### ISSUE TITLE
Sync communication，50 client 30s Concurrent Request， Log WARN is com.alipay.sofa.rpc.event.EventBus [] - This queue is full

### ISSUE THREAD

**Issue by xuliguov5** [sofastack/sofa-rpc#1009]
### Describe the bug
Sync communication，50 client 30s Concurrent Request， Log WARN is
 [SOFA-client--5-T6] [WARN ] com.alipay.sofa.rpc.event.EventBus [] - This queue is full when post event to async execute, queue size is 256, please optimize this async thread pool of eventbus.
[SOFA-client--5-T14] [WARN ] com.alipay.sofa.rpc.event.EventBus [] - This queue is full when post event to async execute, queue size is 1, please optimize this async thread pool of eventbus.

场景描述：
50个线程 30s内 不停的请求，数据包requets size 10byte/100byte.  response size 10byte/100byte. 都会有上方的提示，当requets size大于1k时，提示就消失了。

看源码，"async.pool.queue": 256, 异步的线程池设置，只会在异步的时候用到，同步的时候 怎么会报这种提示。

### Environment

- SOFARPC version:
- JVM version (e.g. `java -version`):
- OS version (e.g. `uname -a`):
- Maven version:
- IDE version:

**Comment by ujjboy** [comment]
@xuliguov5 当async线程池满的时候，麻烦执行下 jstack  把 jstack 日志上传下看看

**Comment by OrezzerO** [comment]
暂时关闭,有需要可以打开.
Close this issue temporarily, open it if necessarily.
