### ISSUE TITLE
SOFA-CLI-IO线程过多

### ISSUE THREAD

**Issue by 99246255** [sofastack/sofa-rpc#1011]
### Describe the bug
所有都是默认的sofa-rpc配置
仅用了client调用，但是发现有几千runnable 的SOFA-CLI-IO-XXX-XX(例如SOFA-CLI-IO-1610-T7)
dump文件
链接: https://pan.baidu.com/s/1uDF0gtOqkAv6p4BHL77gUg 提取码: rk5y 
这个是线程池配置问题还是其他的

- SOFARPC version: 5.6.2
- JVM version (e.g. `java -version`):jdk1.8.0_151
- OS version (e.g. `uname -a`):Linux3.10.0
- Maven version:
- IDE version:

**Comment by ujjboy** [comment]
从 1610 看应该是使用问题， 是不是 new 了很多 consumerconfig ?

ConsumerConfig.refer() 拿到接口代理类是支持并发调用的，保留唯一就行

**Comment by 99246255** [comment]
> 
> 
> 从 1610 看应该是使用问题， 是不是 new 了很多 consumerconfig ?
> 
> ConsumerConfig.refer() 拿到接口代理类是支持并发调用的，保留唯一就行

没有

**Comment by OrezzerO** [comment]
Consumer 需要做成单例的，每次请求都创建的话，会造成内存泄露。
