### ISSUE TITLE
SOFARPC链路数据透传中文乱码

### ISSUE THREAD

**Issue by gwcai** [sofastack/sofa-rpc#1014]
### Describe the bug

在provider端写入数据，在consumer端获取数据，中文为乱码

### Steps to reproduce
启动provider
启动consumer
consumer调用provider的exception方法，在过滤器SofaRpcFilter中根据异常信息网context中写数据。
consumer收到数据有中文乱码

### Minimal yet complete reproducer code (or GitHub URL to code)
https://github.com/gwcai/fd-sofa-base

### Environment

- SOFARPC version:  sofaboot-enterprise-dependencies  3.4.2
- JVM version (e.g. `java -version`): 1.8
- OS version (e.g. `uname -a`): windows 7
- Maven version: 3.5.2
- IDE version:2019.1.3 Ultimate edition

**Comment by OrezzerO** [comment]
你是用的是rest协议进行调用， 透传数据 会放在Http header 传输， 需要使用 URLEncoder.encode(“中文”,"UTF-8")  编码后传输

**Comment by gwcai** [comment]
> 你是用的是rest协议进行调用， 透传数据 会放在Http header 传输， 需要使用 URLEncoder.encode(“中文”,"UTF-8") 编码后传输

用bolt协议还需要这样编码吗？

**Comment by OrezzerO** [comment]
bolt 并不需要
