### ISSUE TITLE
通过注解方式java代码生成对应的protobuf文件给其他语言使用

### ISSUE THREAD

**Issue by Dreampie** [sofastack/sofa-rpc#1027]
![image](https://user-images.githubusercontent.com/3667080/114025551-cfe84c00-98a7-11eb-919d-d8328ea374b8.png)

**Comment by OrezzerO** [comment]
有几个问题: 
1. 如果目标语言需要通过 protobuf 调用 sofarpc ,那么它必须使用 grpc (如果开发目标语言的 rpc client,那就本末倒置了)
2. 如果用需要用 grpc 通讯, grpc 不支持多参数, 所以和 java interface 不兼容.
我们的建议是,直接定义 pb 文件,然后用  bolt + hessian 的通讯方式
