### ISSUE TITLE
配置客户端调用timeout的疑问

### ISSUE THREAD

**Issue by isharpever** [sofastack/sofa-rpc#1035]
### Your question

使用@SofaReference+@SofaReferenceBinding配置客户端，如何修改【全局缺省的客户端调用timeout】？

如下是com.alipay.sofa.rpc.client.AbstractCluster#resolveTimeout按优先级决定”客户端调用timeout“的逻辑：
```
        // 先去调用级别配置
        Integer timeout = request.getTimeout();
        if (timeout == null) {
            // 取客户端配置（先方法级别再接口级别）
            timeout = consumerConfig.getMethodTimeout(request.getMethodName());
            if (timeout == null || timeout < 0) { //<---@SofaReferenceBinding#timeout的缺省值造成该条件默认永不满足
                // 再取服务端配置
                timeout = (Integer) providerInfo.getDynamicAttr(ATTR_TIMEOUT);
                if (timeout == null) {
                    // 取框架默认值
                    timeout = getIntValue(CONSUMER_INVOKE_TIMEOUT); //<---该全局缺省值没有机会生效
                }
            }
        }
```
当@SofaReference+@SofaReferenceBinding配置客户端时，由于@SofaReferenceBinding中写死了timeout的缺省值是3000，那么按照上述逻辑，META-INF/sofa-rpc/rpc-config.json中配置的全局缺省值(consumer.invoke.timeout)没有机会生效。

### Your scenes

无论生产环境，还是开发/测试环境，为节省配置，一般都需要【全局缺省的客户端调用timeout】，在此基础之上，再对各接口/方法按需配置。然而使用@SofaReference+@SofaReferenceBinding时，【全局缺省的客户端调用timeout】相当于固定了，没有办法调整。如果@SofaReferenceBinding#timeout缺省的3000不满足场景，我现在只能这样做：
（1）把客户端应用内的@SofaReferenceBinding先逐个设置timeout=0
（2）把服务端应用内的@SofaServiceBinding先逐个设置timeout=0
（3）配置META-INF/sofa-rpc/rpc-config.json，设置一个符合场景的【consumer.invoke.timeout】
（4）按需调整各接口/方法的@SofaReferenceBinding#timeout
太繁琐了。

### Your advice

（1）希望在使用@SofaReference+@SofaReferenceBinding配置客户端时，有便捷办法修改【全局缺省的客户端调用timeout】
（2）希望在按优先级决定”客户端调用timeout“时，客户端侧设置的【全局缺省值】优先级高于服务端配置的【全局缺省值】。即：
【调用级别配置>>>>>客户端方法/接口级配置>>>>>服务端方法/接口级配置>>>>>客户端全局缺省值>>>>>服务端全局缺省值】

### Environment

- SOFARPC version: sofa-rpc-all-5.7.3
- JVM version (e.g. `java -version`): 无关
- OS version (e.g. `uname -a`): 无关
- Maven version: 无关
- IDE version: 无关

**Comment by OrezzerO** [comment]
对，按现在的设计来说，是有这个问题， 全局 timeout 无法生效，这个 [issue](https://github.com/sofastack/sofa-rpc/issues/1036) 中说的也是这个问题。有一个方案是将注解中的超时时间默认值改为 0， 在后续判断中如果超时时间是 0，就用默认时间。
