### ISSUE TITLE
rpc的消费者使用注解模式下超时时间的小优化

### ISSUE THREAD

**Issue by huangyong239** [sofastack/sofa-rpc#1036]
### Your question

rpc，在消费者使用注解模式的时候，由于会注入默认的超时时间，导致rpc服务提供者配置的超时时间失效，例如roc提供者配置的超时时间为5s，当消费者端使用注解方式且没有配置超时时间，由于会优先使用消费者段默认的3s的超时时间，则当服务端配置的超时时间>3s时，会导致服务端配置的超时时间失效，不起作用。
另外这边已验证：消费者使用xml模式下消费者都不配置超时时间时，是不会走消费者端的默认的超时时间的，是可以走服务提供者的超时时间的，这个和注解模式的超时时间的用法有点不统一。

### Your scenes

**银行这边原来的应用都是dubbo开发的，很多超时时间都是配置在服务的提供端（dubbo官网推荐超时时间配置在），由于上面的情况存在，导致原来配置在服务提供端的超时时间的处理都需要做调整，改动量有点大。

### Your advice

请问是否有办法增加一个参数的配置，做上面情况的兼容处理，这个参数不配的走原来的流程，如果配置消费端的【超时的默认值是不开启】的参数配置为1，就不用消费端的默认超时时间的值，这样**银行的从基于dubbo开发的功能迁移到sofa的rpc服务时，改动量会小很多，同时rpc的消费端的超时时间控制也会更灵活，更兼容不同银行/保险公司的业务需求。

### Environment

- SOFARPC version:rpc-enterprise-sofa-boot-starter    3.4.2
- JVM version :jdk1.8
- OS version :无关
- Maven version:无关
- IDE version:无关

**Comment by dajitui** [comment]
这种情况应该是不存在的，它会先从配置读取，没有再从客户端配置拿，再没有从服务端超时，最终还是没有从框架默认值拿consumer.invoke.timeout
com.alipay.sofa.rpc.client.AbstractCluster#resolveTimeout
`/**
     * 决定超时时间
     *
     * @param request        请求
     * @param consumerConfig 客户端配置
     * @param providerInfo   服务提供者信息
     * @return 调用超时
     */
    private int resolveTimeout(SofaRequest request, ConsumerConfig consumerConfig, ProviderInfo providerInfo) {
        // 动态配置优先
        final String dynamicAlias = consumerConfig.getParameter(DynamicConfigKeys.DYNAMIC_ALIAS);
        if (StringUtils.isNotBlank(dynamicAlias)) {
            String dynamicTimeout = null;
            DynamicConfigManager dynamicConfigManager = DynamicConfigManagerFactory.getDynamicManager(
                consumerConfig.getAppName(),
                dynamicAlias);

            if (dynamicConfigManager != null) {
                dynamicTimeout = dynamicConfigManager.getConsumerMethodProperty(request.getInterfaceName(),
                    request.getMethodName(),
                    "timeout");
            }

            if (DynamicHelper.isNotDefault(dynamicTimeout) && StringUtils.isNotBlank(dynamicTimeout)) {
                return Integer.parseInt(dynamicTimeout);
            }
        }
        // 先去调用级别配置
        Integer timeout = request.getTimeout();
        if (timeout == null) {
            // 取客户端配置（先方法级别再接口级别）
            timeout = consumerConfig.getMethodTimeout(request.getMethodName());
            if (timeout == null || timeout < 0) {
                // 再取服务端配置
                timeout = (Integer) providerInfo.getDynamicAttr(ATTR_TIMEOUT);
                if (timeout == null) {
                    // 取框架默认值
                    timeout = getIntValue(CONSUMER_INVOKE_TIMEOUT);
                }
            }
        }
        return timeout;
    }`

**Comment by EvenLjj** [comment]
@dajitui 感谢回复，你的分析没有问题，消费端超时时间配置优先级高于提供端高于默认兜底配置。不过上面的问题是，消费端现在提供了默认的超时时间，导致了提供端不管配置多少都不起作用，这个问题，去掉消费端的默认配置就行了。
***
@dajitui Thank you for your reply. Your analysis is no problem. The timeout configuration on the consumer side has a higher priority than the provider side，and than the default configuration. However, the above problem is that the consumer now provides a default timeout, which causes the provider to not work regardless of the configuration. For this problem, just remove the default configuration of the consumer.
