### ISSUE TITLE
One NPE in RouterChain.java

### ISSUE THREAD

**Issue by containerAnalyzer** [sofastack/sofa-rpc#1048]
Hello,

Our static analyzer found a following potential NPE. We have checked the feasibility of this execution trace. It is necessary to defend this vulnerability to improve the code quality.

Here is the bug trace.

1. Return **null** to caller
https://github.com/sofastack/sofa-rpc/blob/4f824e2b2897ce5b6cbc8944219e0c96b56ebd02/core/api/src/main/java/com/alipay/sofa/rpc/ext/ExtensionLoader.java#L428

2. Function **getExtensionClass** executes and stores the return value to the parameter of **add**, which can be **null**
https://github.com/sofastack/sofa-rpc/blob/4f824e2b2897ce5b6cbc8944219e0c96b56ebd02/core/api/src/main/java/com/alipay/sofa/rpc/client/RouterChain.java#L149

3. Function **add** executes and returns. One of the elements in **extensionRouters** can be **null**.
https://github.com/sofastack/sofa-rpc/blob/4f824e2b2897ce5b6cbc8944219e0c96b56ebd02/core/api/src/main/java/com/alipay/sofa/rpc/client/RouterChain.java#L149

4. Function **next** executes and stores the return value to **extensionRouter** (**extensionRouter** can be null)
https://github.com/sofastack/sofa-rpc/blob/4f824e2b2897ce5b6cbc8944219e0c96b56ebd02/core/api/src/main/java/com/alipay/sofa/rpc/client/RouterChain.java#L167

5. **extensionRouter** is passed as **this** pointer to function **getExtInstance** (**extensionRouter** can be **null**), which will lead to null pointer dereference
https://github.com/sofastack/sofa-rpc/blob/4f824e2b2897ce5b6cbc8944219e0c96b56ebd02/core/api/src/main/java/com/alipay/sofa/rpc/client/RouterChain.java#L168

Commit: 4f824e2b2897ce5b6cbc8944219e0c96b56ebd02

**Comment by OrezzerO** [comment]
Thank you for reporting the bug. When `ConsumerConfig` is set a wrong router alias ,it will throw NPE.We will appreciate if you can submit a PR. 🙏
