### ISSUE TITLE
Support for JDK 11

### ISSUE THREAD

**Issue by alaneuler** [sofastack/sofa-rpc#1055]

**Comment by leizhiyuan** [comment]
do you mean 

run in jdk 11 or compile with jdk11？

**Comment by nobodyiam** [comment]
Shall we talk about java 17 now? 😀

**Comment by StringKe** [comment]
I tried `sofaboot 3.12.1` and the rpc component fails to register the service correctly.

At the same time, there are some differences between `sofaboot` and `sofarpc` version updates.
