### ISSUE TITLE
sofarpc使用直连方式callback有问题

### ISSUE THREAD

**Issue by dannishushu** [sofastack/sofa-rpc#1114]
直连方式directUrl，callback有问题， sync没有问题
callback时服务端没有收到，客户端的SofaResponseCallbackImpl也没有响应

服务端：
ServerConfig serverConfig = new ServerConfig()
                    .setPort(port)
                    .setDaemon(false);
ProviderConfig providerConfig = new ProviderConfig<>()
                    .setInterfaceId(objectInterface.getName())
                    .setRef(clazz.newInstance())
                    .setServer(serverConfig)
                    .setParameter("serverId", objectInterface.getName());

providerConfig.export();

客户端：
ConsumerConfig<interfaceClass> consumerConfig = new ConsumerConfig<interfaceClass>()
                .setInterfaceId(interfaceClass.getName())
                .setDirectUrl(server)
                .setInvokeType(RpcConstants.INVOKER_TYPE_CALLBACK)
                .setOnReturn(sofaResponseCallbackImpl);

return consumerConfig.refer();

然后客户端调用通过refer拿到的接口类，ICallService callService调用方法
callService.hello("test")
sync方式没问题，callback不行
callback方式比sync方式在获取的时候多的两行代码是：
.setInvokeType(RpcConstants.INVOKER_TYPE_CALLBACK)
.setOnReturn(sofaResponseCallbackImpl);

**Comment by OrezzerO** [comment]
我测了下没有问题，这是我客户端测试代码： 
``` java
public class Client {
    public static void main(String[] args) throws InterruptedException {
        String url = System.getProperty("server");
        if (Strings.isNullOrEmpty(url)) {
            url = "localhost:12200";
        }
        ConsumerConfig<EchoService> consumerConfig = new ConsumerConfig<EchoService>()
                .setInterfaceId(EchoService.class.getName()) // 设置服务名称
                .setProtocol("bolt") // 指定协议
                .setRegister(false) // 是否去注册中心订阅服务
                .setDirectUrl(url) // 设置直连地址
                .setInvokeType(RpcConstants.INVOKER_TYPE_CALLBACK)
                .setOnReturn(new SofaResponseCallBackImpl());
        EchoService echoService = consumerConfig.refer(); // 生成引用代理

        System.out.println(echoService.echo("Hello world")); // 发起调用并输出

        Thread.sleep(1000);
    }

    public static class SofaResponseCallBackImpl implements SofaResponseCallback{

        @Override
        public void onAppResponse(Object appResponse, String methodName, RequestBase request) {
            System.out.println("callBack result" + appResponse);
        }

        @Override
        public void onAppException(Throwable throwable, String methodName, RequestBase request) {

        }

        @Override
        public void onSofaException(SofaRpcException sofaException, String methodName, RequestBase request) {

        }
    }

}
```
