### ISSUE TITLE
BusinessPool增加Disruptor队列类型

### ISSUE THREAD

**Issue by SteNicholas** [sofastack/sofa-rpc#112]
您好，关于BoltServer用到的BusinessPool类考虑过增加一种队列类型：Disruptor吗？Disruptor高性能，低延，相比于一些BlockingQueue来说速度快。

**Comment by ujjboy** [comment]
@SteNicholas  是一个好思路，不过 Disruptor 直接并非面向 Java 的队列接口，如果需要支持 Disruptor 并发框架，可能涉及到底层 [Bolt](http://github.com/alipay/sofa-bolt) 的改动。

欢迎一起完善此功能。

**Comment by SteNicholas** [comment]
@ujjboy OK，我把之前的PR修改完毕后想参与此功能的完善可以吗？

**Comment by ujjboy** [comment]
@SteNicholas 欢迎。
