### ISSUE TITLE
运行quick start的demo报InaccessibleObjectException错误

### ISSUE THREAD

**Issue by yida1313** [sofastack/sofa-rpc#1123]
sofa-rpc版本5.7.9
java 11
Eclipse上运行官方主页上quick start的DEMO报错。
（https://www.sofastack.tech/projects/sofa-rpc/getting-started-with-rpc/）
求教如何解决？谢谢！

---------报错信息------------
SofaRpcRuntimeException: RPC-010080001: 使用 [javassist] 构造代理出现错误. 

java.lang.reflect.InaccessibleObjectException: Unable to make protected final java.lang.Class java.lang.ClassLoader.defineClass(java.lang.String,byte[],int,int) throws java.lang.ClassFormatError accessible: module java.base does not "opens java.lang" to unnamed module @543c6f6d

**Comment by EvenLjj** [comment]
Hi @yida1313 , pls see https://stackoverflow.com/questions/41265266/how-to-solve-inaccessibleobjectexception-unable-to-make-member-accessible-m .

**Comment by yida1313** [comment]
> Hi @yida1313 , pls see https://stackoverflow.com/questions/41265266/how-to-solve-inaccessibleobjectexception-unable-to-make-member-accessible-m .

yeah~~ it works, thanks so much.
(but still a little troublesome... maybe fixed in future?)
