### ISSUE TITLE
sofarpc优雅停机如何设置？

### ISSUE THREAD

**Issue by zeshaoy** [sofastack/sofa-rpc#1133]
sofaboot是都支持优雅停机，和sofarpc怎样配合使用，实现优雅停机的目的？谢谢

**Comment by EvenLjj** [comment]
Hi @zeshaoy, how to achieve graceful shutdown and why need graceful shutdown，can read my [study notes](https://evenljj.github.io/2021/04/01/rpclevel2/#more). This is a brief introduction, and how to implement in sofarpc can refer to the source code. There is no source code analysis article and the explanation will not be clear for a while. If you are interested, you can read the source code and write a learning article to [SOFASTACK](https://www.sofastack.tech/tags/%E5%89%96%E6%9E%90-sofarpc-%E6%A1%86%E6%9E%B6/). We welcome you to join SOFASTACK.

**Comment by zeshaoy** [comment]
> sofarpc

您好，感谢解答。令，再请教一个问题：sofarpc 框架应该就默认支持优雅关闭的吧？不需要额外再配置什么吧？

**Comment by EvenLjj** [comment]
As this article said, graceful shutdown must be established at the upper level of operation and maintenance. SOFABoot has integrated graceful shutdown. However, if kill -9 is still used for shutdown, graceful shutdown will not work. This is a precaution. At the same time, the operation and maintenance level also needs to control the switch flow. When a machine is shutting down gracefully, it is best not to let new requests in.
