### ISSUE TITLE
SOFAboot 3.2.1和SOFARPC5.5.25.5.2和SOFARregistry5.2 服务无法注册

### ISSUE THREAD

**Issue by fengyu415** [sofastack/sofa-rpc#1134]
1、问题 ：SOFAboot 3.2.1和SOFARPC5.5.2和SOFARregistry5.2 服务无法注册

描述 ：原有使用SOFAboot 3.1.4和sofarpc5.5.2和SOFARregistry5.2，SOFARregistry注册中心用的最新版5.4.2 ，服务可以正常注册发现
修改为SOFAboot 3.2.1 ，服务注册失败
不定义SOFARPC5.5.2，就继承SOFAboot 3.2.1的rpc版本 3.2.1，也报错

希望得到正确的版本匹配信息

源码地址，因公司不让网络严格，将源码放到阿里云服务器上
地址：http://47.96.191.50:8888/down/0Vcg3zTz4tEm
项目README.md中有详细搭建过程

**Comment by ujjboy** [comment]
已知问题：https://github.com/sofastack/sofa-boot/issues/566

可以升级到新版本 SOFABoot，或者试试增加如下代码绕过
```java
public class RPCClientApplication {
……
    
    @Bean
    @ConditionalOnMissingBean
    public SofaRegistryConfigurator sofaRegistryConfigurator() {
        return new SofaRegistryConfigurator();
    }
}
```
