### ISSUE TITLE
server thread pool busy

### ISSUE THREAD

**Issue by wind-hx** [sofastack/sofa-rpc#1139]
### Your question

如何设置线程池大小？服务器4核cpu使用率才百分之三不到就提示这个错误了，每次都重启才能解决

- SOFARPC version:5.7.7
- JVM version (e.g. `java -version`):11.0.10
- OS version (e.g. `uname -a`):Linux VM-4-14-centos 4.18.0-305.3.1.el8.x86_64 #1 SMP Tue Jun 1 16:14:33 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

**Comment by nobodyiam** [comment]
I think you may reference [this](https://www.sofastack.tech/projects/sofa-rpc/application-rpc-config/) and [this](https://www.sofastack.tech/projects/sofa-rpc/custom-threadpool/)
