### ISSUE TITLE
new registry component  polaris

### ISSUE THREAD

**Issue by ZLBer** [sofastack/sofa-rpc#1141]
### Your question

hi, i want to add a new registry component polaris , the project website : https://github.com/polarismesh/polaris , https://polarismesh.cn/#/ . can i try to do this ？

related issue: https://github.com/polarismesh/polaris/issues/163

**Comment by ZLBer** [comment]
@EvenLjj  I will do this as soon as possible. if there is a problem, I will raise it under this issue.

**Comment by EvenLjj** [comment]
> @EvenLjj I will do this as soon as possible. if there is a problem, I will raise it under this issue.

@ZLBer Welcome, you can ask questions anytime if you have any questions. The related documents of the extension mechanism can be referred to "https://www.sofastack.tech/blog/sofa-rpc-framework-overall-extension".
