### ISSUE TITLE
ProviderConfig setTimeout 返回结果范型没了

### ISSUE THREAD

**Issue by wind-hx** [sofastack/sofa-rpc#1142]
### Describe the bug

https://github.com/sofastack/sofa-rpc/blob/303ae5ebd7ccaa6b87380cedb2666d084937c252/core/api/src/main/java/com/alipay/sofa/rpc/config/ProviderConfig.java?_pjax=%23js-repo-pjax-container%2C%20div%5Bitemtype%3D%22http%3A%2F%2Fschema.org%2FSoftwareSourceCode%22%5D%20main%2C%20%5Bdata-pjax-container%5D#L449

为什么setTimeout返回结果没有范型了，是设计如此吗？还是漏掉了

**Comment by nobodyiam** [comment]
This looks like a bug to me. Would you please help to fix it?

**Comment by wind-hx** [comment]
> This looks like a bug to me. Would you please help to fix it?

https://github.com/sofastack/sofa-rpc/pull/1143
