### ISSUE TITLE
SofaBootRpcAllTest run failed, class SofaGreeterTriple not found

### ISSUE THREAD

**Issue by Kunple-w** [sofastack/sofa-rpc#1149]
### Describe the bug

SofaBootRpcAllTest run error, import `io.grpc.examples.helloworld` package failed:

![image](https://user-images.githubusercontent.com/15710694/146662834-e8e7cbc0-92b2-4ca0-9fbb-4452263a41a4.png)

### Environment

- SOFARPC version: 3.9.0 & 3.10.0-s
- JVM version (e.g. `java -version`): jdk8
- OS version (e.g. `uname -a`): Darwin
- Maven version: 3.6.1
- IDE version: idea

**Comment by EvenLjj** [comment]
@Kunple-w Mark the java as test resources root.
![image](https://user-images.githubusercontent.com/15122299/146707271-795753cf-0a6d-4e85-aef0-64b2eef7d000.png)
