### ISSUE TITLE
sofa与hystrix集成时，能否通过xml方式（spring风格）配置hystrix对应的fallback逻辑。

### ISSUE THREAD

**Issue by wentfar** [sofastack/sofa-rpc#1151]
场景
sofa与hystrix集成时，有以下代码：

// 全局开启
RpcConfigs.putValue(HystrixConstants.SOFA_HYSTRIX_ENABLED, true);

// 对特定 Consumer 开启
ConsumerConfig consumerConfig = new ConsumerConfig()
.setInterfaceId(HelloService.class.getName())
.setParameter(HystrixConstants.SOFA_HYSTRIX_ENABLED, String.valueOf(true));

问题：
我目前用了sofastack框架，HelloService以xml方式被consumer消费，请问fallback实现类是否可以在xml消费者中配置，如果不可以该怎么集成？

@ScienJus @ujjboy @JervyShi

**Comment by JervyShi** [comment]
SOFARPC`s Hystrix integration currently only supported in API mode settings, could be found at [HystrixFilterSyncTest](https://github.com/sofastack/sofa-rpc/blob/master/test/test-integration/src/test/java/com/alipay/sofa/rpc/hystrix/HystrixFilterSyncTest.java#L97) , if you need to configure it in xml, feel free  to create PR for [sofa-rpc-boot-projects](https://github.com/sofastack/sofa-rpc-boot-projects) to support it.

**Comment by wentfar** [comment]
> SOFARPC`s Hystrix integration currently only supported in API mode settings, could be found at [HystrixFilterSyncTest](https://github.com/sofastack/sofa-rpc/blob/master/test/test-integration/src/test/java/com/alipay/sofa/rpc/hystrix/HystrixFilterSyncTest.java#L97) , if you need to configure it in xml, feel free to create PR for [sofa-rpc-boot-projects](https://github.com/sofastack/sofa-rpc-boot-projects) to support it.

OK，Thanks！
