### ISSUE TITLE
异步RPC暂时只支持xml方式，没有注解方式

### ISSUE THREAD

**Issue by zzzzk12345** [sofastack/sofa-rpc#1159]
建议增加注解实现

**Comment by seeflood** [comment]
@evenliu @OrezzerO 我翻了下文档，异步调用好像只能通过xml配置，我们是否可以把“支持注解方式配异步调用”作为一个社区任务发出来?

**Comment by EvenLjj** [comment]
@zzzzk12345 支持异步化调用的，在SofaReference注解下binding中methodInfos中设置
