### ISSUE TITLE
使用consul作为注册中心，不支持配置acl

### ISSUE THREAD

**Issue by Kunple-w** [sofastack/sofa-rpc#1168]
### Your question

使用consul作为注册中心时，不支持配置acl，sofaboot中也没有配置项支持

坐标: com.alipay.sofa.rpc.registry.consul.ConsulRegistry

建议增加

### Environment

- SOFARPC version: 5.7.7
- JVM version (e.g. `java -version`): jdk8
- OS version (e.g. `uname -a`): linux
- Maven version: 3.8
- IDE version: idea

**Comment by JervyShi** [comment]
@Kunple-w 有兴趣提交 PR 支持一下么？

**Comment by Kunple-w** [comment]
> @Kunple-w 有兴趣提交 PR 支持一下么？

好的，稍后我会看下
