### ISSUE TITLE
Small optimization, StringBuilder is better than StringBuffer in HelpTelnetHandler.telnet()

### ISSUE THREAD

**Issue by MingJunDuan** [sofastack/sofa-rpc#1170]
### Describe the bug
Actually, this is not a bug, just an optimization.
StringBuilder is better then StringBuffer in thread-safety context as we all know.

### Environment

- SOFARPC version:
- JVM version (e.g. `java -version`):
- OS version (e.g. `uname -a`):
- Maven version:
- IDE version:

**Comment by EvenLjj** [comment]
@MingJunDuan Welcome, would you like to submit a PR to optimize this issue.

**Comment by MingJunDuan** [comment]
> @MingJunDuan Welcome, would you like to submit a PR to optimize this issue.

I'd like to contribute to sofa-rpc，I will submit a PR for it latter.
