### ISSUE TITLE
请教设置high low watermark 的具体操作方法和过程

### ISSUE THREAD

**Issue by qinqinhaijie** [sofastack/sofa-rpc#1174]
## 原因
RPC在写出数据的时候，会检测当前的ChannelOutboundBuffer的大小，如果超过了WRITE_BUFFER_HIGH_WATER_MARK（默认64K），就会限流，报write overflow的异常。
这个是为了保护客户端，防止无界的ChannelOutboundBuffer被打爆，导致资源耗尽。
通常情况下，网络有问题，导致写出失败；或者下游压力太大，不能处理这么多网络包的时候会出现这样的异常。

## 解决办法：
建议首先排查网络环境（网卡打满也是一种）
网络环境没问题的情况下，看下是否是流量过大，导致下游处理不过来。，如果是这种，可能意味着，这就是压测的瓶颈了。可以评估下游扩容，性能优化等方式来解决。
如果确实认为64k 也不够用. 可以自行调整

-Dbolt.netty.buffer.low.watermark  
-Dbolt.netty.buffer.high.watermark
值自己算一下，默认是32\*1024 和64\*1024

_Originally posted by @leizhiyuan in https://github.com/sofastack/sofa-rpc/issues/551#issuecomment-475186984_

**Comment by nobodyiam** [comment]
> -Dbolt.netty.buffer.low.watermark
-Dbolt.netty.buffer.high.watermark

I believe the original post already provides the guide to set high & low watermark.
