### ISSUE TITLE
jackson 序列化在 sofaboot 下无法复用 spring 注入的 mapper 对象

### ISSUE THREAD

**Issue by Sharember** [sofastack/sofa-rpc#1176]
### Your question

JacksonSerializer 中的 ObjectMapper 对象是自己 new 出来的，并且没有办法修改。

在 sofaboot(springboot) 环境下，spring 会在上下文中创建一个全局可用的 bean，并且支持对该 bean 进行各种方式配置。比如在 application.properties 中配置 Jackson 的 feature。

JacksonSerializer 当前的实现无法使用 spring 注入的 bean，也就无法使用 spring 的方式配置各种 feature，在使用 json 序列化的时候有些不方便。（目前只能通过设置 jvm 启动参数的方式配置 feature）

### Your advice

JacksonSerializer 添加一个 public 方法，支持自定义 mapper。在 sofaboot 中，将 spring 的 mapper 注入到 JacksonSerializer 里

### Environment

- SOFARPC version:
- JVM version (e.g. `java -version`):
- OS version (e.g. `uname -a`):
- Maven version:
- IDE version:

**Comment by nobodyiam** [comment]
I think it's better to customize the JSON serializer instead of just customizing the object mapper inside the current JacksonSerializer.
