### ISSUE TITLE
客户端通过反射获取consumerConfig.refer()后创建对象时，报java.lang.NullPointerException，如下述示例中的obj。求解答

### ISSUE THREAD

**Issue by qinqinhaijie** [sofastack/sofa-rpc#1183]
public static void main(String[] args) throws InterruptedException, NoSuchMethodException, InvocationTargetException, InstantiationException, IllegalAccessException
    {
        ResendHandler resendHandler = new ResendHandler();

        ConsumerConfig<HelloService> consumerConfig = new ConsumerConfig<HelloService>()
                .setInterfaceId(HelloService.class.getName()) // 指定接口
                //.setInvokeType(RpcConstants.INVOKER_TYPE_FUTURE)
                .setInvokeType(RpcConstants.INVOKER_TYPE_CALLBACK)
                .setConnectTimeout(8000)
                .setTimeout(5000)
                .setOnReturn(new RpcCallbackImpl(resendHandler))
                .setProtocol("bolt") // 指定协议
                .setDirectUrl("bolt://127.0.0.1:12200"); // 指定直连地址

        // 生成代理类
        HelloService helloService = consumerConfig.refer();

        Class clazz = helloService.getClass();
        System.out.println("clazz:" + helloService.getClass());//clazz:class reflectrpc.HelloService_proxy_0

        Constructor constructor = clazz.getConstructor();
        System.out.println("constructor:" + constructor);//constructor:public reflectrpc.HelloService_proxy_0()

        Object obj = constructor.newInstance();
        System.out.println("obj:" + obj);//Exception in thread "main" java.lang.NullPointerException
}

**Comment by EvenLjj** [comment]
@qinqinhaijie Why do you need to do this? Doesn't look like normal operation.
