### ISSUE TITLE
[Discuss] Do we have an example module contains sofa features example

### ISSUE THREAD

**Issue by MingJunDuan** [sofastack/sofa-rpc#1185]
### Your question

Just like Dubbo examples or Shardingsphere exampls(https://github.com/apache/shardingsphere/tree/master/examples)

### Your scenes

When we use sofa-rpc/sofa-boot in project,  many developers feel it's hard to find an example for how to use a feature 

### Your advice

Developers will feel much more friendly and easier if sofa/sofa-boot examples which contains sofa/sofa-boot features. We can add an examples module in project and show how to use sofa/sofa-boot features. 

### Environment

- SOFARPC version:
- JVM version (e.g. `java -version`):
- OS version (e.g. `uname -a`):
- Maven version:
- IDE version:

**Comment by EvenLjj** [comment]
@MingJunDuan sofa-rpc standalone example in [rpc examples](https://github.com/sofastack/sofa-rpc/tree/master/example/src/test/java/com/alipay/sofa/rpc) and sofa boot example can find in [sofa-boot examples](https://github.com/orgs/sofastack-guides/repositories)
