### ISSUE TITLE
消费端如何自定义业务线程池？

### ISSUE THREAD

**Issue by dragon-zhang** [sofastack/sofa-rpc#1186]
### Your question

消费端如何自定义业务线程池？

### Your scenes

网关中间件做协议兼容时，对所有RPC框架想用同一个自定义的共享线程池，以提高线程池资源利用率。

### Your advice

提供一个类似`dubbo`的线程池`SPI扩展`。

### Environment

- SOFARPC version: 5.7.6
- JVM version (e.g. `java -version`): 1.8
- OS version (e.g. `uname -a`):
- Maven version:
- IDE version:

**Comment by MingJunDuan** [comment]
这个是服务提供方的自定义线程池:  https://www.sofastack.tech/projects/sofa-rpc/custom-threadpool/

**Comment by dragon-zhang** [comment]
额，主要关心消费方



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: Duan ***@***.***&gt;
发送时间: 2022年3月28日 13:02
收件人: sofastack/sofa-rpc ***@***.***&gt;
抄送: dragon-zhang ***@***.***&gt;, Author ***@***.***&gt;
主题: Re: [sofastack/sofa-rpc] 消费端如何自定义业务线程池？ (Issue #1186)





 
这个是服务提供方的自定义线程池:  https://www.sofastack.tech/projects/sofa-rpc/custom-threadpool/

**Comment by JervyShi** [comment]
@dragon-zhang 消费方使用的是业务当前线程，不存在自定义线程池的概念

**Comment by dragon-zhang** [comment]
了解了，感谢



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: JervyShi ***@***.***&gt;
发送时间: 2022年3月28日 19:27
收件人: sofastack/sofa-rpc ***@***.***&gt;
抄送: dragon-zhang ***@***.***&gt;, Mention ***@***.***&gt;
主题: Re: [sofastack/sofa-rpc] 消费端如何自定义业务线程池？ (Issue #1186)





 
@dragon-zhang 消费方使用的是业务当前线程，不存在自定义线程池的概念

**Comment by dragon-zhang** [comment]
在问个问题，如果是异步调用，走的哪个线程？



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: JervyShi ***@***.***&gt;
发送时间: 2022年3月28日 19:27
收件人: sofastack/sofa-rpc ***@***.***&gt;
抄送: dragon-zhang ***@***.***&gt;, Mention ***@***.***&gt;
主题: Re: [sofastack/sofa-rpc] 消费端如何自定义业务线程池？ (Issue #1186)





 
@dragon-zhang 消费方使用的是业务当前线程，不存在自定义线程池的概念

**Comment by JervyShi** [comment]
这个要看你指的是哪种异步了，如果是指的 SOFA-RPC 的 Async 调用模式，类似 https://github.com/sofastack/sofa-rpc/blob/master/example/src/test/java/com/alipay/sofa/rpc/invoke/future/FutureClientMain.java
依然可以在当前线程中获取 Async 的响应结果。
如果指的是自己通过线程池异步触发 RPC 调用，那么发起方是你的自定义线程池的线程。
当然这里指的是调用端视角，RPC 本身的工作机制其实是纯异步的，请求发起后，response 返回的时候其实是有另外一个线程池在负责接受请求并和请求发起线程交互返回结果，这个在 sofa-rpc 这里目前暂不支持自定义。

**Comment by dragon-zhang** [comment]
您好，我指的是INVOKER_TYPE_CALLBACK这种异步，比如https://github.com/sofastack/sofa-rpc/blob/master/example/src/test/java/com/alipay/sofa/rpc/invoke/callback/CallbackClientMain.java，这个应该是借助了netty的io线程吧




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "sofastack/sofa-rpc"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年3月31日(星期四) 中午11:32
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [sofastack/sofa-rpc] 消费端如何自定义业务线程池？ (Issue #1186)





 
这个要看你指的是哪种异步了，如果是指的 SOFA-RPC 的 Async 调用模式，类似 https://github.com/sofastack/sofa-rpc/blob/master/example/src/test/java/com/alipay/sofa/rpc/invoke/future/FutureClientMain.java
 依然可以在当前线程中获取 Async 的响应结果。
 如果指的是自己通过线程池异步触发 RPC 调用，那么发起方是你的自定义线程池的线程。
 当然这里指的是调用端视角，RPC 本身的工作机制其实是纯异步的，请求发起后，response 返回的时候其实是有另外一个线程池在负责接受请求并和请求发起线程交互返回结果，这个在 sofa-rpc 这里目前暂不支持自定义。

**Comment by MingJunDuan** [comment]
不是Netty的io线程，INVOKER_TYPE_CALLBACK异步使用了SOFA-RPC定义的callBack线程池，见AsyncRuntime和RpcInvokerCallbackListener.onResponse()

**Comment by dragon-zhang** [comment]
十分感谢



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: MingJunDuan ***@***.***&gt;
发送时间: 2022年3月31日 18:45
收件人: sofastack/sofa-rpc ***@***.***&gt;
抄送: dragon-zhang ***@***.***&gt;, Mention ***@***.***&gt;
主题: Re: [sofastack/sofa-rpc] 消费端如何自定义业务线程池？ (Issue #1186)





 
不是Netty的io线程，INVOKER_TYPE_CALLBACK异步使用了SOFA-RPC定义的callBack线程池，见AsyncRuntime和RpcInvokerCallbackListener.onResponse()

**Comment by MingJunDuan** [comment]
可以自行设置线程池core、max、队列大小参数，目前没有setAsyncThreadPool方法

**Comment by MingJunDuan** [comment]
目前AsyncThreadPool除了callBack有用到，EventBus、ConnectionHolder也使用到，改动需要仔细斟酌。

**Comment by dragon-zhang** [comment]
收到，谢谢

**Comment by dajitui** [comment]
我觉得异步回调线程池参数可配置化已经够用了，如果采用自定义共享线程池会存在其他问题的，比如说资源争抢，优先级混乱
