### ISSUE TITLE
sofa-rpc泛化调用

### ISSUE THREAD

**Issue by MingJunDuan** [sofastack/sofa-rpc#1195]
### Your question

sofa泛化调用支持参数是List<Entity>的吗，sofa-rpc的example里面没有找到，发现会有hessian的反序列化异常
如果有例子的话，想对比下是否是我自己使用错误

Help!

### Your scenes

describe your use scenes (why need this feature)

### Your advice

describe the advice or solution you'd like

### Environment

- SOFARPC version:
- JVM version (e.g. `java -version`):
- OS version (e.g. `uname -a`):
- Maven version:
- IDE version:

**Comment by EvenLjj** [comment]
@MingJunDuan Can refer to [the generic test cases](https://github.com/sofastack/sofa-rpc/blob/master/test/test-integration/src/test/java/com/alipay/sofa/rpc/test/generic/GenericTest.java) here.
