### ISSUE TITLE
1、看代码，对实例进行权重降级的时候不能降为 0 吧？因为当服务异常的时候，是希望可以直接将节点摘除的，自动故障剔除是不支持的吗？

### ISSUE THREAD

**Issue by jiaobuchong** [sofastack/sofa-rpc#1198]
1、看代码，对实例进行权重降级的时候不能降为 0 吧？因为当服务异常的时候，是希望可以直接将节点摘除的，自动故障剔除是不支持的吗？
2、现在的做法是权重降级最低是 1，然后等着有流量进来没有异常率就恢复，如果一直没流量进来，就不会恢复？

_Originally posted by @jiaobuchong in https://github.com/sofastack/sofa-rpc/issues/84#issuecomment-1109580140_

**Comment by EvenLjj** [comment]
@jiaobuchong 这个值是可以设置的，具体可以参考 https://www.sofastack.tech/projects/sofa-rpc/configuration-fault-tolerance/

**Comment by jiaobuchong** [comment]
阈值降到 0 之后怎么恢复呢？已经没有流量了
