### ISSUE TITLE
可否增加一个配置功能, 在初始化sofa rpc过程中主动扫描扩展点

### ISSUE THREAD

**Issue by WindySummerF** [sofastack/sofa-rpc#1199]
### Your question

可否增加一个配置功能, 在初始化sofa rpc过程中主动扫描扩展点, 主动将响应的类加载到内存中? 这样可以保证第一次调用流程避免因为加载类导致耗时过长.

### Your scenes

如果没有自动加载这些类, 第一次调用RPC服务耗时会明显增加. 通过jProfiler检测, 发现明显第一次调用RPC的时候JVM内的类会增加大约2000个左右, 在我本地机器, 这个加载过程会耗时大约200ms
(我本地RPC测试环境没有开启连接懒加载, 所以第一次调用之前TCP连接应该就已经建立好了, 这200ms中应该不包含建立连接时间)

![VPOxccG1PR](https://user-images.githubusercontent.com/92834914/165715085-9768bf35-35bd-4bba-b7ca-1b2929c248ad.jpg)

### Your advice

增加一个配置, 如果改配置打开, 则在初始化过程中直接扫描扩展点并将涉及到的类加载到JVM中. 第一次调用时不会因为加载类二耗时过长.

### Environment

- SOFARPC version: 5.7.10
- JVM version (e.g. `java -version`): 1,,8
- OS version (e.g. `uname -a`): linux or windows
- Maven version: 3.8.2
- IDE version: IDEA

**Comment by JervyShi** [comment]
@WindySummerF  Interested in submitting a PR for this function?
