### ISSUE TITLE
Server thread pool busy!

### ISSUE THREAD

**Issue by menglikaibin** [sofastack/sofa-rpc#1200]
### Your question

项目重启偶尔会报这个异常

### Your scenes

![image](https://user-images.githubusercontent.com/29141492/165745584-f13e5141-a592-4379-9635-2186ef301830.png)

### Environment

- SOFARPC version: 3.9.1
- JVM version (e.g. `java -version`):1.8
- OS version (e.g. `uname -a`):
- Maven version:
- IDE version:

**Comment by JervyShi** [comment]
Link https://github.com/sofastack/sofa-rpc/issues/446#issuecomment-1111109401
