### ISSUE TITLE
是否支持服务路由分组的能力？

### ISSUE THREAD

**Issue by boolfunc** [sofastack/sofa-rpc#1205]
### Your question

开源版本的sofa-rpc支持服务路由分组的能力吗？

### Your scenes

印象中，sofa rpc可以跟通过设置run.mode=TEST的方式，实现调用指定的微服务提供方。但是开源版本中没有搜到相关代码。
这个功能支持吗？
我们希望在研发环境，利用类似的能力实现服务分组，实现多环境线下测试

### Environment
环境及版本无关

**Comment by EvenLjj** [comment]
@boolfunc This function is not implemented in the open source version, and it is simple to implement. According to some parameter configurations, and then set directurl when creating consumerconfig in [inBinding](https://github.com/sofastack/sofa-boot/blob/fcad392b7e7e0d94b83de4f63187eaadaa98fd8b/sofa-boot-project/sofa-boot-core/rpc-sofa-boot/src/main/java/com/alipay/sofa/rpc/boot/runtime/adapter/RpcBindingAdapter.java).This way use the [DirectUrlRouter](https://github.com/sofastack/sofa-rpc/blob/10dc5859283c1a06b2cbacf53e6f564abb488af9/core-impl/client/src/main/java/com/alipay/sofa/rpc/client/router/DirectUrlRouter.java) to router. In other words, you can also [customize the router ](https://www.sofastack.tech/projects/sofa-rpc/custom-router/)to meet the needs of your multi environment testing.
