### ISSUE TITLE
是否支持服务端主动调用客户端发送消息？

### ISSUE THREAD

**Issue by crazyStar00** [sofastack/sofa-rpc#1217]
项目中需要服务端给客户端发送消息通知，我看sofa中有EventBus不知道是不是能达到这个目的。

**Comment by EvenLjj** [comment]
[EventBus](https://www.sofastack.tech/blog/sofa-rpc-link-tracking/)不是直接做这个的，你需要的是服务端通知特定客户端，还是通知所有客户端，是什么场景需要这样做的呢？

**Comment by MingJunDuan** [comment]
EventBus是用于服务内部通知事件的，不是用于provider端通知consumer端的的，provider端发送消息通知给consumer，可以看看双工通道、callbback等方式或者走MQ
