### ISSUE TITLE
服务端业务报错，日志不显示

### ISSUE THREAD

**Issue by yanwcc** [sofastack/sofa-rpc#1222]
客户端调用服务端时，当服务端有业务报错时，日志中不体现，只有在middle_error.log中可以看到，有解决方案吗？

**Comment by EvenLjj** [comment]
> 客户端调用服务端时，当服务端有业务报错时，日志中不体现，只有在middle_error.log中可以看到，有解决方案吗？

middle_error.log就是统一错误输出的地方，服务端业务报错可以自行打印业务日志，同时业务报错客户端收到的是01错误码。

**Comment by yanwcc** [comment]
但是我们现在想在服务端的日志中也打出详细的报错堆栈日志，这点目前可以做到吗

**Comment by yanwcc** [comment]
目前是想在服务端，当业务代码抛异常时，在服务端也想展示详细的报错堆栈信息，而不是只在middle_err.log中展示

> > 客户端调用服务端时，当服务端有业务报错时，日志中不体现，只有在middle_error.log中可以看到，有解决方案吗？
> 
> middle_error.log就是统一错误输出的地方，服务端业务报错可以自行打印业务日志，同时业务报错客户端收到的是01错误码。

目前是想在服务端，当业务代码抛异常时，在服务端也想展示详细的报错堆栈信息，而不是只在middle_err.log中展示

**Comment by yanwcc** [comment]
> 目前是想在服务端，当业务代码抛异常时，在服务端也想展示详细的报错堆栈信息，而不是只在middle_err.log中展示
> 
> > > 客户端调用服务端时，当服务端有业务报错时，日志中不体现，只有在middle_error.log中可以看到，有解决方案吗？
> > 
> > 
> > middle_error.log就是统一错误输出的地方，服务端业务报错可以自行打印业务日志，同时业务报错客户端收到的是0

**Comment by EvenLjj** [comment]
@yanwcc middle_err.log也是有错误堆栈的。

**Comment by yanwcc** [comment]
> @yanwcc middle_err.log也是有错误堆栈的。

这个了解的，因为我们是刚升级SOFA-RPC组件的，相关开发人员发现程序报错，但是没有堆栈信息感到比较疑惑，所以想不仅仅是在middle_error.log有堆栈，在本身的服务也打出来堆栈比较好。

**Comment by MingJunDuan** [comment]
可以自行添加一个filter拦截进行业务打印
