### ISSUE TITLE
package triple does not exist issue

### ISSUE THREAD

**Issue by nobodyiam** [sofastack/sofa-rpc#1244]
### Describe the bug

When I cloned the repository and build the project in Intellij, it failed with `package triple does not exist`.

### Expected behavior

It should compile successfully.

### Actual behavior

![image](https://user-images.githubusercontent.com/837658/190037826-3170d87f-6b92-415f-8d5d-ede3d91ea616.png)

I had to manually mark the `remoting/remoting-triple/build/generated/source/proto/main/java` folder as Sources to make it compile successfully.

![image](https://user-images.githubusercontent.com/837658/190037779-cf8104ae-5264-4c0a-99c1-b928f0087b3f.png)

### Steps to reproduce

* git clone repository
* open it in Intellij
* build project

**Comment by MingJunDuan** [comment]
Any idea for it？ It's quite unfriendly, especially for freshman.

**Comment by EvenLjj** [comment]
https://github.com/sofastack/sofa-rpc/pull/1412
