### ISSUE TITLE
如何获取@SofaService注解生成的代理对象

### ISSUE THREAD

**Issue by van0314** [sofastack/sofa-rpc#1246]
如何获取@SofaService注解生成的代理对象

我希望在服务运行中动态修改服务实例的一些属性。所以做了以下操作：
1.使用ApplicationContext.getBean(XXX.class)获取spring管理的服务实例；
2.通过反射修改服务实例属性；
但似乎并不生效。跟踪后发现通过sofaRPC调用的服务实例与spring容器中获取的服务实例不是同一个对象。
我该如何获取sofRPC的服务实例来实现动态修改其属性。

环境：
- SOFARPC version:  3.9.1

**Comment by EvenLjj** [comment]
@van0314 The bean name generated by SofaService has changed by `com.alipay.sofa.runtime.spring.bean.SofaBeanNameGenerator#generateSofaServiceBeanName(java.lang.Class<?>, java.lang.String)` and addDependsOn the orgin bean.So the way you get may not the true you want. If you have other questions, you can raise the issue in sofaboot. More professional personnel on sofaboot will answer this question for you.
