### ISSUE TITLE
JSON.toJSONString() 序列化导致原Map的value转换为LinkedHashMap

### ISSUE THREAD

**Issue by bzl132** [sofastack/sofa-rpc#1254]
### Describe the bug

JSON.toJSONString() 序列化导致原Map的value转换为LinkedHashMap。

### Expected behavior
JSON.toJSONString() 序列化后不影响原实体
### Actual behavior
JSON序列化自定义对象时，调用BeanSerializer.serialize()将对象转换成map
![image](https://user-images.githubusercontent.com/17823187/196385608-7816fbc0-ed0a-41a5-b86b-c8df88fb5fb3.png)
如果，自定义对象中属性是Map时，会将Value替换成递归调用的结果，
![image](https://user-images.githubusercontent.com/17823187/196386254-75c0fec9-8c92-48cb-ad38-4700bc45dd58.png)
这时如果Value是对象，会转换成LinkedHashMap，返回后会替换原始实体
![image](https://user-images.githubusercontent.com/17823187/196388406-58a4955f-da31-492e-aeb6-8db801cd8507.png)

### Steps to reproduce
运行Demo的main方法
### Minimal yet complete reproducer code (or GitHub URL to code)

import com.alipay.sofa.rpc.common.json.JSON;
import java.util.HashMap;
import java.util.Map;

public class TestDemo {

    public static void main(String[] args) {
        BeanEntity bean = new TestDemo.BeanEntity();
        Map<String, ? super ValueEntity> map = new HashMap<>();
        map.put("1", new ValueEntity());
        bean.map = map;

        String jsonString = JSON.toJSONString(bean);

        bean.map.values().forEach(value -> {
            System.out.println(value.getClass().getSimpleName());
        });
    }

    static class BeanEntity {
        Map<String, ? super ValueEntity> map;
    }

    static class ValueEntity {}
}

### Environment

- SOFARPC version:5.7.3
- JVM version (e.g. `java -version`): 11.0.15
- OS version (e.g. `uname -a`): Windows10
- Maven version:3.6.1
- IDE version:idea 2020.2.4

**Comment by EvenLjj** [comment]
![image](https://user-images.githubusercontent.com/15122299/198841091-e8a9a1b1-9cd5-455b-8078-305119da937b.png)
@bzl132 Thank you for feedback. It's really a bug, there should be a new map. Are you interested to fix it?

**Comment by gofow** [comment]
Hi there, I'd like to take a crack at fixing it. Would you mind assigning the issue to me? My thought is to create a fresh Map within the serialize() function when the "bean" is a Map instance, in order to prevent any unpredictable changes due to references.

**Comment by EvenLjj** [comment]
@gofow You are right, looking forward to your participation.
