### ISSUE TITLE
Confuse on the logic judge isRandomPort and the comment  note | 随机端口判断的逻辑和注释容易混淆

### ISSUE THREAD

**Issue by jnan806** [sofastack/sofa-rpc#1256]
### Describe the bug

file-location : `sofa-rpc/core/api/src/main/java/com/alipay/sofa/rpc/common/utils/NetUtils.java`
function : `public static boolean isRandomPort(int port)`

logic in isRandomPort()  is conflict with the comment, so which is the correct ？ the logic or the comment ?

<img width="429" alt="image" src="https://user-images.githubusercontent.com/43714056/196639040-c3bc2670-b812-4059-85ac-15a6bd9bd564.png">
### Environment

- SOFARPC version:
- JVM version (e.g. `java -version`):
- OS version (e.g. `uname -a`):
- Maven version:
- IDE version:

**Comment by EvenLjj** [comment]
@jnan806 A precondition is that the port is between - 1 and 65535. Therefore, the comment that is less than 0 actually refers to - 1 too. Look very carefullyl. If you are interested, you can submit PR to modify this comment.

**Comment by jnan806** [comment]
> @jnan806 A precondition is that the port is between - 1 and 65535. Therefore, the comment that is less than 0 actually refers to - 1 too. Look very carefullyl. If you are interested, you can submit PR to modify this comment.

Does 0 is the random port ?

**Comment by jnan806** [comment]
> @jnan806 A precondition is that the port is between - 1 and 65535. Therefore, the comment that is less than 0 actually refers to - 1 too. Look very carefullyl. If you are interested, you can submit PR to modify this comment.

glad to contribute it. Please sign it to me ?

**Comment by EvenLjj** [comment]
@jnan806 Okay, look forward to more participation.

**Comment by jnan806** [comment]
@EvenLjj  PR has been submitted. And need an approval to run the workflow.
