### ISSUE TITLE
error code-formatter of comment for package-info.java 

### ISSUE THREAD

**Issue by jnan806** [sofastack/sofa-rpc#1273]
### Describe the bug

I found that the all comment for package-info.java in this project is error in code-formatter; Should we fix it ?

For example,
In current code, the comment is under the package-name in package-info.java , the tips of comment would not occurred when the pointer is focus on the package.
<img width="786" alt="image" src="https://user-images.githubusercontent.com/43714056/198877740-f25ea997-6eb6-44e3-b58c-df78c5088fa1.png">

When i move the comment above the package-name in package-info.java, the tips will occur.
<img width="1006" alt="image" src="https://user-images.githubusercontent.com/43714056/198877760-999a88c8-f4a7-4368-a0ab-10b184302ec8.png">

### Environment

- SOFARPC version:
- JVM version (e.g. `java -version`):
- OS version (e.g. `uname -a`):
- Maven version:
- IDE version:

**Comment by EvenLjj** [comment]
@jnan806 Of course, this is also very important. It will be more friendly to users.

**Comment by jnan806** [comment]
Okay, I will optimize it ~
