### ISSUE TITLE
Security alerts need to be solved

### ISSUE THREAD

**Issue by OrezzerO** [sofastack/sofa-rpc#1286]
There are several security alerts in [dependabot](https://github.com/sofastack/sofa-rpc/security/dependabot).

There are two related PR need to be merged: 
* [x] #1285 
* [x] #1279

Security issues should be treated seriously and solved quickly .

**Comment by EvenLjj** [comment]
OK, verify that there is no compatibility problem and can merge.

**Comment by EvenLjj** [comment]
- [ ] https://github.com/sofastack/sofa-rpc/pull/1252
