### ISSUE TITLE
sofa端口自适应，预期不一致

### ISSUE THREAD

**Issue by ZhengweiHou** [sofastack/sofa-rpc#1313]
### Your question
同一台机器启动两个sofa进程，开启端口自适应（AdaptivePort），但是两个进程服务注册端口一致，但实际生效端口不一致。通过验证端口自适应逻辑发现我的机器上`ServerSocket.bind()`预期结果不一致。详细情况如图所示：
![图片](https://user-images.githubusercontent.com/14498342/222075898-cad2518c-0d6b-4a6f-ac81-3336d73f7da5.png)

### Your scenes
describe your use scenes (why need this feature)

### Your advice
describe the advice or solution you'd like
这个问题也许是jvm的bug，但是应用有办法屏蔽这个问题吗？

### Environment

- SOFARPC version: 5.7.10
- JVM version (e.g. `java -version`):
```
➜  ~ java -version
java version "1.8.0_201"
Java(TM) SE Runtime Environment (build 1.8.0_201-b09)
Java HotSpot(TM) 64-Bit Server VM (build 25.201-b09, mixed mode)
```
- OS version (e.g. `uname -a`):
```
➜  ~ uname -a
Linux manjaro-xps 6.0.19-4-MANJARO #1 SMP PREEMPT_DYNAMIC Mon Feb 6 11:26:13 UTC 2023 x86_64 GNU/Linux
```
- Maven version:`3.8.1`
- IDE version:`2022.1.3 (Community Edition)`

**Comment by OrezzerO** [comment]
AdaptivePort 的逻辑在com.alipay.sofa.rpc.server.ServerFactory#resolveServerConfig , 可以看下这块代码. 和你理解的应该不太一样.

**Comment by ZhengweiHou** [comment]
![图片](https://github.com/sofastack/sofa-rpc/assets/14498342/8e62ff40-6f00-4acd-9252-f0eaa28fb57d)
@OrezzerO 
原图的示例就是com.alipay.sofa.rpc.server.ServerFactory#resolveServerConfig 中调用的 NetUtils获取可用端口的逻辑。测试时发生NetUtils通过ServerSocket.bind验证通过的端口却和实际sofa服务启动时生效的端口不一致，简化情景如原始截图发生的情景
