### ISSUE TITLE
SOFAStack 五周年活动- SOFARPC 优秀贡献者公示

### ISSUE THREAD

**Issue by EvenLjj** [sofastack/sofa-rpc#1318]
# 活动概况
* 主题：SOFAStack 社区开源五周年：Live Long and Prosper
* 关键词：有趣、健康、开放
* 时间：04 月 15 日 12:00
* 地点：北京市朝阳区恒通国际创新园 C6 栋 C work
* 合作伙伴
    * 主办方：SOFAStack 社区
    * 合作伙伴：掘金、思否、开源中国、开源社、InfoQ、活动行、示说网
 
欢迎感兴趣的同学到现场参与活动。

# 获奖名单
SOFARPC 2022 年新增了 13 位 contributor，同时也有一些老朋友一起参与了共建，首先在这里感谢所有参与 SOFARPC 的贡献者们。SOFAStack 五周年活动之际，为积极参与 SOFARPC 项目的外部贡献者设立了三个奖项，人数为 1:1:1。参考去年、往年的贡献度以及SOFAStack 其他组件的贡献度，经过内部的沟通确认，最终获奖名单如下。

## 2022 社区优秀 Contributor 奖
获奖人：@MingJunDuan
获奖理由：2022 年 @MingJunDuan 积极参与 issue 的讨论，协助解答社区同学的疑问， 也是 2022 年新增的 13 位 contributor 之一。同时在自己博客中，分享了 SOFARPC 源码解读系列文章，感谢 @MingJunDuan 去年的贡献。

## 2022 社区优秀 Committer 奖
获奖人：@OrezzerO 
获奖理由：2022 年 @OrezzerO 作为 SOFARPC 的 Committer 和 Maintainer，贡献了很多 PR 和解决问题的 idea，并且优化了单测以及版本发布的流程。同时活跃在 SOFARPC 开源社区，认真对 PR 进行 review，并提出比较中肯的建议，感谢 @OrezzerO 去年的贡献。

## 五周年特别奖-常青树奖
获奖人：@leizhiyuan
获奖理由：SOFAStack 五周年之际，为了感谢长久以来一直对 SOFAStack 社区贡献的朋友们，特别设立这个奖项。综合对 SOFARPC 的贡献度，@leizhiyuan 作为 SOFARPC 奠基人之一，同时近些年来也一直活跃在开源社区，协助解决了很多的问题，感谢 @leizhiyuan 一直以来的贡献。

# 写在最后
恭喜上述获奖同学，没有获奖的同学也同样优秀。另外，如果有五周年活动参与的相关问题或建议，欢迎大家在下方留言讨论。

**Comment by Kelei0215** [comment]
🥳
