### ISSUE TITLE
spring boot 3.1 + jdk 17 sofa rpc显示发布成功但是客户端获取不到服务

### ISSUE THREAD

**Issue by Misakami** [sofastack/sofa-rpc#1320]
### Your question

项目使用spring boot 3.1 + jdk 17  [sofa-rpc](com.alipay.sofa:sofa-rpc-all:5.5.0)  JVM启动参数加上了 --add-opens java.base/java.lang=ALL-UNNAMED

服务发布成功。但是客户端调用时会提示RPC-02306: Cannot get the service address of service

### Your scenes

describe your use scenes (why need this feature)

### Your advice

sofa rpc什么版本支持java 17

### Environment

- SOFARPC version: sofa-rpc-all:5.5.0
- JVM version (e.g. `java -version`):  java 17
- OS version (e.g. `uname -a`):windows
- Maven version:
- IDE version:

**Comment by OrezzerO** [comment]
看上去获取不到服务和 JDK17  并没有直接的联系. 可以先确认: 
1. 服务端是否将自身地址发布到注册中心
2. 客户端是否接收到注册中心的推送
