### ISSUE TITLE
sofa升级的一个小问题咨询

### ISSUE THREAD

**Issue by LSQGUANLIVV** [sofastack/sofa-rpc#1322]
从sofa2.3.5升级到3.6.3的时候，启动应用报错，如下图所示
![图片](https://user-images.githubusercontent.com/129157140/228171036-1116fa8b-f086-4aa0-80d3-1778d56b4042.png)
![图片](https://user-images.githubusercontent.com/129157140/228171717-d67d0034-6041-4c84-87fc-1acb398e31bc.png)

![图片](https://user-images.githubusercontent.com/129157140/228171188-30707647-47d5-4174-a1ea-ebc78e7a0763.png)
按照报错的点去找发现是applicationContext为null，这里是需要新增加什么配置吗？还是原来的什么地方需要改呢？麻烦解答一下，谢谢

**Comment by OrezzerO** [comment]
有可能是 sofa-boot / sofa-rpc-starter / sofa-rpc 这三个包的兼容性问题. 升级了 sofa-rpc, 需要同时升级这三个包. 可以通过 pom 依赖看下是否有版本冲突.

**Comment by OrezzerO** [comment]
使用默认的一般不会有问题, 担心有些配置把默认配置覆盖了. 另外商业版需要咨询商业版客服, 开源社区这边能提供的帮助有限.
