### ISSUE TITLE
ExtensionLoader override logic optimization

### ISSUE THREAD

**Issue by EvenLjj** [sofastack/sofa-rpc#1363]
## Background
If one overrides ExtensionClass without adding an override label, it may result in the failure to load other ExtensionClasses of the same type. For instance, if you override the implementation of hessian2 without including an override tag, it will cause serializers like protobuf and json to not load.

**Comment by SanikaAi** [comment]
Please assign this issue to me. Can you help me a little , in which project is the issue? Actually this is my first time contributing.
