### ISSUE TITLE
请问为什么 sofaboot-dependencies 的sofa-rpc-all一直固定在 5.8.3

### ISSUE THREAD

**Issue by Jiiiiiin** [sofastack/sofa-rpc#1368]
### Your question

1. 请问为什么 sofaboot-dependencies 的sofa-rpc-all一直固定在 5.8.3，目前我们使用的sofastack对应版本为：

```xml
  <parent>
    <groupId>com.alipay.sofa</groupId>
    <artifactId>sofaboot-dependencies</artifactId>
    <version>3.20.0</version>
    <relativePath/>
  </parent>

<properties>
    <sofa.boot.version>3.20.0</sofa.boot.version>
    <spring-boot.version>2.7.14</spring-boot.version>
```
但是我们发现sofaboot-dependencies 的sofa-rpc-all一直固定在 5.8.3

2.针对 rpc-sofa-boot-starter 和 sofa-rpc-all的关系是？我们看到 rpc-sofa-boot-starter在sofaboot-dependencies中一直和sofa-boot保持一致，比如上面的3.20.0，他们3者之间的映射关系也没有一个地方能查询到？

为什么我们会关系这个问题，在于，sofa-registry 开源版本或者说核心版本并没有一个简单的dashboard，类似 nacos，所以我们注册中心使用的是nacos，而nacos 服务端目前升级到2.2.3 （或者说我们想把注册中心，或者跟着社区将上游依赖进行同步），但是sofa默认文档中并没有针对 nacos-client 和 sofa-rpc相关组件的版本映射列表（已有的列表长期停滞在1.x）

### Your advice

我们建议针对nacos和sofa-rpc的结合进行响应的定期文档更新

### Environment

- SOFARPC version: sofa.boot.version 来自于sofaboot-dependencies
- JVM version (e.g. `java -version`):1.8
- OS version (e.g. `uname -a`):centos 7.9
- Maven version: Apache Maven 3.9.4

谢谢回复

**Comment by EvenLjj** [comment]
@Jiiiiiin SOFABoot 中 SOFARPC 版本升级应该是遗漏了，没有跟进 SOFABoot 的迭代，目前可以直接升级下最新版本，这个我去提下。当前 sofarpc 最新版本 nacas 版本已经是 2.x 系列了，会定期去更新社区的最新稳定版本，有兴趣的话也可以提交 PR 过来升级版本。

**Comment by Jiiiiiin** [comment]
@EvenLjj 好的老师，等把手上项目交付，计划是要参与sofa项目，先从阅读相关代码开始吧。您的回复针对这种“多模块、团队”项目如何进行聚合依赖管理的思路，谢谢。

![image](https://github.com/sofastack/sofa-rpc/assets/8840636/7e73d5f3-f1d7-4d09-b401-18dc1482c461)

上面这个是测试升级到最新的 sofa-rpc-all 测试的结果是通过（通过排除rpc-sofa-boot-starter中的sofa-rpc-all依赖，手动指定依赖）；

但是另外因为我们nacos-server升级到2.2.3，想着配套的 nacos-client 也升级到对应版本，但是实测是不行，会爆出如下错误，当然近期sofa-boot 4.x（包括生态升级列表中，我看到nacos-client标注的也仅仅是2.0.3 https://zhuanlan.zhihu.com/p/647221821）难道2.2.x这个版本其中存在什么特殊差异吗？老师

```bash
***************************
APPLICATION FAILED TO START
***************************

Description:

An attempt was made to call a method that does not exist. The attempt was made from the following location:

    com.alibaba.nacos.spring.context.properties.config.NacosConfigurationPropertiesBinder.bind(NacosConfigurationPropertiesBinder.java:106)

The following method did not exist:

    com.alibaba.nacos.api.config.annotation.NacosConfigurationProperties.yaml()Z

The calling method's class, com.alibaba.nacos.spring.context.properties.config.NacosConfigurationPropertiesBinder, was loaded from the following location:

    jar:file:/Users/zhaojun/.m2/repository/com/alibaba/nacos/nacos-spring-context/1.1.1/nacos-spring-context-1.1.1.jar!/com/alibaba/nacos/spring/context/properties/config/NacosConfigurationPropertiesBinder.class

The called method's class, com.alibaba.nacos.api.config.annotation.NacosConfigurationProperties, is available from the following locations:

    jar:file:/Users/zhaojun/.m2/repository/com/alibaba/nacos/nacos-client/2.2.3/nacos-client-2.2.3.jar!/com/alibaba/nacos/api/config/annotation/NacosConfigurationProperties.class

The called method's class hierarchy was loaded from the following locations:

    com.alibaba.nacos.api.config.annotation.NacosConfigurationProperties: file:/Users/zhaojun/.m2/repository/com/alibaba/nacos/nacos-client/2.2.3/nacos-client-2.2.3.jar


Action:

Correct the classpath of your application so that it contains compatible versions of the classes com.alibaba.nacos.spring.context.properties.config.NacosConfigurationPropertiesBinder and com.alibaba.nacos.api.config.annotation.NacosConfigurationProperties
```

当然貌似是因为nacos-config导致无法启动。 老师也没有什么思路？目前nacos-config相关starter为最新，当然不调整nacos-client是没有问题的，这个好像和sofa无关，我要去隔壁反馈是吧 哈哈。
