### ISSUE TITLE
项目启动提示：WARN  |  | io.fury.config.FuryBuilder | Class registration isn't forced, unknown classes can be deserialized. If the environment isn't secure, please enable class registration by `FuryBuilder#requireClassRegistration(true)` or configure ClassChecker by `ClassResolver#setClassChecker`

### ISSUE THREAD

**Issue by LiJinYu2024** [sofastack/sofa-rpc#1408]
### Your question

项目启动提示：WARN  |  | io.fury.config.FuryBuilder | Class registration isn't forced, unknown classes can be deserialized. If the environment isn't secure, please enable class registration by `FuryBuilder#requireClassRegistration(true)` or configure ClassChecker by `ClassResolver#setClassChecker`

### Your scenes

更新sofarpc版本后出现的这个提示

### Your advice

windows11开发环境 

### Environment

- SOFARPC version: [5.12.0](https://mvnrepository.com/artifact/com.alipay.sofa/sofa-rpc-all/5.12.0)
- JVM version (e.g. `java -version`): JDK21
- OS version (e.g. `uname -a`): 
- Maven version: 3.9.6
- IDE version: IntelliJ IDEA 2023.2.4 (Community Edition)

**Comment by pandalee99** [comment]
新版的sofa有了新的序列化器，fury，这个是它的配置。意思是在你使用fury的时候，建议去配置黑白名单的功能，防止不安全的类被序列化/反序列化

**Comment by OrezzerO** [comment]
From a compatibility perspective:

Whether the new version of SofaRpc defaults to using the Fury serializer. If it does, this should be prominently highlighted in the release notes (and I believe it shouldn't be the default without a change in major version).

If SofaRpc does not default to using the Fury serializer, then this warning should not be reported.
