### ISSUE TITLE
rpc 调用超时没有丢弃reponse

### ISSUE THREAD

**Issue by zonghaishang** [sofastack/sofa-rpc#1410]
### Describe the bug

https://github.com/sofastack/sofa-rpc/blob/bd25a4e894fc7a1fde00ba15699ea3ee12aa8c16/remoting/remoting-bolt/src/main/java/com/alipay/sofa/rpc/server/bolt/BoltServerProcessor.java#L180

```
    @Override
    public void handleRequest(BizContext bizCtx, AsyncContext asyncCtx, SofaRequest request) {
                   // ... before code
                    response = doInvoke(serviceName, invoker, request);
                    if (bizCtx.isRequestTimeout()) { // 加上丢弃超时的响应的逻辑
                        throwable = clientTimeoutWhenSendResponse(appName, serviceName, bizCtx.getRemoteAddress());
                        break invoke;
                    }

            //  !!!! Bad， 超时的情况下， response 不为空也会导致发送给client，
            //  没有达到丢弃的效果...
            if (response != null) {
            
                try {
                        asyncCtx.sendResponse(response);
                    } finally {
                        if (EventBus.isEnable(ServerSendEvent.class)) {
                            EventBus.post(new ServerSendEvent(request, response, throwable));
                        }
                    }
            }

```

### Expected behavior

```
throwable = clientTimeoutWhenSendResponse(appName, serviceName, bizCtx.getRemoteAddress());
// append response

// todo setup  reponse to null ? or  err message ?
response = MessageBuilder.buildSofaErrorResponse(throwable.getMessage());

```

### Environment

- SOFARPC version:
- JVM version (e.g. `java -version`):
- OS version (e.g. `uname -a`):
- Maven version:
- IDE version:

**Comment by nailcui** [comment]
Thank you, I agree with you. setting the response to null will discard it, @nailcui will solve it@

**Comment by OrezzerO** [comment]
Agree! How about submit a pr to fix it @zonghaishang

**Comment by seeflood** [comment]
这个有人修么，没人修的话我来？正好最近没事干

**Comment by EvenLjj** [comment]
在多笔请求合并时，bolt 层会共用同一个`RemotingContext`，到rpc侧处理不同的请求时，根据`bizCtx.isRequestTimeout()` 这种判断方式去判定超时不一定准确。如果某个接口设置比较小的超时时间，和其他请求合并处理时，会造成预期之外的超时问题。
@seeflood 修这个问题的时候，一并看下怎么处理这块吧。
![image](https://github.com/sofastack/sofa-rpc/assets/15122299/aaeced81-1d74-4b52-8749-0085fa22a715)

**Comment by chuailiwu** [comment]
在多笔请求合并时和这个超时检查应该是冲突的
可以做一个修复逻辑，即如果是多笔请求合并，让超时检查失效
![image](https://github.com/sofastack/sofa-rpc/assets/2288906/fe330c43-0c58-4611-b7e0-a2c1fb31c1fc)

**Comment by EvenLjj** [comment]
@seeflood 这个并发问题在 bolt 1.6.8 版本修复了，https://github.com/sofastack/sofa-bolt/pull/347。
