### ISSUE TITLE
泛化调用如何指定服务实例

### ISSUE THREAD

**Issue by jin840919** [sofastack/sofa-rpc#1423]
项目不同的环境是以不同实例在注册中心sofaregistry区分的，例如

"github.clyoudu.sofa.api.CalculatorService:1.0@DEFAULT#@#DEFAULTINSTANCEID#@#SOFA"

"github.clyoudu.sofa.api.CalculatorService:1.0@DEFAULT#@#GHFVJuGvHhH#@#SOFA"

这两个服务名相同，只是实例不同，怎么在进行泛化调用时指定实例，因为不同实例对应不同环境，代码可能不一样

**Comment by OrezzerO** [comment]
没有很理解 "不同的环境是以不同实例注册" ,那么就是 "相同的环境是以相同的实例注册的", 我理解的对么? 在这种语境下, "实例" 是什么含义呢?
