### ISSUE TITLE
用户手动构造SofaResponse时并且errorMsg为空字符串场景会导致异常

### ISSUE THREAD

**Issue by wangchengming666** [sofastack/sofa-rpc#1425]
在使用sofa-hessian-go这个库时，使用hessian序列化的场景下，用户手动构造`com.alipay.sofa.rpc.core.response.SofaResponse`会导致异常。

SofaRPCResponse的结构体如下
```
type SofaRPCResponse struct {
	IsError       bool              `hessian:"isError"`
	ErrorMsg      string            `hessian:"errorMsg"`
	AppResponse   interface{}       `hessian:"appResponse"`
	ResponseProps map[string]string `hessian:"responseProps"`
}

func (s *SofaRPCResponse) GetJavaClassName() string {
	return "com.alipay.sofa.rpc.core.response.SofaResponse"
}
```

可以看到errorMsg为string类型，在go里string会被初始化为空字符串。此时用户想自定义`appResponse`这个属性为一个`xxxRuntimeException`，并没有设置`errorMsg`这个属性。

那么在`com.alipay.sofa.rpc.core.response.SofaResponse#setErrorMsg`里，仅仅判断了`errorMsg为null`的场景并`没有判断为空字符串`的场景，那么就会将`isError设置为true`，导致异常类型为`SofaRpcException`而不是用户手动设置的`xxxRuntimeException`。

解决方案：
可以在`com.alipay.sofa.rpc.core.response.SofaResponse#setErrorMsg`里使用StringUtils.isEmpty进行判断

**Comment by OrezzerO** [comment]
Tracing this topic In [sofa-hessian-go](https://github.com/sofastack/sofa-hessian-go) . Close this issue in java side.
