### ISSUE TITLE
Thrift原生协议支持可行性如何？

### ISSUE THREAD

**Issue by eonezhang** [sofastack/sofa-rpc#159]
### Question

如果想要扩展支持原生thrift协议，请问框架目前对这块的支持灵活吗，实现难度有多大？
最好能同时支持同步接口和异步接口
### Scenes
想通过HTTP1.1/HTTP2协议来传输thrift的序列化数据后进行rpc调用。
目前系统大部分接口使用thrift协议进行了通信。
如果此方案可行，将大大降低系统迁移所带来的成本和风险。

**Comment by ujjboy** [comment]
你是想只用 `thrift` 的序列化部分，而不用他的 `transport` 部分是吗？

**Comment by eonezhang** [comment]
`netty`创始人搞了一个rpc框架叫[Armeria](http://github.com/line/armeria)，内置了对`thrift`的原生支持。基于`HTTP2`来传输，可以提供4个序列化方式。
不知道`sofa`能否提供类似的支持，这样除了rpc以外，还可以利用sofa提供了其它能力,LB, SD，Tracer等，完美解决跨语言问题。

**Comment by ujjboy** [comment]
SOFARPC 作为已经内置了负载均衡、服务发现、链路跟踪的能力，我们也基于 netty 支持了 HTTP/2协议 + Protobuf 序列化的实现。thrift 作为一套完整的实现，有自己的transport层和序列化层。

你的需求应该只是说在SOFARPC多一个 thrift 序列化的能力，从而实现 HTTP/2 + thrift？

**Comment by eonezhang** [comment]
@ujjboy 我想实现通过IDL生成的java接口实现后挂到sofa，可以让通过IDL生成的其他语言客户端调用即可，如Python, Golang, Java, C等。

**Comment by ujjboy** [comment]
thrift 生成的 java 接口比较特殊  一般是 `XXX.Iface` 内部类，这个我们暂时没测试过有啥影响。

另外一个是 IDL 生成的对象，可以写入到 TMemoryTransport 内存里，拿到 byte[] 数据后，就可以 thrift 协议或者 HTTP/2 协议都可以发送了。

**Comment by billowqiu** [comment]
多语言互相通信？

**Comment by eonezhang** [comment]
是的，thrift本身就支持多语言，就跟grpc一样。
只是在想是否能让thrift服务跑在sofa上，其他语言根据idl就可以生成client来访问。
如果sofa能提供http的传输，通过nginx的反向代理可以让手机等移动设备访问thrift服务并享受到负载均衡的能力。

**Comment by leizhiyuan** [comment]
@eonezhang 代码中有对 pb 的支持代码,可以先看下,有疑问可以在这里讨论.

**Comment by leizhiyuan** [comment]
这个我先测试看下.

**Comment by leizhiyuan** [comment]
![image](https://user-images.githubusercontent.com/2684384/48176656-17232900-e34c-11e8-87ad-8c5453a8e69b.png)

@ujjboy  测试了一个简单的场景,直接当成普通的接口,是可以用的

如果要用 thrift 跨语言,那就要类似 protobuf 实现一个序列化,但是如果想在 rpc 里面用 thrift. 但是其他语言不用理解 bolt 协议,进行发送,感觉不是很合适,这样的话,那核心处理代码都是 thrift 的.服务端能做的太少
这个需求可以后面再看看.

**Comment by leizhiyuan** [comment]
这个跟 grpc 的支持一起看下 @NeGnail

**Comment by juaby** [comment]
我fork了，拉分支了，在集成thrift.....

**Comment by leizhiyuan** [comment]
grpc 最近将支持上，thrift暂时不考虑了。如果用需要的同学，欢迎pr
