### ISSUE TITLE
grpc support

### ISSUE THREAD

**Issue by Moriadry** [sofastack/sofa-rpc#304]
### Your question

Hi all,  我正在开发 支持grpc协议的feature，有些问题想请教下。参照weibo/motan的grpc实现，他们是面向stub/channel layer来适配grpc，把接口用grpc的client包装了一层。我们知道grpc layer有stub, channel, transport三层。通过类似motan的这种做法， 我们能完成与grpc组件的对接。 

还是要包含grpc一些lb, health check, streaming调用等适配的话，需要通过更high level的方案来做。欢迎讨论 :) 目前看，通过(io.grpc.netty.NettyChannelBuilder, io.grpc.stub.ClientCalls, io.grpc.netty.NettyServerBuilder, and io.grpc.stub.ServerCalls) 的方式比较简单，逻辑上的调用流程也是走grpc内部 包括load balancing, cluster/registry management。这样在我理解看来，sofa在其中担任的只是请求转发者的角色而已。这是我们目前想要的吗？

**Comment by liangyuanpeng** [comment]
how about  registry  of consul now ?

**Comment by Moriadry** [comment]
I will create a pr to fix that.

**Comment by leizhiyuan** [comment]
refer：https://github.com/alipay/sofa-rpc/issues/57

**Comment by leizhiyuan** [comment]
@NeGnail G

**Comment by NeGnail** [comment]
@Moriadry   你这边进展怎么样，如果有已经做了的部分可以提个分支吗，我们一起看下。

**Comment by Moriadry** [comment]
@NeGnail 嗨，我最近在准备在职研究生的考试，稍微有点忙。今天或明天把之前开发的分支给到你这边，帮忙一起看下~ 感谢:)

**Comment by NeGnail** [comment]
@Moriadry   ok。

**Comment by leizhiyuan** [comment]
see https://github.com/alipay/sofa-rpc/pull/383 待 review

**Comment by netroby** [comment]
https://github.com/sofastack/sofa-rpc/pull/716 already merged, can this issue be closed?
