### ISSUE TITLE
webflux等异步框架如何使用sofa-rpc异步调用

### ISSUE THREAD

**Issue by yh3434** [sofastack/sofa-rpc#318]
### Your question
你好，
目前回调方法只能做通知使用，我想用webflux这样的异步框架调用sofa-rpc服务，然后在回调里使用结果是不是做不到，要用的话也只能每次新建一个Consumer<Config>

### Your advice

future模式什么时候可以支持add listener?

### Environment

- SOFARPC version:
- JVM version (e.g. `java -version`):
- OS version (e.g. `uname -a`):
- Maven version:
- IDE version:

**Comment by khotyn** [comment]
@yh3434 你是想用 `CompletableFuture` 的那种 `thenApply` 之类的方法？

**Comment by yh3434** [comment]
@khotyn 你好，是想用CompletableFuture  这类的，现在是可以通过callback，然后再包装一层CompletableFuture。但是每次调用后得两行代码。

**Comment by leizhiyuan** [comment]
@yh3434 你们这边包装的示例代码可否提供下?我们看下是否可以提供一个内置的包装.

**Comment by yh3434** [comment]
@leizhiyuan 
final CompletableFuture<UserDTO> completableFuture = Reference.callBack();
//调用
 loginService.findUserByName(username);

Reference类链接：https://github.com/winkflow/sofarpc-spring-boot-starter/blob/master/src/main/java/io/wink/tool/reference/Reference.java

**Comment by leizhiyuan** [comment]
@yh3434 好的,我看下.谢谢
