### ISSUE TITLE
使用zk时，curator-recipes版本只支持2.9.1吗？改为4.0.1时service注册不上去。

### ISSUE THREAD

**Issue by yh3434** [sofastack/sofa-rpc#331]
### Your question
使用zk时，curator-recipes版本只支持2.9.1吗？改为4.0.1时service注册不上去，和spring cloud zookeeper结合使用时，spring cloud 要求curator-recipes为4.0.1。

### Environment

- SOFARPC version:
- JVM version (e.g. `java -version`):
- OS version (e.g. `uname -a`):
- Maven version:
- IDE version:

**Comment by leizhiyuan** [comment]
代码里是引入了这个2.9.1的版本，你可以尝试进行排除这个依赖，然后引入4.0.1的版本验证下。

https://curator.apache.org/zk-compatibility.html 另外，4.0.x 强依赖 zk 3.5.x。可以都尝试排除掉，引入 zk 这个版本来验证下。 如果指定版本有什么问题，可以issue 提供下。

**Comment by yh3434** [comment]
@leizhiyuan 你好，引入4.0.1时会报下面的错，应该是不支持高版本的：
018-10-14 17:27:42,147 WARN  main                             - Catch exception when subscribe from registry: rpc-cfg-4, but you can ignore if it's called by JVM shutdown hook
java.lang.NoSuchMethodError: org.apache.curator.framework.api.CreateBuilder.creatingParentContainersIfNeeded()Lorg/apache/curator/framework/api/ProtectACLCreateModePathAndBytesable;
	at com.alipay.sofa.rpc.registry.zk.ZookeeperRegistry.subscribe(ZookeeperRegistry.java:471)
	at com.alipay.sofa.rpc.bootstrap.DefaultConsumerBootstrap.subscribeFromRegistries(DefaultConsumerBootstrap.java:337)
	at com.alipay.sofa.rpc.bootstrap.DefaultConsumerBootstrap.subscribe(DefaultConsumerBootstrap.java:260)
	at com.alipay.sofa.rpc.client.AbstractCluster.init(AbstractCluster.java:144)
	at com.alipay.sofa.rpc.bootstrap.DefaultConsumerBootstrap.refer(DefaultConsumerBootstrap.java:151)
	at com.alipay.sofa.rpc.config.ConsumerConfig.refer(ConsumerConfig.java:926)

**Comment by leizhiyuan** [comment]
看错误提示：

org.apache.curator.framework.api.CreateBuilder

我看了一下

```
4.0.1 接口 上述接口扩展了下面这个接口
org.apache.curator.framework.api.CreateBuilderMain#creatingParentContainersIfNeeded
返回值ProtectACLCreateModeStatPathAndBytesable
2.9.1 接口 直接CreateBuilder自己实现
返回值ProtectACLCreateModePathAndBytesable
```

注意：两个方法一样，但是返回值不一样。

所以应该可以确定是rpc 编译用了2.9.1，但是运行起来之后，是4.0.1，导致这个报错。这是curator-recipes 自身api不兼容带来的。

要解决，需要使用4.0.1的 api 对 rpc 进行编译，这个如果用了4.0.1，那么以前的用户在2.9.1上就无法使用。这个我们考虑一下，可能只能在之后的大版本中进行升级，作为不兼容的变更。

**Comment by yh3434** [comment]
是的，我暂时用4.0.1本地打包就可以了。

**Comment by leizhiyuan** [comment]
在5.5.0 的大版本中会对一下基础组件升级到稳定的新版本。比如 zk

**Comment by OrezzerO** [comment]
@leizhiyuan  如果我现在上生产的的话,建议使用什么版本的 ZK ?

**Comment by leizhiyuan** [comment]
@OrezzerO 客户端的没有限制，rpc 自带的也是稳定版。目前是2.9.1  
这个 issue 里只是为了给用户在 spring cloud 环境下使用的。

**Comment by fallsea** [comment]
@leizhiyuan 最新版本没有升级吗

**Comment by pengjieran** [comment]
When will it be repaired?
