### ISSUE TITLE
add assertions to ConsulRegistryTest

### ISSUE THREAD

**Issue by ScienJus** [sofastack/sofa-rpc#414]
### Your scenes

`ConsulRegistryTest` 需要一些断言确保能正确运行。

### Your advice

每一个 `CountDownLatch#await` 都应该判断返回值为 `true` 确保 `MockProviderInfoListener` 收到了更新事件。

### Environment

- SOFARPC version: the master branch

**Comment by leizhiyuan** [comment]
fix in https://github.com/sofastack/sofa-rpc/pull/629
