### ISSUE TITLE
can we provider a custom xml tag for rest filter?

### ISSUE THREAD

**Issue by leizhiyuan** [sofastack/sofa-rpc#440]
### Your question

maybe we can  allow user 

```
<sofa:rest-filter id ="xx",class = "xxxx" />
```

### Your scenes

describe your use scenes (why need this feature)

### Your advice

describe the advice or solution you'd like

### Environment

- SOFARPC version:
- JVM version (e.g. `java -version`):
- OS version (e.g. `uname -a`):
- Maven version:
- IDE version:

**Comment by SteNicholas** [comment]
@leizhiyuan Yes,I could complete this feature that provider custom xml tag for rest filter in this week.

**Comment by leizhiyuan** [comment]
https://github.com/sofastack/sofa-boot/pull/600
