### ISSUE TITLE
Provider端通过sdk主动触发服务降级或者影响负载均衡策略

### ISSUE THREAD

**Issue by VincentSleepless** [sofastack/sofa-rpc#448]
### Your question

Sofa-Provider 目前有没有接口可以实现根据调用次数（或者provider本地统计维度）达到某个阀值来影响负载均衡策略，或者provider服务的权重降级。

比如每一个执行节点，开启sofa-rpc provider ，但是执行节点可以执行的作业数量是有上限的（比如一个odps-sql或者一个datax作业会占用一定的内存），超过阈值后，rpc将不再向这个provider进行作业推送请求。

### Your scenes

describe your use scenes (why need this feature)

### Your advice

describe the advice or solution you'd like

### Environment

- SOFARPC version:5.4.8
- JVM version (e.g. `java -version`):
- OS version (e.g. `uname -a`):
- Maven version:
- IDE version:

**Comment by JervyShi** [comment]
负载均衡可以从两方面去考虑：
1. 客户端负载均衡：SOFA RPC 提供负载均衡算法的自定义扩展能力，https://github.com/alipay/sofa-rpc/tree/master/core-impl/client/src/main/java/com/alipay/sofa/rpc/client/lb
2. 服务端影响负责均衡：每个 Provider 在向服务注册中心注册时都会带上自己的权重，理论上是可以在 Provider 处根据请求频率修改自己的权重，然后重新向服务注册中心发布自己的元信息来影响客户端负载均衡的。

**Comment by VincentSleepless** [comment]
> 负载均衡可以从两方面去考虑：
> 
> 1. 客户端负载均衡：SOFA RPC 提供负载均衡算法的自定义扩展能力，https://github.com/alipay/sofa-rpc/tree/master/core-impl/client/src/main/java/com/alipay/sofa/rpc/client/lb
> 2. 服务端影响负责均衡：每个 Provider 在向服务注册中心注册时都会带上自己的权重，理论上是可以在 Provider 处根据请求频率修改自己的权重，然后重新向服务注册中心发布自己的元信息来影响客户端负载均衡的。
目前是纯java开发的，刚开始看，可能有些地方还有看到，但是ProviderConfig里貌似只有export和unexport方法来做服务上下线，或者可以设置启动静态权重，没有看到动态频率的修改，或者说这部分目前要自己修改源码的方式去实现。
