### ISSUE TITLE
Intergrate with Apollo to support dynamic  config 

### ISSUE THREAD

**Issue by leizhiyuan** [sofastack/sofa-rpc#452]
### Your question

https://github.com/alipay/sofa-rpc/pull/456

### Your scenes

describe your use scenes (why need this feature)

### Your advice

so we can support custom auth, shut down gracefully, or thread pool size adjust.

### Environment

- SOFARPC version:
- JVM version (e.g. `java -version`):
- OS version (e.g. `uname -a`):
- Maven version:
- IDE version:

**Comment by leizhiyuan** [comment]
这个@SteNicholas  应该会认领，等他认领后跟他确定时间。

**Comment by OrezzerO** [comment]
感觉直接用 apollo 的话耦合有点严重, 是不是中间加层 archaius 解耦?

**Comment by leizhiyuan** [comment]
> 感觉直接用 apollo 的话耦合有点严重, 是不是中间加层 archaius 解耦?

嗯，是这样的。这个feature比较大，需要先详细设计一下框架。

**Comment by SteNicholas** [comment]
@leizhiyuan @khotyn I claim this feature.By the way,I will complete this feature in one and a half weeks.

**Comment by SteNicholas** [comment]
@leizhiyuan Has apollo design plan been ready?

**Comment by SteNicholas** [comment]
@leizhiyuan Has apollo design plan already been ready?

**Comment by JervyShi** [comment]
Link to https://github.com/alipay/sofa-rpc/issues/549

**Comment by leizhiyuan** [comment]
已经支持。
