### ISSUE TITLE
rpc-config.json 中的配置是否可以通过 application.property 中的配置覆盖

### ISSUE THREAD

**Issue by OrezzerO** [sofastack/sofa-rpc#472]
### Your question

rpc-config.json 中的配置是否可以通过 application.property 中的配置覆盖?
### Your scenes

describe your use scenes (why need this feature)

### Your advice

describe the advice or solution you'd like

### Environment

- SOFARPC version:
- JVM version (e.g. `java -version`):
- OS version (e.g. `uname -a`):
- Maven version:
- IDE version:

**Comment by leizhiyuan** [comment]
目前不可以，这个是一份非常完全的配置，对Spring的结合，我们通过Starter转换来改变某些值，但不是全部。
