### ISSUE TITLE
rest支持skywalking

### ISSUE THREAD

**Issue by leizhiyuan** [sofastack/sofa-rpc#476]
### Your question

现在bolt是支持的，看下rest的支持。
### Your scenes

describe your use scenes (why need this feature)

### Your advice

describe the advice or solution you'd like

### Environment

- SOFARPC version:
- JVM version (e.g. `java -version`):
- OS version (e.g. `uname -a`):
- Maven version:
- IDE version:

**Comment by khotyn** [comment]
@leizhiyuan 这个在哪里修复了？

**Comment by leizhiyuan** [comment]
关错issue了。。要关的是这个 https://github.com/alipay/sofa-rpc/issues/474

**Comment by leizhiyuan** [comment]
应该是已经支持了。
