### ISSUE TITLE
bolt support swagger to generate api doc or test api

### ISSUE THREAD

**Issue by leizhiyuan** [sofastack/sofa-rpc#482]
### Your question

describe your question clearly

### Your scenes

describe your use scenes (why need this feature)

now api json is ok.
next is api-ui
![image](https://user-images.githubusercontent.com/2684384/58945455-7946ee00-87b6-11e9-9ee2-efb4232e5078.png)

### Your advice

maybe this project will be helpful for us, thanks for the author.
https://github.com/Sayi/swagger-dubbo
### Environment

- SOFARPC version:
- JVM version (e.g. `java -version`):
- OS version (e.g. `uname -a`):
- Maven version:
- IDE version:

**Comment by leizhiyuan** [comment]
好的，我看看。另外 sofa-rpc这个项目目前不依赖Spring
如果要基于spring的一些东西最终实现，可能放到starter那个项目中更好。

这个当时需求的背景主要是生成 doc  api ，test api目前没那么重要，

如果是生成doc api这个你这个项目依赖多吗？

**Comment by zhaojigang** [comment]
奥，springfox 是要基于 spring 搞的，如果要做的话，除了 starter，放到 sofaboot 也合适，但是没试过与springboot2 的兼容性，依赖还好（如下），**个人觉得，如果可以直接基于 swagger 去搞，是最好的**，我当时写的时候因为是为了快糙猛的实现，所以用了目前的这种方式
![image](https://user-images.githubusercontent.com/14085645/51978597-8c267a80-24c5-11e9-8b70-0cec3b847e6b.png)

**Comment by zhaojigang** [comment]
依赖 dubbo 主要是我们现在用的是 dubbo，就直接用了 dubbo 的 jdkCompiler 编译器
