### ISSUE TITLE
add method for AddressHolder  to judge which group the designated provider in?

### ISSUE THREAD

**Issue by leizhiyuan** [sofastack/sofa-rpc#485]
### Your question
now if user want to judge the the designated provider in which group,they need do like this
```
  AddressHolder addressHolder = AddressHolderFactory.getAddressHolder(consumerConfig.getConsumerBootstrap());
        List<ProviderGroup> providersGroups = addressHolder.getProviderGroups();
        for (ProviderGroup providerGroup : providersGroups) {
            List<ProviderInfo> providerInfos = providerGroup.getProviderInfos();
            if (providerInfos == null) {
                continue;
            } else {
                for (ProviderInfo providerInfo : providerInfos) {
                    if (StringUtils.equals(providerInfo.getHost(), ip)) {
                        return providerGroup.getName();
                    }
                }
            }
        }
```

this is  poor performance, maybe we can provider a method like 

    public String judgeGroupFromIp(String ip) {

to make address holder to implement

### Your scenes

describe your use scenes (why need this feature)

### Your advice

describe the advice or solution you'd like

### Environment

- SOFARPC version:
- JVM version (e.g. `java -version`):
- OS version (e.g. `uname -a`):
- Maven version:
- IDE version:

**Comment by leizhiyuan** [comment]
@ujjboy @JervyShi

**Comment by JervyShi** [comment]
Direct return group name is too customized, what about return providerGroup when ip match?

**Comment by leizhiyuan** [comment]
yes, I write it now, 

public ProviderGroup judgeGroupFromProvider(ProviderInfo providerInfo) 

is  more general
