### ISSUE TITLE
是否需要支持Filter的热加载

### ISSUE THREAD

**Issue by zhaojigang** [sofastack/sofa-rpc#510]
### Your question

目前，我们自己加一个filter后，需要重新发布服务，如果可以支持热加载（例如使用groovy编写filter，写一个定时加载引擎或者带通知机制的引擎来实现热加载，类似 zuul），就不需要重新发布服务了。

**Comment by leizhiyuan** [comment]
这里有几个问题需要考虑。

1. 需要持有一个<key,proxyIns>  的全局变量
2.如果通过动态推送的能力，推送了一个filter，需要proxyIns 取出这个里面的proxyInvoker，然后将buildchain进行增加。
3.动态能力可以对接apollo
4.考虑下这个能力是不是做到整个SOFABoot中更好。
