### ISSUE TITLE
业务代码抛出异常之后,框架没有打印异常信息

### ISSUE THREAD

**Issue by OrezzerO** [sofastack/sofa-rpc#513]
### Your question

业务代码抛出异常之后,框架没有打印异常堆栈

#### Rest 协议异常请求流程
1. netty 客户端接收网络请求
2. resteasy 交给具体处理类
3. 处理方法抛出异常
4. MethodInjectorImpl 包装成 ApplicationException
5. dispatcher 处理异常,将异常对应的 response 写入返回流中
6. 如果不能处理这个异常,抛出 UnhandledException
7. SofaRestRequestHandler 兜底处理异常,打印异常堆栈

SofaRestRequestHandler 兜底处理异常,打印异常堆栈

**然而**,SofaRestRequestHandler 中的 logger 是由 `org.jboss.resteasy.logging.Logger`这个特殊的 Logger 构造出来的. 如果不指定日志实现, 这个 Logger 的日志实现是由以下代码指定的: 
```java
static
 {
    LoggerType type = LoggerType.JUL;

    if (classInClasspath("org.apache.log4j.Logger"))
    {
       type = LoggerType.LOG4J;
    }
    else if (classInClasspath("org.slf4j.Logger"))
    {
       type = LoggerType.SLF4J;
    }

    setLoggerType(type);
 }
```
可以看出,Log4j 的优先级是高于 SLF4j 的. 我们很难在依赖中完全去除`org.apache.log4j.Logger`这就导致了我们整体上使用 Logback,`SofaRestRequestHandler`这个类以及 resteasy 相关类中的日志依然使用`log4j`打印.

### 解决方案 
显示指定 resteasy 使用的日志框架:
```java
   Logger.setLoggerType(Logger.LoggerType.SLF4J);
```

### Environment

- SOFARPC version:
- JVM version (e.g. `java -version`):
- OS version (e.g. `uname -a`):
- Maven version:
- IDE version:

**Comment by JervyShi** [comment]
@OrezzerO 这里使用 SOFA RPC 自己内置的 `com.alipay.sofa.rpc.log.Logger` 更合适，内置 Logger 的实现会通过用户环境内依赖的日志实现 jar 来自动选择，这里应该是漏掉了，可以提个 PR Fix 这个问题么？

**Comment by OrezzerO** [comment]
@JervyShi  我觉得这么处理还是不够的, 因为 resteasy 内部是用`org.jboss.resteasy.logging.Logger`,光改掉这个类是不够的.

**Comment by JervyShi** [comment]
@OrezzerO 是说框架主动做 `Logger.setLoggerType(Logger.LoggerType.SLF4J);` 吗？这种方式对用户不太友好，选择权还是应该在用户手中，按照 `org.jboss.resteasy.logging.Logger` 的实现逻辑，只有应用内有 `org.apache.log4j.Logger` 时才会启用，所以可以主动排除掉项目中 log4j 的依赖吧，然后就走到 SLF4J 了。

**Comment by leizhiyuan** [comment]
refer to https://github.com/sofastack/sofa-rpc/issues/513
