### ISSUE TITLE
SOFA-RPC支持Eureka服务注册发现

### ISSUE THREAD

**Issue by liufeiit** [sofastack/sofa-rpc#52]
支持将服务注册到Eureka Server并定时向Eureka续约，支持Eureka服务发现。

**Comment by ujjboy** [comment]
Hi  @liufeiit  可与参考如下文档：
- 参与贡献：https://github.com/alipay/sofa-rpc/wiki/Contributing
- 扩展demo：https://github.com/ujjboy/sofa-rpc-extension-demo
- 也可以参考 `registry-zookeeper` 模块的实现。

**Comment by leizhiyuan** [comment]
由于服务注册发现实现方很多,目前我们还是尽量开源 RPC 中必须的本身的功能,对于可以用户扩展实现的组件适配,有兴趣可以提 pr~

**Comment by leizhiyuan** [comment]
这个功能现在怎么样了? 有遇到什么问题么?  @liufeiit

**Comment by Lmyxny** [comment]
@liufeiit 您那里现在开发的怎么样了，我现在也要实现这个功能，需要您帮助

**Comment by Lmyxny** [comment]
@liufeiit 您那面sofa 基于eureka的注册中心，开发到什么阶段了？可以给予一下消息嘛？

**Comment by leizhiyuan** [comment]
@liufeiit  hi ，如果方便的话可以考虑先提交部分，我们可以协助来开发~

**Comment by wdxxs2z** [comment]
@leizhiyuan , eureka注册中心对RPC的注册方式不太友好，eureka对应的是一个application多个实例，并没有服务service的概念，如果要做有几个办法，一个是一个application的instance注册时，绑定追加metadata，并写入相应服务的数据结构，可以实现，但并不优雅，索取服务时会扫描eureka的所有应用的instance信息，应用较多时，优化空间有限；另一个办法是注册应用的时候，将应用名替换成服务名，实例对应服务的应用，但容易造成理解混淆；
还有我注意到dubbo那边对这个问题，也有相关解释，这个问题应该被搁置了。
https://github.com/apache/incubator-dubbo/issues/1981#

**Comment by leizhiyuan** [comment]
暂时不做了。
