### ISSUE TITLE
sofaboot 啥时候支持自定义 Router

### ISSUE THREAD

**Issue by chenhj520** [sofastack/sofa-rpc#534]
### Your question

describe your question clearly

### Your scenes

describe your use scenes (why need this feature)

### Your advice

describe the advice or solution you'd like

### Environment

- SOFARPC version:
- JVM version (e.g. `java -version`):
- OS version (e.g. `uname -a`):
- Maven version:
- IDE version:

**Comment by leizhiyuan** [comment]
现在你可以通过

https://www.sofastack.tech/sofa-rpc/docs/Custom-Router

这个文档来做

**Comment by leizhiyuan** [comment]
或者说你这边是想一个怎么样的路由方式？如果比较通用，我们可以内置支持。

**Comment by chenhj520** [comment]
最好是通过打一个 @Router 注解的方式注入 Router，在 xml 里配置也行。

**Comment by leizhiyuan** [comment]
好的，这个我们整理看下，将SPI的能力，通过SOFABoot暴露出来。
