### ISSUE TITLE
传输压缩选项未生效

### ISSUE THREAD

**Issue by 9599110** [sofastack/sofa-rpc#582]
### Your question

new ProviderConfig<IBattleService>().setCompress("snappy");
new ConsumerConfig<GenericService>().setCompress("snappy");

用上边的方法设置压缩，启动参数加上 -Dcompress.open=true，但传输过程中并没有压缩数据传输！
麻烦大神指点一下还需要其他的什么设置，才能传输压缩吗？

### Your scenes

因为传输的数据略大，想压缩后传输

### Your advice

describe the advice or solution you'd like

### Environment

- SOFARPC version:   5.5.2
- JVM version (e.g. `java -version`):  1.8
- OS version (e.g. `uname -a`):  server：CentOS release 6.10 (Final)  client：macos 10.12.3 
- Maven version:  Apache Maven 3.5.2
- IDE version:

**Comment by leizhiyuan** [comment]
对 BOLT 协议不生效，目前并没有开启

对 Http 协议目前也没有开启。

**Comment by 9599110** [comment]
谢谢大神！

**Comment by leizhiyuan** [comment]
嗯，hessian 序列化 / pb 序列化已经算比较高效了。snappy 不会很明显，对http的场景倒是后面可以开启试试。那issue我先关闭了。

**Comment by leizhiyuan** [comment]
5.6.0中我们对 http 开发，然后打开好了。

**Comment by 9599110** [comment]
明白了！谢谢耐心解答！

**Comment by khotyn** [comment]
@leizhiyuan We can throw exception to make the startup process failed if a specific protocol does not support snappy?

**Comment by leizhiyuan** [comment]
ok

**Comment by javeme** [comment]
@khotyn @leizhiyuan 请问下，ClassName或DataType可以采取整数编码等方式进行压缩，以减少传输内容吗？谢谢

**Comment by leizhiyuan** [comment]
> @khotyn @leizhiyuan 请问下，ClassName或DataType可以采取整数编码等方式进行压缩，以减少传输内容吗？谢谢

你说的这个其实是可以的。但是修改hessian代码，将元信息id分配和缓存的数据结构，从HessianOutput和HessianInput拆分出来。在连接层面进行共享，这样，就跟写引用一样，都只写入id。性能会有提升。

不过这个需要改hessian的一些代码。可以看下是不是值得。

**Comment by OrezzerO** [comment]
暂时关闭,有需要可以打开.
Close this issue temporarily, open it if necessarily.
