### ISSUE TITLE
sofa-rpc not supports the dubbo 2.0 protocol?

### ISSUE THREAD

**Issue by xiaoyue6** [sofastack/sofa-rpc#587]
DubboProviderBootstrap.copyProvider in line 135, sofa-rpc force sets the dubbo version to 1.0

private void copyProvider(ProviderConfig<T> providerConfig, ServiceConfig<T> serviceConfig) {
        serviceConfig.setId(providerConfig.getId());
        serviceConfig.setInterface(providerConfig.getInterfaceId());
        serviceConfig.setRef(providerConfig.getRef());
        serviceConfig.setGroup(providerConfig.getUniqueId());
        serviceConfig.setVersion("1.0");//here
        serviceConfig.setActives(providerConfig.getConcurrents());
        serviceConfig.setDelay(providerConfig.getDelay());
        serviceConfig.setDynamic(providerConfig.isDynamic());
        serviceConfig.setRegister(providerConfig.isRegister());
        serviceConfig.setProxy(providerConfig.getProxy());
        serviceConfig.setWeight(providerConfig.getWeight());
        if (providerConfig.getTimeout() > 0) {
            serviceConfig.setTimeout(providerConfig.getTimeout());
        }
        serviceConfig.setParameters(providerConfig.getParameters());
    }

**Comment by leizhiyuan** [comment]
yes, if you want to a different version, we should use the uniqueId in  SOFARPC as version
