### ISSUE TITLE
rpc-config-default.json配置包含配置项consumer.connect.elastic.precent拼写错误吧，改成percent ?

### ISSUE THREAD

**Issue by zonghaishang** [sofastack/sofa-rpc#589]
### Your question

describe your question clearly

### Your scenes

describe your use scenes (why need this feature)

### Your advice

describe the advice or solution you'd like

### Environment

- SOFARPC version:
- JVM version (e.g. `java -version`):
- OS version (e.g. `uname -a`):
- Maven version:
- IDE version:

**Comment by JervyShi** [comment]
@zonghaishang Yes, you can create PR for this issue.

**Comment by zonghaishang** [comment]
好的，很乐意处理
