### ISSUE TITLE
服务上线之后立即自动下线

### ISSUE THREAD

**Issue by OrezzerO** [sofastack/sofa-rpc#598]
### Your question
遇到一个奇怪的情况, 有时候一个服务注册到zk 上之后, 过0~2分钟, 它会自动下线. 
1. 之前听说有 health Check 来做健康检查, 如果不健康就会自己下线. 是不是这样?
2. 我翻了一下代码, 找到这个类:  RpcAfterHealthCheckCallback , 里面发了两个事件,就直接返回健康了. RPC 健康检查的项目有哪些呢?

### Your scenes

describe your use scenes (why need this feature)

### Your advice

describe the advice or solution you'd like

### Environment

- SOFARPC version:
- JVM version (e.g. `java -version`):
- OS version (e.g. `uname -a`):
- Maven version:
- IDE version:

**Comment by leizhiyuan** [comment]
1.不会，这个是说和zk的链接如果断了就会取消注册，但是马上还是会重练的
2.健康检查目前主要是检查作为消费者，有没有收到过注册中心的地址推送。如果没有，就是不健康的。
