### ISSUE TITLE
sofarpc使用uniqueId服务调用不通

### ISSUE THREAD

**Issue by OAALin** [sofastack/sofa-rpc#606]
### Describe the bug

sofarpc使用uniqueId 来进行区分，会出现调用不通，服务可以被发现，但是调用出现问题。
注：
在初始阶段调用正常，之后时间一致无法调用通过，中间没有做修改

### Expected behavior

访问对应服务

### Actual behavior
无法访问

### Environment

- SOFARPC version:  2.5.2
- JVM version (e.g. `java -version`): java version "1.8.0_141"

**Comment by leizhiyuan** [comment]
调用不通的的日志提供下？ 在logs/tracelog  logs/bolt logs/rpc 这几个目录下的日志。

**Comment by leizhiyuan** [comment]
用户长时间未提供相关的信息，如果还有问题，可以再打开issue。谢谢
