### ISSUE TITLE
如何在rpc 各个节点之间共享用户登录信息

### ISSUE THREAD

**Issue by cxc3214** [sofastack/sofa-rpc#611]
我想要能在rpc 各个节点之间共享 当前request的用户信息比如 当前登录的用id,
本来是想通过穿透数据传递的，但是在穿透各个上下文之中获取不到requestContext, 有没有办法能够做到，比如filter？

**Comment by leizhiyuan** [comment]
requestContext？ 这是哪个类？

如果是非敏感信息，用tracer的透传也可以的。

**Comment by 17733106917** [comment]
能说详细一点吗

**Comment by Honestman22** [comment]
你好能说详细一点吗

**Comment by leizhiyuan** [comment]
tracer是链路透传的。可以向tracer中放一下。
