### ISSUE TITLE
使用Annotation方式回调无响应

### ISSUE THREAD

**Issue by BINGW2019** [sofastack/sofa-rpc#614]
### Your question

使用Annotation方式回调无响应，配置文件方式成功

### Your scenes

  /**
     * callback调用
     */
//    @SofaReference(interfaceType = DemoFacadeService.class, binding = @SofaReferenceBinding(bindingType = "bolt", invokeType = "callback", callbackRef = "testSofaResponseCallback"))
    @Autowired
    private DemoFacadeService demoFacadeService3;

### Your advice

describe the advice or solution you'd like

### Environment
-RPC-SOFA-BOOT-STARTER version:6.0.1
- SOFARPC version: 5.5.1
- JVM version 1.8.0_212
- OS version : win10
- Maven version: 3.6.1
- IDE version: IDEA 2019

**Comment by JervyShi** [comment]
@BINGW2019 看 issue 描述 `@SofaReference` 是被注释的状态？有可复现 demo 么？

**Comment by BINGW2019** [comment]
@JervyShi 注释的代码就是demo，使用注解方式不可以我改成了xml方式

**Comment by opjk** [comment]
同上，注释方式回调失败。
测试了一下，能够走到服务端，也能生成 response，但是代码走不到  回调接口中的任何方法。
代码

- 服务发布

@Slf4j
@SofaService(interfaceType = SofaRpcBaseService.class, bindings = {@SofaServiceBinding(bindingType = "bolt")})
public class SofaRpcBaseServiceImpl implements SofaRpcBaseService {
    @Override
    public String getServiceName(String name) {
        String rs = name + " server time is=" + System.currentTimeMillis();
        log.info(" SofaRpcBaseServiceImpl = {}", rs);
        return rs;
    }
}

- 服务引用


    @SofaReference(interfaceType = SofaRpcBaseService.class, binding = @SofaReferenceBinding(
            bindingType = "bolt",
            invokeType = "callback",
            callbackRef = "gridntCallBack",
            directUrl = "192.168.8.13"))
    private SofaRpcBaseService sofaRpcBaseService;

- 回调接口

@Slf4j
@Component("gridntCallBack")
public class GridntCallBack implements SofaResponseCallback {


    @Override
    public void onAppResponse(Object appResponse, String methodName, RequestBase request) {

        log.info("your args is {},GridntCallBack time is {}",
                Arrays.asList(request.getMethodArgs()), System.currentTimeMillis());
    }

    @Override
    public void onAppException(Throwable throwable, String methodName, RequestBase request) {
        log.error("GridntCallBaclk failed ", throwable);
    }

    @Override
    public void onSofaException(SofaRpcException sofaException, String methodName, RequestBase request) {
        log.error("GridntCallBaclk  onSofaException failed ", sofaException);
    }
}

**Comment by leizhiyuan** [comment]
看了一下。你目前需要使用的是callbackHandler = "gridntCallBack",


![image](https://user-images.githubusercontent.com/2684384/77029823-c7d91800-69d7-11ea-89ab-98869547dfba.png)

**Comment by leizhiyuan** [comment]
sofaboot 340解决。 参见 refer
