### ISSUE TITLE
 provider.dynamic 配置不生效

### ISSUE THREAD

**Issue by OrezzerO** [sofastack/sofa-rpc#620]
### Describe the bug
我在 rpc-config.json 中设置`  "provider.dynamic": false` . debug ZookeeperRegistry 中代码, 发现 zk 中 path 的 data 已经设置为 `com.alipay.sofa.rpc.registry.zk.ZookeeperRegistry#PROVIDER_OFFLINE` . 当我启动客户端的时候, 客户端还能正常连接服务端.  这和我的预期不一致.  

PS: 我在源码中搜索 `PROVIDER_OFFLINE`,也没有看到其他引用它的地方, 是不是这个功能还没好?

### Environment

- SOFARPC version:
- JVM version (e.g. `java -version`):
- OS version (e.g. `uname -a`):
- Maven version:
- IDE version:

**Comment by leizhiyuan** [comment]
我看下

**Comment by leizhiyuan** [comment]
是的，这个目前预留。还未完成。

**Comment by OrezzerO** [comment]
现在我想控制项目发布,但不自动注册,有好的办法吗? 用 自定义 Router 来做这个事情?

**Comment by leizhiyuan** [comment]
描述下你期望的整个流程？假设这个功能完成，你如何使用？

**Comment by OrezzerO** [comment]
1. Provider A 发布, 注册中心能感知到 Provider A 已经发布, 但是此时 Consumer B不能调用刚发布的这个 Provider A
2. 在某个 WebConsle 上, 点击发布更改注册中心状态, 此时 Consumer B 可以消费 Provider A.
3. 当 Provider A 重启后(IP不变) ,Consumer B 能消费 ProviderA 

以上就是我期望的流程

**Comment by leizhiyuan** [comment]
@glmapper 这个我们一起看下，sofa-dashboard 看看能否支持上

**Comment by OrezzerO** [comment]
@leizhiyuan @glmapper  我准备开始做这个功能了, 具体方案我们一起讨论一下?
