### ISSUE TITLE
bom 依赖关系的问题

### ISSUE THREAD

**Issue by OrezzerO** [sofastack/sofa-rpc#625]
### Your question
源码中有一个bom 模块,它是 `sofa-rpc-parent` 的子 module ,但 bom 模块没有指定 `<parent>`.
在 `sofa-rpc-parent ` 中,  dependencyManagement 指定了 sofa-rpc-bom. 

我的问题是: 

 bom 是 parent 的子 module ,maven 处理时先处理 parent ,然后就先处理 parent 的 dependencyManagement, 这时候 就要引入 bom ,可这个时候这个 bom 还没有被处理, 为什么没有报错呢?

@ujjboy 
### Your scenes

describe your use scenes (why need this feature)

### Your advice

describe the advice or solution you'd like

### Environment

- SOFARPC version:
- JVM version (e.g. `java -version`):
- OS version (e.g. `uname -a`):
- Maven version:
- IDE version:

**Comment by ujjboy** [comment]
Sorry, 刚看到。

先说下 `sofa-rpc-bom` 的作用，这个是为了管理项目自身各个模块的依赖版本的，不是为了给使用者用的。 

为什么看着像是循环依赖但是不报错呢？我觉得其实是因为 maven project 下的 modules 并不决定依赖关系，只是标识模块目标结构。 `dependencyManagement` 的作用也是管理依赖版本，也不决定模块依赖关系。决定模块依赖关系的是 `parent` 和 `dependency` 这两个。

所以实际构建顺序是： parent -> 各模块 -> all -> bom/test

**Comment by leizhiyuan** [comment]
如果没问题，先关闭了。如果还有问题，可以再打开讨论
