### ISSUE TITLE
sofa有server端降级功能吗

### ISSUE THREAD

**Issue by huangyunbin** [sofastack/sofa-rpc#626]
我说的降级是server端主动降级，直接返回错误码或者是fallback返回一些固定数据。
server端主动降级的场景也挺多，比如大促的时候，关掉一些不重要的服务。

目前看到是有自动故障剔除，但是这个是client做的事情，而且会经过多次失败或超时才会剔除。

**Comment by leizhiyuan** [comment]
你说的更像是服务端限流，目前开源 RPC 接入了hystrix，稍后我们提供个demo出来。

**Comment by huangyunbin** [comment]
> 你说的更像是服务端限流，目前开源 RPC 接入了hystrix，稍后我们提供个demo出来。

全部限流掉，是可以做到类似降级的操作。不过server端降级有更加丰富的功能，比如可以执行fallback逻辑。
hystrix这个主要是在client端做的事情吧。当然一些观点认为client有fallback就好了，server端是不需要有fallback的，不知道你们怎么看这个。我是觉得两边都是可以有的。

**Comment by ScienJus** [comment]
> hystrix这个主要是在client端做的事情吧。当然一些观点认为client有fallback就好了，server端是不需要有fallback的，不知道你们怎么看这个。我是觉得两边都是可以有的。

我觉得这个想法很正确，client 端和 server 端的限流、fallback 都是有其特殊场景的。

> 比如大促的时候，关掉一些不重要的服务

如果是 client 端直接关闭调用，以 hystrix 为例，可以通过 `circuitBreaker.forceOpen` 强制开启熔断，它的好处是省去了一次无意义的网络请求，所以在系统稳定性或是性能问题时更加有优势。但是它的缺点是管理更加复杂，因为一般一组 provider 会有 n 组 consumer，每一组 consumer 都需要独立的开启和关闭。

而 server 端限流在管理上会更加集中，通过令牌桶等 rate limit 算法也会更加准确，不过这个例子更像是服务治理相关的功能，通过后台控制开关强制某些 provider 触发 fallback 逻辑？
