### ISSUE TITLE
自动故障剔除的最小权重默认是1，那这样会一直异常报错？

### ISSUE THREAD

**Issue by huangyunbin** [sofastack/sofa-rpc#628]
假设服务3台机器，总的qps是3000，其中一台有问题，自动故障剔除权重变为1，其他两台权重是100，那么有问题的机器每秒的请求是 3000/201=15，这样每秒还是有15个异常请求。
每秒都有不少异常请求，而且还可能一直持续，这个对于一些服务不太能接受的吧？

但是好像又不能设置最小权重为0，为0的话就没有请求，就恢复不了权重，就算恢复正常也就一直没请求了。

**Comment by leizhiyuan** [comment]
你分析的是对的，所以这个值是可以配置的。根据用户的需求来决定。

比如有些用户有自己的监控平台，他发现之后，可以自己重启，他就可以配置成0，一点都不要调用。

**Comment by leizhiyuan** [comment]
如果还有其他问题，可以再打开讨论。
