### ISSUE TITLE
Extension 的 Order 和 Filter 的 Order 的问题

### ISSUE THREAD

**Issue by OrezzerO** [sofastack/sofa-rpc#632]
### Describe the bug

在 `Extension.java` 中, order 的注释是:
```java
   /**
     * 优先级排序，默认不需要，大的优先级高
     *
     * @return 排序
     */ 
    int order() default 0;
```

然而在 Filter 排序的时候, Filter 是按照从小到大排的, 反而是 order 小的优先级高. 
### Expected behavior
我们把注释改成这样子?:
```
      /**
     * 优先级排序，默认不需要，在单例扩展中大的优先级高,在多例扩展中,按从小到大排序
     *
     * @return 排序
     */ 
    int order() default 0;
```

### Environment

- SOFARPC version:
- JVM version (e.g. `java -version`):
- OS version (e.g. `uname -a`):
- Maven version:
- IDE version:

**Comment by OrezzerO** [comment]
相关代码:[Extention load Order](https://github.com/sofastack/sofa-rpc/blob/3e8bbf61896277c5d561f7e8f132e3d11ee0bfad/core/api/src/main/java/com/alipay/sofa/rpc/ext/ExtensionLoader.java#L268)  和 [Filter 处理 Order](https://github.com/sofastack/sofa-rpc/blob/5d0d8a8b30ba250cc6b50344c16a26b8fdb7b5c3/core/api/src/main/java/com/alipay/sofa/rpc/filter/FilterChain.java#L227)

**Comment by ujjboy** [comment]
扩展点本身是越大越优先，大的可以覆盖小的，然后各个 ExtensionLoader 拿到扩展点后可以自己再用这个排序的，这个无法限制。

例如 filter 拿到排序自己从小到大排，只是代表请求的顺序吧，A(1) -> B(2)  -> C(3) -> 调远程 -> C(3) -> B(2)  -> A(1)

**Comment by OrezzerO** [comment]
我是觉得注释有点不太恰当, 如果不需要改,可以关闭这个 Issue. thx

**Comment by ujjboy** [comment]
我觉得 `大的优先级高` 这个可以去掉。 也不用加其它描述了，各种使用排序的地方单独注释。

**Comment by leizhiyuan** [comment]
ok，下次其他pr里顺便将这行注释去掉。

**Comment by leizhiyuan** [comment]
remove the comment in https://github.com/sofastack/sofa-rpc/pull/674
