### ISSUE TITLE
本地文件系统作为注册中心有性能问题吗

### ISSUE THREAD

**Issue by opjkjava** [sofastack/sofa-rpc#635]
### Your question
文档中有一段话如下：
“SOFABoot RPC Starter 为用户提供多种注册中心选择和方便的配置。 目前 bolt ， rest ， dubbo 都支持 Zookeeper 作为注册中心。另外 bolt ， rest 支持本地文件系统作为注册中心，该种模式一般用于测试。”

“该种模式一般用于测试”， 是性能有问题，还是安全有问题，不适合在生产环境中使用？

describe your question clearly

### Your scenes

describe your use scenes (why need this feature)

### Your advice

describe the advice or solution you'd like

### Environment

- SOFARPC version:
- JVM version (e.g. `java -version`):
- OS version (e.g. `uname -a`):
- Maven version:
- IDE version:

**Comment by ujjboy** [comment]
@opjkjava 仅仅是为了方便开发测试，这样的话不需要在本地开发的时候启动一个注册中心。

**Comment by zonghaishang** [comment]
仅仅用于本地开发测试和验证(适合同一台机器服务的发布和消费)， 不具备远程分发和订阅能力
