### ISSUE TITLE
注册中心不支持自定义域名(hosts)

### ISSUE THREAD

**Issue by gocreater** [sofastack/sofa-rpc#636]
### Describe the bug

注册中心不支持自定义域名,或者自定义hosts,使用自定义hosts时异常，ConsulURLUtils 中检查限制为ip地址。

### Steps to reproduce
![image](https://user-images.githubusercontent.com/1320187/58363595-68a29800-7ed9-11e9-9ca0-10783829fa37.png)
![image](https://user-images.githubusercontent.com/1320187/58363598-6b9d8880-7ed9-11e9-818b-7c4de098cff6.png)
![image](https://user-images.githubusercontent.com/1320187/58363599-6e987900-7ed9-11e9-870d-45d3cef841b2.png)

### Minimal yet complete reproducer code (or GitHub URL to code)
![image](https://user-images.githubusercontent.com/1320187/58363595-68a29800-7ed9-11e9-9ca0-10783829fa37.png)
![image](https://user-images.githubusercontent.com/1320187/58363598-6b9d8880-7ed9-11e9-818b-7c4de098cff6.png)

### Environment

- SOFARPC version: 5.5.1
- JVM version (e.g. `java -version`): 1.9

**Comment by zonghaishang** [comment]
Fix it this week

**Comment by JervyShi** [comment]
@zonghaishang @gocreater This issue already fixed by @ScienJus in https://github.com/sofastack/sofa-rpc/pull/629 will merge into master after all review done.

**Comment by leizhiyuan** [comment]
fixed in https://github.com/sofastack/sofa-rpc/pull/629
