### ISSUE TITLE
关于sofarpc

### ISSUE THREAD

**Issue by xiaohanfeidao** [sofastack/sofa-rpc#645]
如下：

**Comment by xiaohanfeidao** [comment]
关于sofarpc 使用consul注册中心，消费端不能注册到consul中，
server.port=8082
spring.application.name=digital-ms-gateway-test

logging.path=c:/logs/digital-ms-gateway-test

#com.alipay.sofa.rpc.registryAddress=zookeeper://127.0.0.1:2181
com.alipay.sofa.rpc.registryAddress=consul://127.0.0.1:8500
com.alipay.sofa.rpc.boltPort=12201
com.alipay.sofa.rpc.boltThreadPoolCoreSize=200
com.alipay.sofa.rpc.boltThreadPoolMaxSize=500
com.alipay.sofa.rpc.boltThreadPoolQueueSize=2000
com.alipay.sofa.rpc.boltAcceptsSize=2000


 


<?xml version="1.0"?>
<project xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd" xmlns="http://maven.apache.org/POM/4.0.0"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
  <modelVersion>4.0.0</modelVersion>
  <parent>
    <groupId>com.alipay.sofa</groupId>
    <artifactId>sofaboot-dependencies</artifactId>
    <version>2.5.3</version>
  </parent>
  <groupId>com.digital.ms</groupId>
  <artifactId>digital-ms-dependencies-sofarpc</artifactId>
  <version>1.0.0</version>
  <packaging>pom</packaging>
  <properties>
    <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
  </properties>
  <dependencies>
  	<dependency>
	   <groupId>org.springframework.boot</groupId>
	   <artifactId>spring-boot-starter-web</artifactId>
	   <exclusions>
	      <exclusion>
	         <groupId>org.springframework.boot</groupId>
	         <artifactId>spring-boot-starter-tomcat</artifactId>
	      </exclusion>
	   </exclusions>
	</dependency>
	
	<dependency>
	   <groupId>org.springframework.boot</groupId>
	   <artifactId>spring-boot-starter-undertow</artifactId>
	</dependency>
	
	<dependency>
	     <groupId>com.alipay.sofa</groupId>
	     <artifactId>rpc-sofa-boot-starter</artifactId>
	</dependency>
	
	<dependency>
         <groupId>com.alipay.sofa</groupId>
         <artifactId>tracer-sofa-boot-starter</artifactId>
     </dependency>
     
     <dependency>
	    <groupId>com.alipay.sofa</groupId>
	    <artifactId>healthcheck-sofa-boot-starter</artifactId>
	</dependency>
	
     <dependency>
	     <groupId>io.zipkin.zipkin2</groupId>
	     <artifactId>zipkin</artifactId>
	     <version>2.11.12</version>
	 </dependency>
	 <dependency>
	     <groupId>io.zipkin.reporter2</groupId>
	     <artifactId>zipkin-reporter</artifactId>
	     <version>2.7.13</version>
	 </dependency>
<dependency>
            <groupId>com.ecwid.consul</groupId>
            <artifactId>consul-api</artifactId>
            <version>1.4.0</version>
        </dependency>
  </dependencies>
  
  <build>
		<plugins>
			<plugin>
				<groupId>org.springframework.boot</groupId>
				<artifactId>spring-boot-maven-plugin</artifactId>
			</plugin>
		</plugins>
	</build>
</project>
![image](https://user-images.githubusercontent.com/28434690/58700410-8341a900-83d2-11e9-9713-09e3e1251310.png)
![image](https://user-images.githubusercontent.com/28434690/58700419-8d63a780-83d2-11e9-9259-a7b018c6e2a1.png)
![image](https://user-images.githubusercontent.com/28434690/58700432-948ab580-83d2-11e9-802a-cc367a1b60ff.png)
![image](https://user-images.githubusercontent.com/28434690/58700451-a0767780-83d2-11e9-81dd-9b85d4ce026f.png)

debug到ConsulRegistry#registerEphemralNode 是ok的 返回结果为true，但是consul中不显示
consul 版本consul_1.5.0_windows_amd64
但是服务提供者可以注册进去，换成zk就好用了

**Comment by xiaohanfeidao** [comment]
demo链接：https://github.com/xiaohanfeidao/digital-ms

**Comment by JervyShi** [comment]
@xiaohanfeidao demo 链接是私有 repo 么？我这边访问不到

**Comment by JervyShi** [comment]
Link to https://github.com/sofastack/sofa-rpc/pull/629
