### ISSUE TITLE
传递jpa实体对象报错了，如果传递jpa数据库查询出来的数据？

### ISSUE THREAD

**Issue by cxc3214** [sofastack/sofa-rpc#646]
### 传递jpa实体对象报错了，如果传递jpa数据库查询出来的数据？

https://github.com/cxc3214/sofarpc_test

访问 http://localhost:8888/add 插入两条数据，
再访问 http://localhost:8888/orgs 报错：

`com.alipay.remoting.exception.SerializationException: Server serialize response exception! `

麻烦请指点一下！

**Comment by ScienJus** [comment]
@cxc3214 @zonghaishang 这个是因为 hibernate 用了 lazy 的 one to many 导致的，具体代码是：

https://github.com/cxc3214/sofarpc_test/blob/master/rpctest-face/src/main/java/simple/test/rpctest/entity/Org.java#L60-L64

hibernate 代理过的对象是无法序列化的，所以需要在返回的对象中去掉这种使用方式。

**Comment by cxc3214** [comment]
除此之外，别无他法了.

**Comment by maxid** [comment]
假设是 bolt , 可以 Override BoltServer 的 handleRequest 方法，添加 TransactionTemplate 实现事务，解决 sofa-rpc 序列化 jpa 或 hibernate 的 实体时 lazy 报 no Session 的问题
