### ISSUE TITLE
fix bug of SimpleMapSerializer for null map value

### ISSUE THREAD

**Issue by leizhiyuan** [sofastack/sofa-rpc#652]
### Describe the bug

com.alipay.sofa.rpc.codec.bolt.SimpleMapSerializer#encode
did  not process null value 

### Environment

- SOFARPC version:
- JVM version (e.g. `java -version`):
- OS version (e.g. `uname -a`):
- Maven version:
- IDE version:

**Comment by zonghaishang** [comment]
fixed it, close it now.
