### ISSUE TITLE
Rest 协议不支持透传? 

### ISSUE THREAD

**Issue by OrezzerO** [sofastack/sofa-rpc#663]
### Describe the bug
这样子透传
``` java
RpcInvokeContext.getContext().putRequestBaggage("xxx", "xxx");
```
### Environment

- SOFARPC version:
- JVM version (e.g. `java -version`):
- OS version (e.g. `uname -a`):
- Maven version:
- IDE version:

**Comment by leizhiyuan** [comment]
是的。如果需要。需要添加
```
@Provider
@Priority(100)
public class TraceClientRequestFilter implements ClientRequestFilter {
```

类似这样的filter，将数据放到ClientRequestContext 中

**Comment by OrezzerO** [comment]
恩,我是这样做的,感觉 blot 和 rest 不是用统一接口了 :(

**Comment by leizhiyuan** [comment]
这个可能需要一个pr来完成，内置你写的这两个filter。然后取值进行put。有兴趣的话可以提一个到master？

**Comment by OrezzerO** [comment]
恩,好的:)

**Comment by chpengzh** [comment]
I'll take this.

**Comment by chpengzh** [comment]
Done, should be closed.
