### ISSUE TITLE
sofa-registry demo不能正常运行，是什么原因？

### ISSUE THREAD

**Issue by xiaoni157** [sofastack/sofa-rpc#670]
### Your question

sofa-registry demo不能正常运行，是什么原因？
运行
![image](https://user-images.githubusercontent.com/24448049/59482464-93aa5700-8e9b-11e9-80d6-9b3cb7bc627e.png)这两个demodemo，异常信息如下：
![image](https://user-images.githubusercontent.com/24448049/59482488-a886ea80-8e9b-11e9-897b-2ab1926f4ff0.png)，
![image](https://user-images.githubusercontent.com/24448049/59482506-b5a3d980-8e9b-11e9-80b0-127f0db4866a.png)

### Your scenes

describe your use scenes (why need this feature)

### Your advice

describe the advice or solution you'd like

### Environment

- SOFARPC version:
- JVM version (e.g. `java -version`):
- OS version (e.g. `uname -a`):
- Maven version:
- IDE version:

**Comment by zhaojigang** [comment]
服务没注册成功吧？sofaregistry启动正常吗？

**Comment by xiaoni157** [comment]
嗯 确实是没注册成功，机器锁屏sofaregistry就断了，服务就连不上了，重启sofaregistry 就可以了 谢谢。
