### ISSUE TITLE
大约什么时候会支持 reactive？

### ISSUE THREAD

**Issue by zhaojigang** [sofastack/sofa-rpc#671]
### Your question
大约什么时候会支持 reactive？

**Comment by zonghaishang** [comment]
这个内部在沟通中，有结论会在这里答复你，感谢支持。

**Comment by zhaojigang** [comment]
好的，谢谢！

**Comment by leizhiyuan** [comment]
@zhaojigang 你们是看中这个reactive的什么东西？有没有一些其他更具体的想法？

**Comment by zhaojigang** [comment]
hi，碧神，reactive 我研究的比较少，这里只想到几点：
**1、回调地狱**
假设有这样一段代码
![image](https://user-images.githubusercontent.com/14085645/59602162-ab523b80-9138-11e9-9951-b771b8adc80e.png)
我们如果使用 CompletableFuture，可以以这样类似的方式实现 A.invokeAsync(B).whenComplete(B.invokeAsync(C)).whenComplete(C.invokeAsync(D))，当然这个 CompletableFuture 不知道算不算 reactive 的范畴，用 reactor 应该也能实现，这样编码感觉更流畅一些，更容易实现**链路异步化**

**2、reactor 具有比较多的操作符，组合起来可能能实现更多复杂的功能**

**3、另外一个就是回压和限流，A调用B，到底是B将集群压力反馈回去好，还是直接限流好，这个还没有想清楚**

碧神，你们对于 reactive 现在是怎么看的？

**Comment by leizhiyuan** [comment]
经过内部调研和用户反馈，感觉场景不够强烈。暂时搁置。以后酌情打开。
