### ISSUE TITLE
SofaRegistry 同一条注册数据有重复项，是否可以简化？

### ISSUE THREAD

**Issue by zhaojigang** [sofastack/sofa-rpc#672]
### Your question

SofaRegistry 的 serviceData 默认是：host:port[server.getContextPath()]?rpcVer=当前sofarpc版本&serialization=providerConfig.getSerialization()&weight=providerConfig.getWeight()[&timeout=providerConfig.getTimeout()&appName=providerConfig.getAppName()]&p=xxx&v=4.0&_SERIALIZETYPE=providerConfig.getSerialization()&_WEIGHT=providerConfig.getWeight()[&_TIMEOUT=providerConfig.getTimeout()&app_name=providerConfig.getAppName()&_HOSTMACHINE=xxx&方法级的timeout配置&providerConfig.getParameters()]&startTime=NOW()

其中 providerConfig.getSerialization()、providerConfig.getWeight()、providerConfig.getAppName()、providerConfig.getTimeout() 均使用不同的key注册了两次，是否可以简化？

### Your scenes

describe your use scenes (why need this feature)

### Your advice

describe the advice or solution you'd like

### Environment

- SOFARPC version:
- JVM version (e.g. `java -version`):
- OS version (e.g. `uname -a`):
- Maven version:
- IDE version:

**Comment by leizhiyuan** [comment]
You are right, But It is a compatible issue for some old version in our project.
