### ISSUE TITLE
注册中心log打印需要携带关键信息，比如注册中心地址等

### ISSUE THREAD

**Issue by zonghaishang** [sofastack/sofa-rpc#675]
### Your question

describe your question clearly

### Your scenes

describe your use scenes (why need this feature)

### Your advice

describe the advice or solution you'd like

### Environment

- SOFARPC version:
- JVM version (e.g. `java -version`):
- OS version (e.g. `uname -a`):
- Maven version:
- IDE version:

**Comment by leizhiyuan** [comment]
暂不考虑。
