### ISSUE TITLE
我想用本地SOFARegistry作为注册中心，但是启动有问题

### ISSUE THREAD

**Issue by xiaoni157** [sofastack/sofa-rpc#685]
### Your question

describe your question clearly

1.application.xml
![image](https://user-images.githubusercontent.com/24448049/59917100-9a187000-9453-11e9-82e5-9a5c0ec1c00b.png)

2.console日志
![image](https://user-images.githubusercontent.com/24448049/59917134-b1eff400-9453-11e9-81f3-0a93c3dd4b76.png)

3.pom.xml文件
![image](https://user-images.githubusercontent.com/24448049/59917238-03987e80-9454-11e9-9a47-bedd4ea04bbd.png)

请问我哪里配置的有问题呢？

### Your scenes

describe your use scenes (why need this feature)

### Your advice

describe the advice or solution you'd like

### Environment

- SOFARPC version:
- JVM version (e.g. `java -version`):
- OS version (e.g. `uname -a`):
- Maven version:
- IDE version:

**Comment by zonghaishang** [comment]
@xiaoni157 上传一下demo

**Comment by xiaoni157** [comment]
我用本地SOFARegistry作为注册中心,服务端起来了，客户端调用的时候有异常
![image](https://user-images.githubusercontent.com/24448049/60077346-5461ed00-975c-11e9-8d7e-394b17761ebb.png)
这个是啥原因？

**Comment by zonghaishang** [comment]
上传下demo, 我帮你看下，或者手动加个依赖项试试：
```xml
        <dependency>
            <groupId>com.alipay.sofa</groupId>
            <artifactId>registry-client-all</artifactId>
           <version>5.2.0</version>
        </dependency>
```

**Comment by xiaoni157** [comment]
好的 我已经解决了 谢谢
