### ISSUE TITLE
Consul注册无法使用的问题

### ISSUE THREAD

**Issue by wangyjx** [sofastack/sofa-rpc#687]
### Your question

如何正确的在sofarpc启用consul注册

### Your scenes

在测试sofa-rpc使用consul注册的功能，不在application.properties中加com.alipay.sofa.rpc.registry.address=consul://127.0.0.1:8500  的时候，一切正常。
一旦加上启动就报错
java.lang.NoClassDefFoundError: com/ecwid/consul/v1/ConsulClient

当前项目的maven里面相关dependency:

                 <dependency>
			<groupId>com.alipay.sofa</groupId>
			<artifactId>rpc-sofa-boot-starter</artifactId>
		</dependency>
		

父级项目中：
`        
         <parent> 
		<groupId>com.alipay.sofa</groupId> 
		<artifactId>sofaboot-dependencies</artifactId> 
		<version>3.1.5</version>
	</parent> 
`  
### Environment

- SOFARPC version: 5.5.5
- JVM version (e.g. `java -version`): JDK11.02
- OS version (e.g. `uname -a`): MacOS 10.14.1
- Maven version: 3.6.1
- IDE version: 2019.1

**Comment by ScienJus** [comment]
@wangyjx 请问您使用的是哪个版本的 sofa-rpc 呢？

如果是 5.5.x，可以尝试加入以下依赖：

```
<dependency>
    <groupId>com.ecwid.consul</groupId>
    <artifactId>consul-api</artifactId>
    <version>1.3.0</version>
</dependency>
```

如果是 5.6.x，也同样加入 1.4.2 版本的依赖：

```
<dependency>
    <groupId>com.ecwid.consul</groupId>
    <artifactId>consul-api</artifactId>
    <version>1.4.2</version>
</dependency>
```

**Comment by wangyjx** [comment]
@ScienJus 多谢
我的是5.5.5的RPC，加入上述依赖后不报错了，算是解决了初步的问题。  

不过，consul上显示的service名很奇怪，叫做:   consul-default
ID也很奇怪   叫做  192.168.2.122:12200-null-50505

看来是没有正确传递spring.application.name 或者说还有其他设置需要做才可以正确展示service 吗

**Comment by ScienJus** [comment]
@wangyjx 

首先是 `spring.application.name` 和 `spring.cloud.consul.*` 等配置是在 spring-cloud-consul-discovery 以及其周边组件中所使用的，sofa-rpc 的 consul-registry 并不会读取该配置以及注册对应的信息。

设想一下，sofa-rpc 的注册是以 interface 为粒度的，一个应用可以有多个 interface，难道他们注册时都是同一个 app name 么？这是不合理的。

其次，我看你的配置是希望配置 consul 的 service name 和自定义 http health check，这个在 5.5.x 是没有提供相关配置项的，不过在 5.6.0 版本之后，可以通过一系列配置项进行配置，稍后我尝试提供一个 demo，其大概是：

配置 HTTP 探活：

```
com.alipay.sofa.rpc.registry.address=consul://127.0.0.1:8500?healthCheck.type=http&healthCheck.path=/&healthCheck.interval=10s
```

配置服务别名（默认是 interfaceId）：

```
// xml 方式
<sofa:service ref="helloSyncServiceImpl" interface="com.alipay.sofa.rpc.samples.invoke.HelloSyncService">
    <sofa:binding.bolt/>
</sofa:service>

<sofa:reference id="helloSyncServiceReference" interface="com.alipay.sofa.rpc.samples.invoke.HelloSyncService">
    <sofa:binding.bolt>
        <sofa:parameter key="consulServiceName" value="${spring.application.name}"/>
    </sofa:binding.bolt>
</sofa:reference>

// 注解方式
@SofaReference(
        binding = @SofaReferenceBinding(
                bindingType = "bolt",
                parameters = @SofaParameter(key = "consulServiceName", value = "${spring.application.name}")))

@SofaService(
        bindings = @SofaServiceBinding(
                bindingType = "bolt",
                parameters = @SofaParameter(key = "consulServiceName", value = "${spring.application.name}")))
```

**Comment by wangyjx** [comment]
@ScienJus   非常感谢解答，我看见5.6刚发布了，稍后试试5.6

**Comment by ScienJus** [comment]
@wangyjx 我编写了一个基于 5.6.0 版本 consul registry 的 demo，希望能对你有帮助。

https://github.com/ScienJus/sofa-rpc-consul-registry-demo

**Comment by wangyjx** [comment]
已经使用了5.6，加上这个demo本身运行都是没有问题的。 不过有个问题不知道该怎么做比较好，还请指点。

rpc服务注册是在一个项目，称为项目 A，使用consul注册完全没有问题（和demo一样是注解方式）。

spring.application.name=imp.user.rpc
com.alipay.sofa.rpc.bolt.port=12200
com.alipay.sofa.rpc.registry.address=consul://consul-1:8500


消费在另外一个项目，项目B，这个项目是sofaboot的项目

在application.properties里面加了
