### ISSUE TITLE
registry config [sofa://127.0.0.1:9603] is not supported

### ISSUE THREAD

**Issue by xiaoni157** [sofastack/sofa-rpc#693]
### Your question

我使用sofaregistry作为注册中心，注册了一个服务端的服务，写了一个客户端的服务去调用服务端的方法，使用sofaboot-dependencies 2.6.3和rpc-sofa-boot-starter 5.5.2版本可以正常去调用，加了的日志服务，然后这个版本也还是可以正常调用，但是换成sofaboot-dependencies 3.0.0版本，就有
![image](https://user-images.githubusercontent.com/24448049/60233263-1ab2f280-98d2-11e9-9f8b-3e26116cfc5c.png)
异常了，请问是哪里的问题？

### Your scenes

describe your use scenes (why need this feature)

### Your advice

describe the advice or solution you'd like

### Environment

- SOFARPC version:
- JVM version (e.g. `java -version`):
- OS version (e.g. `uname -a`):
- Maven version:
- IDE version:

**Comment by leizhiyuan** [comment]
升级 sofaboot 3.1.5 看下。3.0.0 里面当时没有这个功能。

https://github.com/sofastack/sofa-rpc-boot-projects/releases

**Comment by xiaoni157** [comment]
嗯 换成sofaboot 3.1.5 版本可以正常调用，请问有没有一个支持的springboot的列表，因为我们以前的老项目的springboot的版本有多个。

**Comment by zonghaishang** [comment]
@leizhiyuan 
https://github.com/sofastack/sofa-rpc-boot-projects/blob/master/sofa-boot-starter/pom.xml
master里面还是3.1.4, 3.1.5在哪里?
