### ISSUE TITLE
REST protocol supports dynamic configuration of timeout

### ISSUE THREAD

**Issue by OrezzerO** [sofastack/sofa-rpc#704]
### Your question

现在 REST 协议是不支持动态配置的.`com.alipay.sofa.rpc.transport.AbstractProxyClientTransport#doInvokeSync` 方法没有使用到 `timeoutMillis` 这个参数. REST 协议的超时时间是在 `com.alipay.sofa.rpc.transport.rest.RestClientTransport#buildProxy` 方法中构造代理时设置的.

有没有一个办法,可以在请求调用时,确定 timeout?

### Your scenes

describe your use scenes (why need this feature)

### Your advice

describe the advice or solution you'd like

### Environment

- SOFARPC version:
- JVM version (e.g. `java -version`):
- OS version (e.g. `uname -a`):
- Maven version:
- IDE version:

**Comment by leizhiyuan** [comment]
目前似乎没有。先关闭了。

**Comment by xuyihuang** [comment]
这个问题现在有修复了吗

**Comment by xuyihuang** [comment]
> 目前似乎没有。先关闭了。
这个问题最新的版本有修复了吗？

**Comment by EvenLjj** [comment]
@xuyihuang 
Currently not support this feature, if you are interested, you can try to support the feature, welcome to submit a PR.
