### ISSUE TITLE
Does zookeeper version must be 3.5.x ?

### ISSUE THREAD

**Issue by OrezzerO** [sofastack/sofa-rpc#711]
### Your question
In sofa-rpc-all:5.6.0 , curator version is 4.0.1. It  enforece zk version to be 3.5.x. Users who use zk 3.4.x need to upgrade zk. If it is what we expect that we want to enforece our users to use zk 3.5..x, we need to  declare it in README.md.

### Your scenes

describe your use scenes (why need this feature)

### Your advice

describe the advice or solution you'd like

### Environment

- SOFARPC version:
- JVM version (e.g. `java -version`):
- OS version (e.g. `uname -a`):
- Maven version:
- IDE version:

**Comment by JervyShi** [comment]
引入 zookeeper `3.5.x` 是为了在 `Spring Cloud` 环境下可正常使用 sofa-rpc ，是由 curator `4.0.1` 引入的，最早有用户来报这个问题也比较久了，可以参见 #331 。5.6.0 作为大版本，我们有在 [Release Note](https://github.com/sofastack/sofa-rpc/releases/tag/v5.6.0) 中提到这次变更 。RPC 本身在 zookeeper `3.5.x` 以下也还是可以继续运行的，你可以尝试排除掉 zookeeper 和 curator 来引入你希望使用的版本，如有新问题欢迎反馈~

**Comment by OrezzerO** [comment]
@JervyShi  恩,需要引入老版本的 curator 之后重新打包一遍 sofa-rpc.

**Comment by JervyShi** [comment]
@OrezzerO OK

**Comment by skybluehhx** [comment]
Apache Curator is meant to be used with ZooKeeper 3.5+. However, it is also compatible with ZooKeeper 3.4.x. See Compatibility for details   Change your ZK version, see  http://curator.apache.org/ ,
