### ISSUE TITLE
Modified the call exception between the hessian4 rpc.

### ISSUE THREAD

**Issue by xiaoni157** [sofastack/sofa-rpc#713]
### Your question

describe your question clearly
1.自己编译服务端SOFARegistry，修改hessian版本为4.0.3，编译成功通过，然后server端和client端修改hessian版本为4.0.3，启动都没有问题， 调用的时候出现了
![image](https://user-images.githubusercontent.com/24448049/60695181-6b9a9a80-9f13-11e9-9129-04b80f836eac.png)异常。

我看 https://github.com/sofastack/sofa-rpc/issues/217 这个issue，上面有提到
![image](https://user-images.githubusercontent.com/24448049/60695222-9127a400-9f13-11e9-9365-925f148849d7.png)，我想问你们解决这个问题了没？还是说我也要这么去编译源码才能解决这个问题。

### Your scenes

describe your use scenes (why need this feature)

### Your advice

describe the advice or solution you'd like

### Environment

- SOFARPC version:
- JVM version (e.g. `java -version`):
- OS version (e.g. `uname -a`):
- Maven version:
- IDE version:

**Comment by leizhiyuan** [comment]
不能使用原生的hessian 版本

使用sofa-hessian 的4.0.3 版本
https://github.com/sofastack/sofa-hessian/releases/tag/v4.0.3

**Comment by xiaoni157** [comment]
我用的就是sofa-hessian的4.0.3版本
![image](https://user-images.githubusercontent.com/24448049/60704069-fc826d80-9f35-11e9-8ebc-b1c8f04a3c40.png)

**Comment by leizhiyuan** [comment]
如果已经使用了这个版本，可以`mvn dependency:tree > x.log`  发一下x.log,

**Comment by zonghaishang** [comment]
按照leizhiyuan说明在项目根目录中执行 `mvn dependency:tree > x.log`， 然后提供上传下x.log文件

**Comment by xiaoni157** [comment]
我先问一下 是服务端和客户端在启动的时候都需要加-Ds=hessian4 这个参数是么？

**Comment by zonghaishang** [comment]
@xiaoni157 没有指定hessian4这种用法，可以用类似`-Ddefault.serialization=hessian2`覆盖；看起来你本地有冲突包导致的，需要提供tree log。不然没办法帮你深入分析。

**Comment by xiaoni157** [comment]
![image](https://user-images.githubusercontent.com/24448049/60781140-b87cac00-a173-11e9-8e39-5fbaf087655c.png)
![image](https://user-images.githubusercontent.com/24448049/60781148-bd416000-a173-11e9-9286-f4ac30018f2c.png)

**Comment by zonghaishang** [comment]
> 我先问一下 是服务端和客户端在启动的时候都需要加-Ds=hessian4 这个参数是么？

我在master分支和5.5分支，都没有找到`com.alipay.sofa.rpc.codec.sofahessian.SofaHessianSerializer#getSerializerFactory`支持`hessian4`序列化的代码。@leizhiyuan 你回复的代码在哪个分支

@xiaoni157 提供下使用的sofa-rpc-all版本。 在项目根目录执行 mvn dependency:tree > x.log， 然后提供上传下x.log文件。

**Comment by xiaoni157** [comment]
你先看一下#217这个问题，我是按照这上面直接修改的源码文件，加上的
![image](https://user-images.githubusercontent.com/24448049/61345001-ea81c280-a885-11e9-8631-e121dcc5ee51.png)这个

**Comment by mayqxp** [comment]
> 我先问一下 是服务端和客户端在启动的时候都需要加-Ds=hessian4 这个参数是么？

不需要

**Comment by leizhiyuan** [comment]
以下已经不需要，只要将项目中的hessian3排掉，使用sofa-hessian 的4.0.3及以上的版本即可
