### ISSUE TITLE
consumerConfig.refer() The entire process duration

### ISSUE THREAD

**Issue by uugit** [sofastack/sofa-rpc#718]
### Your question

![image](https://user-images.githubusercontent.com/6504355/61122409-4f2ecd00-a4d4-11e9-8b7c-cef512adfefb.png)

 consumerConfig.refer()  服务消费者启动类ConsumerBootstrap引用服务 整个过程会消耗的时长很长么

我通过打log 发现这个过程  消耗3s 多 , 如果类似于图中 SampleService  有多个Service , 在调用这个refer方法时, 是不是有点久 
### Environment

- SOFARPC version: sofarpc -5.5.1
- JVM version (e.g. `java -version`): jdk10
- OS version (e.g. `uname -a`): mac
- Maven version: 3.3.3
- IDE version: 2019.1

**Comment by ujjboy** [comment]
@uugit  如果服务端有很多服务端，目前是会去并发全部建连。你日志里有建连超时的场景吗？

**Comment by uugit** [comment]
目前只是在起服务的时候发现时间很长, 要等好久, 查了一下, 结果是在rpc refer 这个块比较耗时 , 我们有多个service ,一个service要3s ,  所以咨询下

**Comment by leizhiyuan** [comment]
如果确实有必要，可以设置addressWaitTime 为一个比较小的值。

**Comment by leizhiyuan** [comment]
如果还有问题，可以打开。
