### ISSUE TITLE
sofarpc + sofaregistry集群部署 ，rpc服务器重启后无法获得注册地址

### ISSUE THREAD

**Issue by spaceandroid** [sofastack/sofa-rpc#720]
sofarpc和sofaregistry集群部署后，客户端用jdk1.6一直在发数据，sofarpc服务端一台down后重启，再也无法接收到数据？重启后是没有重新获得服务列表数据吗？客户端在jkd1.7下运行没有问题。

- SOFARPC version:5.5.6
- JVM version (e.g. `java -version`):server:1.8，client:1.6
- OS version (e.g. `uname -a`):linux
- Maven version:3.5.2
- IDE version:idea

**Comment by leizhiyuan** [comment]
> 一直在发数据？ 

这个是什么意思？有客户端logs/registry 这个目录下的日志没？

**Comment by spaceandroid** [comment]
日志信息：RPC:02306:没有获得服务[.....:1.0]的调用地址，请检查服务是否已经推送。
客户端重启后才能重新获得服务。
