### ISSUE TITLE
new sofa-rpc and old zookeeper problem

### ISSUE THREAD

**Issue by patofan** [sofastack/sofa-rpc#721]
New sofa-rpc  5.6.0 and zookeeper 3.4.6  problem

I use the new version sofa-rpc  5.6.0 and old zookeeper 3.4.6 , the service cant not register in
zookeeper . 

### Environment

- SOFARPC version: 5.6.0
- JVM version (e.g. `java -version`): jdk8u212-b04
- OS version (e.g. `uname -a`): Windows 10
- Maven version:  3.5.3
- IDE version:  Eclipse 2018-09 (4.9.0)

**Comment by OrezzerO** [comment]
see #711

**Comment by JervyShi** [comment]
@OrezzerO Thanks a lot.
