### ISSUE TITLE
Rest CORS cross-domain problem Access-Control-Allow

### ISSUE THREAD

**Issue by jimchou800** [sofastack/sofa-rpc#727]
### Your question
使用rest协议暴露服务，并尝试用swagger-ui 渲染rest api json : http://192.168.36.205:8341/swagger/openapi  但是报了一个错误:

```
Possible cross-origin (CORS) issue? The URL origin (http://127.0.0.1:8341) does not match the page (http://192.168.36.205:8000). Check the server returns the correct 'Access-Control-Allow-*' headers.
```

### Your scenes

想通过swagger api文档形式，把api提供给调用者

### Your advice
提供跨域支持

### Environment

- SOFARPC version: 5.5
- JVM version (e.g. `java -version`): 1.8
- OS version (e.g. `uname -a`): 
- Maven version:
- IDE version:

**Comment by ScienJus** [comment]
@jimchou800 这个应该是跨域问题，可以参考 https://www.sofastack.tech/projects/sofa-rpc/restful-swagger/ 这一章看一下增加跨域配置是否能解决。

**Comment by jimchou800** [comment]
非常感谢
