### ISSUE TITLE
Little white trouble asks the god, when the server calls the RPC service, does this error pop up? (A lot of online search did not find)

### ISSUE THREAD

**Issue by husnhb** [sofastack/sofa-rpc#729]
### Your question

客户端开放一个rpc服务，比如接口IBizManageService，然后接口中有方法A，客户端发布服务；服务端引用服务，然后调用方法A。然后访问服务端的时候，弹出这个错误
![image](https://user-images.githubusercontent.com/4240892/62524886-023ade00-b869-11e9-87f7-cf308804038c.png)

### Your scenes

describe your use scenes (why need this feature)

### Your advice

describe the advice or solution you'd like

### Environment

- SOFARPC version: 5.6.0
- JVM version (e.g. `java -version`): 1.8.0_201
- OS version (e.g. `uname -a`):win10
- Maven version: 3.3.9
- IDE version: eclipse

**Comment by leizhiyuan** [comment]
hessian3 不支持对Object o =xx 这样的Object类型的序列化。

**Comment by leizhiyuan** [comment]
可以考虑使用具体类型。
