### ISSUE TITLE
SOFA integration NACOS

### ISSUE THREAD

**Issue by dodo4** [sofastack/sofa-rpc#730]
SOFA-RPC集成NACOS注册中心失败。
application.properteis配置：
spring.application.name=DemoProvider
com.alipay.sofa.rpc.registry.address=nacos://127.0.0.1:8848
nacos.config.server-addr=127.0.0.1:8848
nacos.discovery.server-addr=127.0.0.1:8848
nacos.config.namespace=Public
nacos.config.group=DEFAULT_GROUP
....省略其它

sofaboot-dependencies版本：3.1.4
rpc-sofa-boot-starter版本：6.0.2
registry-client-all版本：5.2.1
nacos版本：1.1.0
资料参考：
https://nacos.io/zh-cn/docs/quick-start-spring-boot.html
https://yq.aliyun.com/articles/692508

单应用按此配置，@NacosValue获取不到配置，nacos的服务列表也没有任何服务。应用是正常启动的

**Comment by JervyShi** [comment]
@dodo4 It seems that you try to startup nacos server inside your project, please try to startup nacos server standalone, https://nacos.io/zh-cn/docs/quick-start.html , we only test with independent nacos server.

**Comment by dodo4** [comment]
> @dodo4 It seems that you try to startup nacos server inside your project, please try to startup nacos server standalone, https://nacos.io/zh-cn/docs/quick-start.html , we only test with independent nacos server.

Modify application.properties：
com.alipay.sofa.rpc.registry.address=nacos://192.168.36.8:8848
nacos.config.server-addr=192.168.36.8:8848
nacos.discovery.server-addr=192.168.36.8:8848

The problem what to do next remains unsolved

**Comment by JervyShi** [comment]
```
nacos.config.server-addr=192.168.36.8:8848
nacos.discovery.server-addr=192.168.36.8:8848
```
SOFA RPC using nacos does not depend on the above configuration. Can you provide a minimum reproducible project?

**Comment by JervyShi** [comment]
```
nacos.config.server-addr=192.168.36.8:8848
nacos.discovery.server-addr=192.168.36.8:8848
```
SOFA RPC using nacos does not depend on the above configuration. Can you provide a minimum reproducible project?

**Comment by dodo4** [comment]
> SOFA RPC using nacos does not depend on the above configuration. Can you provide a minimum reproducible project?

https://github.com/dodo4/lab.git
THKS

**Comment by JervyShi** [comment]
Link #717 , looks like the same issue.

**Comment by JervyShi** [comment]
@dodo4 I use your project https://github.com/dodo4/lab.git and comment out nacos related configuration such as `@NacosPropertySource` `@NacosValue` and change sofa rpc registry config to `com.alipay.sofa.rpc.registry.address=nacos://127.0.0.1:8848/public`(nacos console show public namespace service list by default).  Then start the project, it works fine.

![image](https://user-images.githubusercontent.com/1862729/63072899-b2d76a80-bf58-11e9-89d8-0ab37ea2c3f3.png)

**Comment by JervyShi** [comment]
Using nacos with sofa rpc, you do not really need `nacos-discovery-spring-boot-starter` etc.

**Comment by dodo4** [comment]
> @dodo4 I use your project https://github.com/dodo4/lab.git and comment out nacos related configuration such as `@NacosPropertySource` `@NacosValue` and change sofa rpc registry config to `com.alipay.sofa.rpc.registry.address=nacos://127.0.0.1:8848/public`(nacos console show public namespace service list by default). Then start the project, it works fine.
> 
> ![image](https://user-images.githubusercontent.com/1862729/63072899-b2d76a80-bf58-11e9-89d8-0ab37ea2c3f3.png)
THKS！！！
the problems have now been sorte

**Comment by dodo4** [comment]
> @dodo4 I use your project https://github.com/dodo4/lab.git and comment out nacos related configuration such as `@NacosPropertySource` `@NacosValue` and change sofa rpc registry config to `com.alipay.sofa.rpc.registry.address=nacos://127.0.0.1:8848/public`(nacos console show public namespace service list by default). Then start the project, it works fine.
> 
> ![image](https://user-images.githubusercontent.com/1862729/63072899-b2d76a80-bf58-11e9-89d8-0ab37ea2c3f3.png)

but ,craete namespace "testNS",  nacos service list is empty
