### ISSUE TITLE
The framework should support message size limits. For example, if the size exceeds 8M, an exception will be thrown.

### ISSUE THREAD

**Issue by zonghaishang** [sofastack/sofa-rpc#734]
### Your question

describe your question clearly

### Your scenes

describe your use scenes (why need this feature)

### Your advice

describe the advice or solution you'd like

### Environment

- SOFARPC version:
- JVM version (e.g. `java -version`):
- OS version (e.g. `uname -a`):
- Maven version:
- IDE version:

**Comment by devYun** [comment]
序列化完之后会做一个数据大小的统计，是不是可以在那里进行设置？

**Comment by leizhiyuan** [comment]
the limit will take effect for the biz which has
 runed in prod.
