### ISSUE TITLE
How to extend user type serializer for bolt hessian2

### ISSUE THREAD

**Issue by maxid** [sofastack/sofa-rpc#736]
### Your question
How to extend user type serializer, like "org.joda.time.DateTime"
describe your question clearly

### Your scenes

describe your use scenes (why need this feature)

### Your advice

describe the advice or solution you'd like

### Environment

- SOFARPC version: 3.1.5
- JVM version (e.g. `java -version`): jdk8
- OS version (e.g. `uname -a`): macos
- Maven version:
- IDE version:

**Comment by leizhiyuan** [comment]
please pr for the hessian  project

https://github.com/sofastack/sofa-hessian
