### ISSUE TITLE
LEAK: ByteBuf.release() REST协议内存泄漏

### ISSUE THREAD

**Issue by liangpdu** [sofastack/sofa-rpc#750]
### Describe the bug

LEAK: ByteBuf.release() REST协议堆外内存泄漏。每次物理内存使用率达到65%左右系统就挂了。
通过查看内存使用情况。发现JVM的堆内存使用情况非常正常。查看应用进程的内存使用情况发现堆外内存使用了2G左右。通过查看堆外内存的内容都是netty http 报文的内存 包括 method,uri, header,body的信息

### Environment

- SOFARPC version:5.4.7
- JVM version (e.g. `java -version`):1.8
- OS version (e.g. `uname -a`):
- Maven version:
- IDE version:

**Comment by leizhiyuan** [comment]
https://github.com/sofastack/sofa-rpc/releases/tag/v5.5.7 5.5.7 fix了

**Comment by liangpdu** [comment]
直接升级sofa-rpc 5.5.7 报Caused by: java.lang.ClassNotFoundException: com.alipay.sofa.rpc.config.JAXRSProviderManager 错误

**Comment by liangpdu** [comment]
@leizhiyuan 您好，用的是sofaboot-dependencies 3.0.0，sofa-rpc 是5.4.7，改成sofa-rpc 5.5.7后发现bolt的版本是1.4.6，原来是1.4.7。比原来低了会有版本兼容问题吗

**Comment by liangpdu** [comment]
经过验证，确实可以
