### ISSUE TITLE
Open source version of RPC, using api refer mode, the cache does not take effect, causing refer times to exceed the limit

### ISSUE THREAD

**Issue by mingluxml** [sofastack/sofa-rpc#755]
### Describe the bug
在通过api方式进行RPC refer，多次调用后客户端出现报错：“ Caused by: com.alipay.sofa.rpc.core.exception.SofaRpcRuntimeException: Duplicate consumer config with key bolt://com.alipay.ap.bcriskvariable.facade.api.ParameterValidateService:rds has been referred more than 3 times! Maybe it's wrong config,  please check it. Ignore this if you did that on purpose!”。
在客户端其实有进行remove操作：referenceClient.removeReference(referenceParam);
跟踪代码发现，在remove过程中，使用binding，从当前全局缓存的ConcurrentHashMap中remove掉此reference时，失败了。具体截图如下：
![image](https://user-images.githubusercontent.com/54924358/64309540-628b7f80-cfcf-11e9-8771-e33bc9fe55d8.png)

### Expected behavior
1：每次reference应该是取缓存，而不是不断的新增reference
2：referenceClient.removeReference(referenceParam);缓存被移除，计数清0

### Actual behavior
1：每次refer都会新建一个reference，有可能会内存溢出
![image](https://user-images.githubusercontent.com/54924358/64311338-5ce56800-cfd6-11e9-99ae-c62d6af71db6.png)

2：referenceClient.removeReference没有生效
### Minimal yet complete reproducer code (or GitHub URL to code)
`        ReferenceClient referenceClient = clientFactory.getClient(ReferenceClient.class);
        ReferenceParam<VariableValidateService> referenceParam = new ReferenceParam<>();
        referenceParam.setInterfaceType(VariableValidateService.class);
        BoltBindingParam refBindingParam = new BoltBindingParam();
        setVip(refBindingParam, ipAddress);
        referenceParam.setBindingParam(refBindingParam);
        referenceParam.setUniqueId(rdsUuid);
        ValidateExecResult result = callFunction.apply(referenceClient.reference(referenceParam));
        //must clean
        referenceClient.removeReference(referenceParam);`
### Environment

- SOFARPC version:
![image](https://user-images.githubusercontent.com/54924358/64311506-f57be800-cfd6-11e9-8267-46d6184e829b.png)

- JVM version (e.g. `java -version`):
jdk1.8
- OS version (e.g. `uname -a`):
- Maven version:
- IDE version:

**Comment by leizhiyuan** [comment]
哪个版本？

**Comment by leizhiyuan** [comment]
https://github.com/sofastack/sofa-rpc-boot-projects/releases/tag/v6.0.4 has fixed

you can try
