### ISSUE TITLE
Can RESTful protocol method return Object?

### ISSUE THREAD

**Issue by YuGe** [sofastack/sofa-rpc#757]
### Your question

Can RESTful protocol method return Object?

### Your scenes

I tried to return an Object with RESTful protocol, but Exception NoMessageBodyWriterFoundFailure was thrown. I've tried to add  `@Produces` annotation, but still failed.
I think it will be much more convenient to return an Object.

### Your advice

Support return Object.

### Environment

- SOFARPC version: com.alipay.sofa:sofa-rpc-all:5.6.1
- JVM version (e.g. `java -version`): openjdk version "1.8.0_222"
- OS version (e.g. `uname -a`): Darwin MacBook-Pro.local 18.7.0
- Maven version: Gradle 5.2.1
- IDE version: Intellij 2019.2

**Comment by leizhiyuan** [comment]
麻烦提供一下复现的demo

暂时关闭，如果有更新，欢迎再次打开。
