### ISSUE TITLE
A SofaRouteException will occur when the service is started multiple times when using nacos as the service registry.

### ISSUE THREAD

**Issue by dxp909** [sofastack/sofa-rpc#763]
### Describe the bug

使用nacos作为服务注册中心，当服务提供端第一次启动时，服务发现调用都没有问题，当把服务重启（在同一台服务器上，使用相同的boltPort）后，就会引发SofaRouteException异常。具体异常信息如下：
com.alipay.sofa.rpc.core.exception.SofaRouteException: RPC-02312: 当前服务[XXXService:1.0]的地址[bolt://IP地址:PORT?accepts=100000&appName=message&weight=100&language=java&pid=2132&interface=XXXService&timeout=0&serialization=hessian2&protocol=bolt&delay=-1&sofa.group=test&dynamic=true&startTime=1568781552627&id=rpc-cfg-3&uniqueId=&rpcVer=50505,]不可用,或指定的地址不在可用的地址列表中 

### Environment
- SOFARPC version:5.5.5
- JVM version (e.g. `java -version`):1.8
- OS version (e.g. `uname -a`):windows10
- Maven version:3.6

**Comment by dxp909** [comment]
使用的是sofa-boot 3.1.5

**Comment by khotyn** [comment]
@dxp909 看起来和 https://github.com/sofastack/sofa-rpc/issues/664 有关，这个问题已经 Fix 了，可以使用 SOFABoot 3.2.0 看下，我本地试了是 OK 的。

**Comment by dxp909** [comment]
ok，我升级下试试，@khotyn 多谢
