### ISSUE TITLE
SofaRpc uses Nacos as a registration center, registration failed due to version

### ISSUE THREAD

**Issue by Jerveen** [sofastack/sofa-rpc#774]
### Your question
我在使用Nacos作为服务的注册中心，因为SofaBoot、SofaRpc、Nacos的版本问题出现注册失败的原因
### Your scenes
①当我使用SofaBoot的版本为2.5.3、SofaRpc的Starter版本为5.5.0、Nacos版本为0.6.0时，此时可以再Nacos成功注册服务，并且调用均正常
②当我使用SofaBoot的版本为3.1.0、SofaRpc的Starter版本为6.0.0、Nacos版本为1.1.0时，此时会报如下错误：com.alipay.sofa.rpc.boot.common.SofaBootRpcRuntimeException: registry config [nacos://127.0.0.1:8848] is not supported

![image](https://user-images.githubusercontent.com/34495476/65667504-71b39980-e072-11e9-8d13-8cc1da1c0963.png)

我更换版本试了很多次都是相同的结果，所以想请教一下是什么原因？
### Environment

- SOFARPC version: 6.0.0
- JVM version (e.g. `java -version`): 1.8
- OS version (e.g. `uname -a`): Windows 7
- Maven version: 3.6.0
- IDE version: 2019.2

**Comment by khotyn** [comment]
麻烦使用 SOFABoot 3.2.0 看下，这个问题应该在 SOFARPC Starter 5.6.0 里面 Fix 了。
