### ISSUE TITLE
Sofaboot/SofaRpc cluster configuration lacks broadcast mechanism

### ISSUE THREAD

**Issue by forsake0120** [sofastack/sofa-rpc#781]
Sofaboot/SofaRpc集群配置缺少广播机制，无法通过配置实现消息广播。
对于例如本地缓存刷新，消息通知等无法很好地实现，希望可以通过提交相关修改增加该配置与功能

**Comment by leizhiyuan** [comment]
can you provider a clearly desc for your scene? maybe the eventbus can be ok
?

**Comment by forsake0120** [comment]
对于集群情况，服务端是否可以通知所有消费者（例如刷新缓存等），类似dubbo：    
<dubbo:registry address="multicast://224.5.6.7:1234" />
也许可以在负载均衡配置中增加“广播”的属性？

**Comment by leizhiyuan** [comment]
@OrezzerO 565中开发。sofaboot对应的bean配置记得同步改。

**Comment by OrezzerO** [comment]
@forsake0120  I'd like to develop a multicast registry module like dubbo. It is used to pub and sub service . It seems nothing to do with updating cache and it may not work as you expected. So ,can you supply a more specific usage?
