### ISSUE TITLE
com.alipay.sofa.rpc.common.json.BeanSerializer will modify the bean object?

### ISSUE THREAD

**Issue by thespit** [sofastack/sofa-rpc#801]
### Your question

BeanSerializer里的serialize方法，在处理Collection和List的时候都会new ArrayList<>()去构建序列化结果。为什么到了Map的时候，就直接把bean变成map，并往里put东西呢？map的value几乎都被替换成LinkedHashMap了。

### Your advice

是不是应该new一个HashMap来记录序列化结果呢。

### Environment

- SOFARPC version: 5.4.8
- JVM version (e.g. `java -version`): 1.8.0_221
- OS version (e.g. `uname -a`): Darwin Kernel Version 17.7.0，10.13.6
- Maven version: 3.5.4
- IDE version: Intellij Community 2019.2

**Comment by ujjboy** [comment]
该类只是简单的内部解析json的类。 LinkedHashMap 作用主要是为了保证 kv 对的原来顺序。

**Comment by thespit** [comment]
我的疑问是，为什么不new一个HashMap来代替bean，现在是直接把bean本身强转成Map进行修改。
而且JSON.toJSONString是对外的方法，并且和fastJson的对外接口一模一样，一旦import错误就会导致严重后果。

**Comment by leizhiyuan** [comment]
1.减少内存占用。
2.这个确实是目前存在的问题。后续可以优化，不过现在基本上很多三方的类都有可能重名。。

还有问题的话，可以再打开。
