### ISSUE TITLE
Latest version of example has problems with missing classes

### ISSUE THREAD

**Issue by qiankunshe** [sofastack/sofa-rpc#825]
### Your question

最新版本的 example 有问题 缺少 类
https://github.com/sofastack/sofa-rpc/tree/master/example
![image](https://user-images.githubusercontent.com/3595926/71066751-3c6ca280-21ae-11ea-8752-2472ffa5f99c.png)
包路径也有问题
### Your scenes

describe your use scenes (why need this feature)

### Your advice

describe the advice or solution you'd like

### Environment

- SOFARPC version: 
- JVM version (e.g. `java -version`): jdk 1.8
- OS version (e.g. `uname -a`): window10
- Maven version: 3.4
- IDE version: idea

**Comment by leizhiyuan** [comment]
直接mvn clean install 即可

这个类是通过mvn 插件生成的。

**Comment by zonghaishang** [comment]
请参楼上的方法，先close，有问题再反馈，thanks.
