### ISSUE TITLE
zookeeper注册中心的线程数量和连接数量的问题

### ISSUE THREAD

**Issue by guyeu** [sofastack/sofa-rpc#837]
### Your question

每个服务都可能export若干个provider，zookeeper注册中心。sofarpc似乎会为zookeeper里注册的每个provider创建一个线程，且和每个集群内的服务建立连接。是不是有什么办法可以使用一个公共的自定义线程池，且限制建立连接的数目或者让连接可配置呢

### Your scenes

一个集群大概有数百个服务，而服务可以大概分成几十个组，只有组内需要互相进行rpc调用。希望限制连接和线程，避免资源浪费。

### Your advice

请告诉我是否有方案实现如上需求。

### Environment

- SOFARPC version: 5.5.1
- JVM version: jdk11
- OS version: ```Linux bogon 3.10.0-957.1.3.el7.x86_64 #1 SMP Thu Nov 29 14:49:43 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux```
- Maven version: 3.6.2

**Comment by zonghaishang** [comment]
sofarpc似乎会为zookeeper里注册的每个provider创建一个线程
----
你是指com.alipay.sofa.rpc.bootstrap.DefaultProviderBootstrap#export中`factory.newThread`?

**Comment by zonghaishang** [comment]
是不是有什么办法可以使用一个公共的自定义线程池，且限制建立连接的数目或者让连接可配置呢
-----
这个是指consumer和集群里所有provider建立连接（限制这个连接？）

**Comment by guyeu** [comment]
> ## sofarpc似乎会为zookeeper里注册的每个provider创建一个线程
> 你是指com.alipay.sofa.rpc.bootstrap.DefaultProviderBootstrap#export中`factory.newThread`?

是的；


> ## 是不是有什么办法可以使用一个公共的自定义线程池，且限制建立连接的数目或者让连接可配置呢
> 这个是指consumer和集群里所有provider建立连接（限制这个连接？）

是的；


另外，也希望是否可以从外部传入一个CuratorFramework实例，同一个服务有两个zookeeper客户端实例也怪怪的。
