### ISSUE TITLE
Cache in AbstractInterfaceConfig

### ISSUE THREAD

**Issue by uugit** [sofastack/sofa-rpc#838]
AbstractInterfaceConfig 中的cache  , 请问下 为true 和为false的区别是什么? sofa底层好像并没有调用
是否启动结果缓存, 这个结果是什么结果 ?

### Your scenes

describe your use scenes (why need this feature)

### Your advice

describe the advice or solution you'd like

### Environment

- SOFARPC version:
- JVM version (e.g. `java -version`):
- OS version (e.g. `uname -a`):
- Maven version:
- IDE version:

**Comment by zonghaishang** [comment]
我check了代码，这个cache没有使用

**Comment by uugit** [comment]
感谢回复! 
如果没有用这个cache的话,  还用一个类似的问题: ProviderConfig 中的executor,  是不是也没有使用啊?   而要使用自定义线程池: 必须是  com.alipay.sofa.rpc.server.UserThreadPool   ?

**Comment by leizhiyuan** [comment]
恩，没有使用。只能用com.alipay.sofa.rpc.server.UserThreadPool

**Comment by uugit** [comment]
好的感谢~
