### ISSUE TITLE
com.alipay.sofa.rpc.core.exception.SofaRouteException: RPC-02312

### ISSUE THREAD

**Issue by 995158803** [sofastack/sofa-rpc#839]
### Your question
每次重启sofarpc项目，经常会报错com.alipay.sofa.rpc.core.exception.SofaRouteException: RPC-02312，The service addresses [bolt://172.16.12.185:9088?version=1.0&accepts=100000&weight=100&language=java&pid=23513&interface=**&timeout=0&serialization=hessian2&protocol=bolt&delay=-1&dynamic=true&startTime=1577931716895&id=rpc-cfg-1&uniqueId=&rpcVer=50509,bolt://172.16.12.185:9089?version=1.0&accepts=100000&weight=100&language=java&pid=23722&interface=**&timeout=0&serialization=hessian2&protocol=bolt&delay=-1&dynamic=true&startTime=1577932261971&id=rpc-cfg-1&uniqueId=&rpcVer=50509,] of service [**:1.0] is not available,or specify url not exist in providers

多重启几次就可以找到address，然后启动成功，不清楚是什么原因

### Environment

- SOFARPC version:    <dependency>
            <groupId>com.alipay.sofa</groupId>
            <artifactId>sofa-rpc-all</artifactId>
            <version>5.5.9</version>
        </dependency>
- JVM version (e.g. `java -version`):   1.8
- OS version (e.g. `uname -a`):   linux7.4
--register ： zookeeper
    <dependency>
        <groupId>org.apache.curator</groupId>
        <artifactId>curator-recipes</artifactId>
        <version>2.9.1</version>
        </dependency>

**Comment by leizhiyuan** [comment]
这个报错是地址连接不上，可以在报错的时候，telnet 一下报错的目标机器。

**Comment by leizhiyuan** [comment]
可以升级到最新版本看下，如果还有问题，可以再打开。
