### ISSUE TITLE
Resteasy upgrade to version 3.6.3, will lead to master rest conflict error

### ISSUE THREAD

**Issue by zonghaishang** [sofastack/sofa-rpc#840]
### Describe the bug

resteasy升级到3.6.3版本, 会携带api依赖版本较低
org.jboss.spec.javax.ws.rs:jboss-jaxrs-api_2.1_spec:jar:1.0.2.Final

会报错：
java.lang.AbstractMethodError: javax.ws.rs.core.Response$ResponseBuilder.status(ILjava/lang/String;)Ljavax/ws/rs/core/Response$ResponseBuilder;

### Environment

- SOFARPC version:
- JVM version (e.g. `java -version`):
- OS version (e.g. `uname -a`):
- Maven version:
- IDE version:

**Comment by OrezzerO** [comment]
这个应该不是依赖版本过低, 而是另一个包也含有 `javax/ws/rs/core/Response` 这个类,冲突了
