### ISSUE TITLE
 Java class located out of the Sources root 

### ISSUE THREAD

**Issue by moonwalk008** [sofastack/sofa-rpc#841]
### Describe the bug
1. 我们开源版和商业版，下载示例项目导入后，都会出现 Java class located out of the Sources root 这种问题，虽然通过重新add content root 可以解决，但是，出现问题的原因是什么呢？有没有方法可以避免这种情形的出现呢？
When the SOFARPC demo was downloaded from [here](https://www.sofastack.tech/projects/sofa-rpc/getting-started-with-rpc/), and was opened in IDEA, the error indicated as "Java class located out of the Sources root" occurred as shown in the screenshot below. Althrough it was solved by adding content root in modules in project setting, I wonder the reason leading to this error and whether there is a possible way to avoid it. Please be advised to add the note to remaind the user of the right way to open or import the demo project.
![image](https://user-images.githubusercontent.com/4928323/71704688-c22b5780-2e16-11ea-80eb-346076a23e12.png)
2. 开源版 快速入门，提到添加依赖：
`<dependency>
    <groupId>com.alipay.sofa</groupId>
    <artifactId>sofa-rpc-all</artifactId>
    <version>最新版本</version>
</dependency>`
但是在示例项目中，该依赖是在all/pom.xml 和 example/pom.xml 中，是否在快速入门中补充一下，不同pom之间的关系以及该依赖添加版本号的具体位置，否则容易和项目的pom混淆。

In the quick start [here](https://www.sofastack.tech/projects/sofa-rpc/getting-started-with-rpc/), it was mentioned to update the version of the dependency below:
`<dependency>
    <groupId>com.alipay.sofa</groupId>
    <artifactId>sofa-rpc-all</artifactId>
    <version>the latest version </version>
</dependency>`
But in the demo provided in this page, this dependency was included in all/pom.xml and example/pom.xml, but not in the pom.xml under sofa-rpc-master package. There might be confusions for new users like me when i was trying to locate this dependency and figure out the differences between these three pom.xml. Pls evaluate the necessity to add a note in the quick start to clarify the differences and help the user to explicitly nail the location.
THX

### Environment

- SOFARPC version:
- JVM version (e.g. `java -version`):
- OS version (e.g. `uname -a`):
- Maven version:
- IDE version:

**Comment by ujjboy** [comment]
1. IDEA 和 Eclipse 不一样，使用 IDEA 的话在 import project 的时候最好选到 repo（sofaboot-rpcdemo-server） 这一层。

2. 你说的示例项目是指哪个？

**Comment by moonwalk008** [comment]
> 1. IDEA 和 Eclipse 不一样，使用 IDEA 的话在 import project 的时候最好选到 repo（sofaboot-rpcdemo-server） 这一层。
> 2. 你说的示例项目是指哪个？
https://www.sofastack.tech/projects/sofa-rpc/getting-started-with-rpc/ 就是快速入门页面提供的示例哦

**Comment by leizhiyuan** [comment]
似乎没有遇到过。  这个应该是用户默认sdk没选？
![image](https://user-images.githubusercontent.com/2684384/76960698-eea33a00-6956-11ea-864a-b72548368a94.png)

**Comment by leizhiyuan** [comment]
还有问题的话，可以再打开。
