### ISSUE TITLE
Multi protocol only bolt is effective,rest is not effective

### ISSUE THREAD

**Issue by zjcscut** [sofastack/sofa-rpc#843]
### Multi Protocol Only Bolt Is Effective

I use SOFARPC to export an interface `HelloService`：

```java
// 接口
@Path("rest")
public interface HelloService {

    @GET
    @Path(value = "/sayHello/{name}")
    String sayHello(@PathParam("name") String name);
}

// 实现类
@Service
@SofaService(
        interfaceType = HelloService.class, bindings = {
        @SofaServiceBinding(bindingType = "bolt"),
        @SofaServiceBinding(bindingType = "rest")
})
public class DefaultHelloService implements HelloService {

    @Override
    public String sayHello(String name) {
        return String.format("%s say hello!", name);
    }
}
```

Then,I startup my server and register  `HelloService` into nacos-server.When I use SOFARPC(base on SOFABoot) to call `HelloService#sayHello()` by REST protocol or use browser to visit `http://localhost:9092/rest/sayHello/throwable`,an exception with '404' happens.Client's code like this：

```java
@Slf4j
@SpringBootApplication(scanBasePackages = {"club.throwable.client", "club.throwable.contract"})
public class ClientApplication implements CommandLineRunner {

//    @SofaReference(binding = @SofaReferenceBinding(bindingType = "bolt"))
//    private HelloService boltHelloService;

    @SofaReference(binding = @SofaReferenceBinding(bindingType = "rest"))
    private HelloService restHelloService;

    public static void main(String[] args) {
        SpringApplication.run(ClientApplication.class, args);
    }

    @Override
    public void run(String... args) throws Exception {
//        log.info("Bolt调用HelloService#sayHello(),结果:{}", boltHelloService.sayHello("throwable"));
        log.info("Rest调用HelloService#sayHello(),结果:{}", restHelloService.sayHello("throwable"));
    }
}
```

### My Scenes

Like above，I could not call remoting service with REST protocol.

### My Demo Project Is Here

Github Repository：https://github.com/zjcscut/framework-mesh/tree/master/spring-boot-nacos

### Environment

- SOFARPC version: 5.6.1
- JVM version (e.g. `java -version`): 1.8
- OS version (e.g. `uname -a`): Windows 7
- Maven version: 3.6.1
- IDE version: IDEA
- SOFABoot version: 3.2.0

**Comment by leizhiyuan** [comment]
rest 不兼容
![image](https://user-images.githubusercontent.com/2684384/77031022-6024cc00-69db-11ea-8b84-22f142255ffb.png)


可以升级到 331即可。

![Uploading image.png…]()
