### ISSUE TITLE
Why start RestServer when Register Processor?

### ISSUE THREAD

**Issue by liangpdu** [sofastack/sofa-rpc#845]
### Your question
Rest服务，为什么在注册请求调用器时启动RestServer？看代码好像这种提前启动不可以关闭。

### Your scenes

有什么办法可以检测到什么时候所有的请求处理器都注册完了吗

### Your advice

1.可以提供所有的请求处理器都注册完了的通知
2.RestServer可以在所有的请求处理器都注册完了才启动

### Environment

- SOFARPC version:5.5.7
- JVM version (e.g. `java -version`):1.8
- OS version (e.g. `uname -a`):
- Maven version:
- IDE version:

**Comment by leizhiyuan** [comment]
在sofaboot的场景下，先注册，但是服务并不会启动。所以你可以监听启动完成事件。
