### ISSUE TITLE
Can we integrate with Sentinel？

### ISSUE THREAD

**Issue by leizhiyuan** [sofastack/sofa-rpc#864]
### Your question

describe your question clearly

### Your scenes

describe your use scenes (why need this feature)

### Your advice

describe the advice or solution you'd like

### Environment

- SOFARPC version:
- JVM version (e.g. `java -version`):
- OS version (e.g. `uname -a`):
- Maven version:
- IDE version:

**Comment by OrezzerO** [comment]
Sentinel  has  already support sofa rpc. Some more details : https://github.com/alibaba/Sentinel/tree/master/sentinel-adapter/sentinel-sofa-rpc-adapter
