### ISSUE TITLE
com.alipay.remoting.rpc.exception.InvokeTimeoutException: Rpc invocation timeout[responseCommand TIMEOUT]!

### ISSUE THREAD

**Issue by GohnGM** [sofastack/sofa-rpc#895]
### Your question

com.alipay.remoting.rpc.exception.InvokeTimeoutException: Rpc invocation timeout[responseCommand TIMEOUT]!

### Your scenes

在 SOFABoot 环境下,通过注解的方式SOFARPC 服务发布与引用
场景如下:
A-B 正常执行，正常返回无超时异常
A-B-C 正常执行，无返回，抛出异常TIMEOUT

### Your advice

注解方式调用，有没有像XML方式那样详细的boot全局配置超时、权重、传输等配置。

### Environment

- SOFARPC version:
sofaboot.version3.1.3
sofa.rpc.starter.version6.0.1
- JVM version (e.g. `java -version`):1.8
- OS version (e.g. `uname -a`):windows10
- Maven version:latest
- IDE version:latest

**Comment by OrezzerO** [comment]
1. 使用注解,超时时间没有全局统一的配置, 
2. 不建议修改权重,如果真要修改,可以把具体例子拿出来详细聊一下
3.  其他全局配置可以在 rpc-config.json 中配置, 全部可以配置的选项可以查看 rpc-config-default.json 
4. 还可以看下  SofaBootRpcProperties 中有没有你想要修改的配置

**Comment by GohnGM** [comment]
因为目前项目使用的dubbo，超时是统一设定的，打算用sofa项目做升级所以在做测试；目前这个场景又出现了一个新的问题，会报class cast转换异常，不知道是不是超时引起的：
xxx cannot be cast to xxx，而且xxx是完全一样的继承了Serializable的业务实体。

**Comment by OrezzerO** [comment]
可以提供下详细堆栈或者复现 demo . 另外,使用 bolt 不强制要求实现 Serializable.

**Comment by GohnGM** [comment]
非常抱歉，经过排查应该是项目其他依赖包冲突导致。非常感谢您的回答，不过我还是希望能提供类似rpc-boo那样的t全局配置的入口。
