### ISSUE TITLE
Docker IP registration configuration problem in sofa-rpc project

### ISSUE THREAD

**Issue by GohnGM** [sofastack/sofa-rpc#901]
Your question
有没有提供类似dubbo那样的参数配置呢？
如下：
DUBBO_IP_TO_REGISTRY --- 注册到注册中心的IP地址
DUBBO_PORT_TO_REGISTRY --- 注册到注册中心的端口
DUBBO_IP_TO_BIND --- 监听IP地址
DUBBO_PORT_TO_BIND --- 监听端口

Your scenes
在 SOFABoot 环境下,通过注解的方式SOFARPC 服务部署在docker中发布与引用
场景如下:
docker 中的应用服务注册后，消费时从zookeeper中获取的IP地址并不是宿主IP，而是docker分配的虚拟IP地址。

Your advice
我详细看了rpc-config-default.json 也没找到。希望得到答复。

Environment
SOFARPC version:
sofaboot.version3.1.3
sofa.rpc.starter.version6.0.1
JVM version (e.g. java -version):1.8
OS version (e.g. uname -a):windows10
Maven version:latest
IDE version:latest

**Comment by ujjboy** [comment]
参考：https://www.sofastack.tech/projects/sofa-rpc/application-rpc-config/

com.alipay.sofa.rpc.virtual.host
com.alipay.sofa.rpc.virtual.port

不知道是不是你想要的功能

**Comment by GohnGM** [comment]
> 参考：https://www.sofastack.tech/projects/sofa-rpc/application-rpc-config/
> 
> com.alipay.sofa.rpc.virtual.host
> com.alipay.sofa.rpc.virtual.port
> 
> 不知道是不是你想要的功能

是的，非常感谢，看了源码，找到了。
ServerConfig server = (ServerConfig)i$.next();
StringBuilder sb = new StringBuilder(200);
String host = server.getVirtualHost();
if (host == null) {
    host = server.getHost();
    if (NetUtils.isLocalHost(host) || NetUtils.isAnyHost(host)) {
        host = SystemInfo.getLocalHost();
    }
}

Map<String, String> metaData = convertProviderToMap(providerConfig, server);
sb.append(server.getProtocol()).append("://").append(host).append(":").append(server.getPort()).append(server.getContextPath()).append("?version=1.0").append(convertMap2Pair(metaData));
urls.add(sb.toString());
