### ISSUE TITLE
Error when switching from Bolt protocol to H2C protocol

### ISSUE THREAD

**Issue by Divernia** [sofastack/sofa-rpc#902]
### Your question

项目在Bolt协议下可以正常使用，但是切换至H2C协议后出现如下错误：
RPC-020100011 (错误提示中调用方法和服务名是反的)：
未找到需要调用的方法：[com.xxx.svc.xxx]；服务名为：[xxx] 

### Environment

- SOFARPC version: 5.6.5
- JVM version (e.g. `java -version`): 1.8
- OS version (e.g. `uname -a`): Win10
- Maven version: 3.5
- IDE version: STS4

**Comment by khotyn** [comment]
请提供一下相关的配置信息。

**Comment by yirenkeji555** [comment]
我这边也经常出现这个问题
