### ISSUE TITLE
Custom load balancing algorithm

### ISSUE THREAD

**Issue by qinliang373** [sofastack/sofa-rpc#910]
### Your question
正在使用nacos 1.0 sofaboot 3.1.3
describe your question clearly
目前最新sofarpc版本是否支持naocs权重与上下线功能，sofarpc有没有灰度发布的功能？项目中需要实现负载均衡算法，需要实现哪个接口？
### Your scenes

describe your use scenes (why need this feature)

### Your advice

describe the advice or solution you'd like

### Environment

- SOFARPC version:
- JVM version (e.g. `java -version`):
- OS version (e.g. `uname -a`):
- Maven version:
- IDE version:

**Comment by OrezzerO** [comment]
@qinliang373 
 1.  不支持naocs原生的权重, 我们把自己的权重属性放到 naocs 中的 metadata 中
2. 负载均衡算法 实现 `com.alipay.sofa.rpc.client.LoadBalancer` 和[自定义路由类似](https://www.sofastack.tech/projects/sofa-rpc/custom-router/), 可以自定义负载均衡算法
3. 上下线和灰度需要发布系统来控制, RPC 本身并不负责这块功能

**Comment by qinliang373** [comment]
@OrezzerO 好的了解谢谢！
