### ISSUE TITLE
For advice, the sofarpc picture client jvm reports oom when the picture data transmission background is a null problem, what can be solved?

### ISSUE THREAD

**Issue by spaceandroid** [sofastack/sofa-rpc#923]
求教，sofarpc传图片客户端jvm报oom时图片数据传输后台是空值问题，有什么能解决的？

### Environment

- SOFARPC version:5.2.1
- JVM version (e.g. `java -version`):1.7
- OS version (e.g. `uname -a`):centos7.0
- Maven version:
- IDE version:

**Comment by OrezzerO** [comment]
Please provider us more details about the question.
