### ISSUE TITLE
How to implement port adaptation?

### ISSUE THREAD

**Issue by Haze-Lan** [sofastack/sofa-rpc#926]
看到配置文档里面有写  “  默认端口 bolt:12200  ”，这样在同一台机器上启动多个实例就会冲突，如果全部手动设置端口的话可以解决这个问题，但是得做端口管理。另外看到https://www.sofastack.tech/projects/sofa-rpc/configuration-common/ 的ServerConfig 部分有个参数是处理这个情况的

adaptivePort | 是否调整端口 | false | 当端口被占用，自动+1进行适应

但是目前sofaboot 不支持这个参数，所以请问下有什么方案可以做端口自适应么？

**Comment by OrezzerO** [comment]
可以通过 java system properties 进行设置:  
```
-Dserver.adaptive.port=true
```

**Comment by Haze-Lan** [comment]
解决了，非常感谢。
