### ISSUE TITLE
sofa泛化调用是否需要指定directUrl

### ISSUE THREAD

**Issue by dpqian** [sofastack/sofa-rpc#928]
### Your question

官网的泛化调用demo地址为https://www.sofastack.tech/projects/sofa-rpc/generic-invoke，代码如下：
ConsumerConfig<GenericService> consumerConfig = new ConsumerConfig<GenericService>()
           .setInterfaceId("com.alipay.sofa.rpc.quickstart.HelloService")
           .setGeneric(true);
GenericService testService = consumerConfig.refer();

String result = (String) testService.$invoke("sayHello", new String[] { "java.lang.String" },new Object[] { "1111" });

这段代码里consumerConfig没有指定directUrl，那么是如何获取服务地址的？自己测试时，如果不指定directUrl，那么会报找不到服务的错误；如果指定directUrl，可以正常调用。所以想问一下到底需不需要指定？

**Comment by ujjboy** [comment]
你这个跟是否跟泛化调用没关系。 RPC 调用肯定是要拿到对方的服务端地址的，这里要么走注册中心去做服务发现，要么走指定直连地址。

**Comment by dpqian** [comment]
明白，我的意思是官网的demo里面没指定url，那么他是怎么调用成功的？既然官网没有指定，为什么我不指定就调用不到？

**Comment by dpqian** [comment]
> 你这个跟是否跟泛化调用没关系。 RPC 调用肯定是要拿到对方的服务端地址的，这里要么走注册中心去做服务发现，要么走指定直连地址。

明白，我的意思是官网的demo里面没指定url，那么他是怎么调用成功的？既然官网没有指定，为什么我不指定就调用不到？另外附加一个问题，如果说一定要指定地址，那么我指定成SLB地址，由SLB去分发，是否可行？

**Comment by ujjboy** [comment]
你说官网的demo 是哪个？

**Comment by dpqian** [comment]
> 你说官网的demo 是哪个？

https://www.sofastack.tech/projects/sofa-rpc/generic-invoke

**Comment by ujjboy** [comment]
哦 这里应该是代码片段，不是完整demo。  example 可以参加 https://github.com/sofastack/sofa-rpc/blob/master/example/src/test/java/com/alipay/sofa/rpc/invoke/generic/GenericClientMain.java

指定成SLB地址是可以的，不过是 slb 跟服务端是长连接，建立了就不断了，服务端负载不一定会均衡。

**Comment by dpqian** [comment]
> 哦 这里应该是代码片段，不是完整demo。 example 可以参加 https://github.com/sofastack/sofa-rpc/blob/master/example/src/test/java/com/alipay/sofa/rpc/invoke/generic/GenericClientMain.java
> 
> 指定成SLB地址是可以的，不过是 slb 跟服务端是长连接，建立了就不断了，服务端负载不一定会均衡。

好的，是否可以认为如果像demo里这样调用，就必须指定directUrl？

**Comment by ujjboy** [comment]
对，使用zk为注册中心的例子就是 https://github.com/sofastack/sofa-rpc/blob/master/example/src/test/java/com/alipay/sofa/rpc/zookeeper/start/ZookeeperBoltClientMain.java

**Comment by dpqian** [comment]
> 对，使用zk为注册中心的例子就是 https://github.com/sofastack/sofa-rpc/blob/master/example/src/test/java/com/alipay/sofa/rpc/zookeeper/start/ZookeeperBoltClientMain.java

这里的address是注册中心的地址还是服务地址，如果是注册中心地址，是不是我只要指定注册中心地址，就能调用发布到中心里的所有服务了？
