### ISSUE TITLE
registerCustomSerializer need to be executed only once

### ISSUE THREAD

**Issue by leizhiyuan** [sofastack/sofa-rpc#929]
### Describe the bug

com.alipay.sofa.rpc.codec.bolt.SofaRpcSerializationRegister#registerCustomSerializer

### Environment

- SOFARPC version:
- JVM version (e.g. `java -version`):
- OS version (e.g. `uname -a`):
- Maven version:
- IDE version:

**Comment by guanchao-yang** [comment]
The Error Stack：

![image](https://user-images.githubusercontent.com/32863418/83324963-3c171e00-a29b-11ea-836a-a2752c7333df.png)
