### ISSUE TITLE
建议提供在服务间进行上下文信息传递的SofaRpcContext

### ISSUE THREAD

**Issue by ivan-cloud** [sofastack/sofa-rpc#930]
### Your question
Sofa-RPC支持 HTTP、Rpc 等不同协议，但它有没有提供一个统一的 SofaRpcContext，可以在服务间进行上下文信息传递。
RpcContext是 dubbo 协议的，不支持 rest。
RpcInvokeContext在 rest 协议下测试过也不能进行上下文信息传递。

### Your scenes

我们在使用Sofa-RPC时，需要在服务间进行上下文信息（如当前用户等）的传递。

### Your advice

建议提供一个统一的 SofaRpcContext，可以兼容不同协议下在服务间进行上下文信息传递

### Environment

- SOFARPC version: 5.6.5
- JVM version (e.g. `java -version`): 1.8
- OS version (e.g. `uname -a`): macOS Mojave 10.14.5
- Maven version: 3.6.0
- IDE version: IDEA 2019.1.3

**Comment by ujjboy** [comment]
RpcInvokeContext 是统一的门面， 上下文透传（隐式传参）的原理就是将 KV 从 RpcInvokeContext 里取出来，放到不同的协议的 HEAD 或者 body 里，传到服务端。你可以自己实现一下试试看

bolt 主要是继承 com.alipay.sofa.rpc.filter.Filter#invoke，核心逻辑是
```
String yyy = RpcInvokeContext.getContext().get("xxx");
request.addRequestProp("xxx", yyy);
```

rest 话可以继承 javax.ws.rs.client.ClientRequestFilter#filter，核心逻辑是
```
requestContext.getHeaders().add("xxx", yyy);
```
