### ISSUE TITLE
Can I call the newly added service without restarting the application?

### ISSUE THREAD

**Issue by dpqian** [sofastack/sofa-rpc#932]
### Your question
       正常调用服务需要引入服务的jar包，xml里面也要配置服务。所以如果想引用新的服务，就必须重启应用。现在想在应用部署之后，如果需要调用新的服务，不需要重启我们的应用。
       首先想到泛化调用方式，不需要引入服务的jar包，但是官方文档里需要在xml里引用服务，因此还是需要重启应用。
       然后想到原生API调用方式，即指定注册中心的地址，通过注册中心去调用。官方文档里确实不需要在xml里引用服务，但是好像需要引入服务的jar包？自己测试时如果不引用jar包，则报ClassNotFound。
       两种方法引入服务jar包和xml里引入服务好像都不能同时丢弃，也就是说还是要重启应用。有没有方法不重启应用，调用新增服务？
       另外附加问题：泛化调用只是不需要引jar包，还是需要配xml，那么和正常调用好像区别不大？应用场景在哪里？是否是还未开发完成？
### Your scenes

describe your use scenes (why need this feature)

### Your advice

describe the advice or solution you'd like

### Environment

- SOFARPC version:
- JVM version (e.g. `java -version`):
- OS version (e.g. `uname -a`):
- Maven version:
- IDE version:

**Comment by OrezzerO** [comment]
可以用泛化调用. 启动应用的时候需要初始化泛化调用的服务. 后面调用新增服务可以动态调用.

**Comment by dpqian** [comment]
> 可以用泛化调用. 启动应用的时候需要初始化泛化调用的服务. 后面调用新增服务可以动态调用.

启动时这个服务没有在xml里引用，针对的场景是在应用启动之后，如果有新的需要调用的服务（xml里没配置过），能否不重启应用去调用它？

**Comment by OrezzerO** [comment]
可以, 按照文档: https://www.sofastack.tech/projects/sofa-rpc/generic-invoke/  中 "RPC API" 那种方式配置, 用代码初始化泛化调用服务
