### ISSUE TITLE
Fix possible names

### ISSUE THREAD

**Issue by leizhiyuan** [sofastack/sofa-rpc#935]
### Describe the bug
<img width="1184" alt="image" src="https://user-images.githubusercontent.com/2684384/83472145-24b57c00-a4b9-11ea-8ec7-84d47d7ab1e0.png">

### Environment

- SOFARPC version:
- JVM version (e.g. `java -version`):
- OS version (e.g. `uname -a`):
- Maven version:
- IDE version:

**Comment by gofow** [comment]
`final List<ProviderInfo> oldProviders = oldGroup == null ? null : oldGroup.getProviderInfos();` in ProviderHelper.compareGroup() 
Perhaps there is a possible situation in multithreading: AFTER determining whether 'oldGroup' is null, and BEFORE 'oldGroup.getProviderInfos()' is executed, oldGroup is changed to null.
It‘s hard to reproduce and has a very low probability of occurrence, but my suggestion is to use a temporary variable for subsequent operations. How do you think about? @EvenLjj

**Comment by OrezzerO** [comment]
This bug is fixed by #936 . You can take a look at it. @gofow
