### ISSUE TITLE
com.alipay.sofa.rpc.core.exception.SofaRpcException: java.lang.NullPointerException

### ISSUE THREAD

**Issue by uugit** [sofastack/sofa-rpc#952]
### Your question

中间红色划掉部分是我们的业务调用

![image](https://user-images.githubusercontent.com/6504355/84491893-d7ff4b80-acd7-11ea-865b-50df6be76b82.png)

### Your scenes

describe your use scenes (why need this feature)

### Your advice

describe the advice or solution you'd like

### Environment

- SOFARPC version: 5.6.3
- JVM version (e.g. `java -version`):
- OS version (e.g. `uname -a`):
- Maven version:
- IDE version:

**Comment by leizhiyuan** [comment]
有自己操作过tracer么？这里面不应该为空的。

        clientSpan.setTag(RpcSpanTags.INVOKE_TYPE, request.getInvokeType());

**Comment by uugit** [comment]
对tracer没有操作, 对zk有操作

**Comment by uugit** [comment]
你好, 如果 providerConfig, export 2次,会对tracer 有什么影响么

**Comment by uugit** [comment]
已定位到问题~~感谢!
