### ISSUE TITLE
http://ip:9003/antcloud/antvip/instances/get will print the exception stack every 100 seconds. Is this address required to start any application?

### ISSUE THREAD

**Issue by Apollo2016926** [sofastack/sofa-rpc#961]
![image](https://user-images.githubusercontent.com/22517877/86868208-dffbb100-c106-11ea-9699-9f06d186c249.png)

**Comment by ujjboy** [comment]
@Apollo2016926  你这不是开源版吧？ 如果是商业版可以走云上的工单咨询。

**Comment by zonghaishang** [comment]
看起来是商业版或者主站的版本，走内部linke工单吧。

**Comment by Apollo2016926** [comment]
谢谢各位的解答，我们用的确实是商业版，问题我们已经排查出来了，是由于我们的寻址服务异常导致的这个问题
