### ISSUE TITLE
有关SOFA-RPC性能测试的相关问题

### ISSUE THREAD

**Issue by Tipiger** [sofastack/sofa-rpc#962]
### Your question
关于这份SOFA-RPC性能测试
https://www.sofastack.tech/projects/sofa-rpc/test/

我想要询问的是关于该性能测试的实施细节：
1. 50个客户端进行并发，是使用同一个jvm环境下模拟的50个线程还是建立50个客户端实例？
2.如何进行TPS的数量控制
### Your scenes

describe your use scenes (why need this feature)

### Your advice

describe the advice or solution you'd like

### Environment

- SOFARPC version:
- JVM version (e.g. `java -version`):
- OS version (e.g. `uname -a`):
- Maven version:
- IDE version:

**Comment by ujjboy** [comment]
@Tipiger  这个是内部的测试平台上跑的。  

服务端是1台    客户端是50并发，分散在若干台测试机上   
 tps 是客户端侧控制的速率。

**Comment by OrezzerO** [comment]
暂时关闭,有需要可以打开.
Close this issue temporarily, open it if necessarily.
