### ISSUE TITLE
 Generalized call and warm-up forwarding are used together, the return type is incorrect

### ISSUE THREAD

**Issue by zonghaishang** [sofastack/sofa-rpc#973]
### Actual behavior

![image](https://user-images.githubusercontent.com/15549777/91126222-18b31200-e6d6-11ea-9094-38e7cfffc7d8.png)

### Environment

- SOFARPC version:
- JVM version (e.g. `java -version`):
- OS version (e.g. `uname -a`):
- Maven version:
- IDE version:

**Comment by OrezzerO** [comment]
I have reproduced the case.  `com.alipay.sofa.rpc.api.GenericService#$genericInvoke(java.lang.String, java.lang.String[], java.lang.Object[], com.alipay.sofa.rpc.api.GenericContext)` returns GenericObject  it is in Design . Your can use `com.alipay.sofa.rpc.api.GenericService#$invoke` or `com.alipay.sofa.rpc.api.GenericService#$genericInvoke(java.lang.String, java.lang.String[], java.lang.Object[], java.lang.Class<T>)` instead.
