### ISSUE TITLE
jsr303

### ISSUE THREAD

**Issue by fwei816** [sofastack/sofa-rpc#977]
com.alipay.sofa.rpc.config.AbstractInterfaceConfig.java

/**
     * 是否开启参数验证(jsr303)
     */
    protected boolean                                validation;

是否已经支持了？

配置validation参数后还是无法支持jsr303验证，是否有完善计划？

**Comment by OrezzerO** [comment]
We do not support jsr303 yet. There is no plan to do it . You are welcome to submit pr for this feature.

**Comment by OrezzerO** [comment]
暂时关闭,有需要可以打开.
Close this issue temporarily, open it if necessarily.
