### ISSUE TITLE
sofa 路由问题

### ISSUE THREAD

**Issue by YczYanchengzhe** [sofastack/sofa-rpc#979]
### Your question

describe your question clearly
请问sofa的路由规则是怎么处理服务端重启的那?

### Your scenes

describe your use scenes (why need this feature)
我看了下源码,sofa会在执行过滤器之前先进行路由,在路由出现超时时候会进行重试,那如果服务端发生了重启,这个时候,调用肯定是不通的,此时会按照超时的策略重新路由么~

### Your advice

describe the advice or solution you'd like

### Environment

- SOFARPC version:
- JVM version (e.g. `java -version`):
- OS version (e.g. `uname -a`):
- Maven version:
- IDE version:

**Comment by OrezzerO** [comment]
会调用失败的

**Comment by OrezzerO** [comment]
暂时关闭,有需要可以打开.
Close this issue temporarily, open it if necessarily.
