### ISSUE TITLE
整合nacos问题

### ISSUE THREAD

**Issue by hxy691738337** [sofastack/sofa-rpc#985]
1. sofaboot版本v3.3.0，目前官网文档里只有整合nacos 0.6.0版本的，请问怎么使用nacos的命名空间功能。
2. sofaboot版本v3.3.0，maven引用里nacos-client版本是1.0.0，请问现在支持nacos最新版本是多少。

**Comment by OrezzerO** [comment]
暂时关闭,有需要可以打开.
Close this issue temporarily, open it if necessarily.
