### ISSUE TITLE
关于sofa服务通过zk注册dubbo服务时，能否新增version版本号的配置

### ISSUE THREAD

**Issue by moorefu** [sofastack/sofa-rpc#990]
发现RegistryUtils.convertConsumerToUrl与RegistryUtils.convertProviderToUrl两个方法中的接口版本号是写死的
“version=1.0”，
dubbo方面这个配置值默认是0.0.0也，默认配置的情况下没法跟dubbo注册的服务互相调用。
能否新增一个配置项配置这个版本号呢。

**Comment by OrezzerO** [comment]
印象中已经处理过这个问题了，没处理的话，下个版本会处理。

**Comment by OrezzerO** [comment]
This  pr will  solve the problem : https://github.com/sofastack/sofa-rpc/pull/1033/files

**Comment by EvenLjj** [comment]
@moorefu 已经在 #1033 中修复.
***
@moorefu It has been fixed in #1033.
