### ISSUE TITLE
sofa-rpc现在是否支持在容器环境中获取宿主机IP作为通信IP注册在注册中心中？

### ISSUE THREAD

**Issue by likeonechild** [sofastack/sofa-rpc#992]
### Your question

describe your question clearly
sofa-rpc现在是否支持在容器环境中获取宿主机IP作为通信IP注册在注册中心中？在dubbo中是有一个口子，可以自己通过配置ENV（不是application.yml）设置注册的通信IP，不知道sofa-rpc是否支持这种方式？

### Your scenes

describe your use scenes (why need this feature)

### Your advice

describe the advice or solution you'd like
通过在ENV中获取变量的话，就可以结合k8s动态获取宿主机IP的方式，灵活的实现k8s集群外调用集群内的接口。如果没有这中的话，请问实现k8s集群外调用集群内的接口有什么更好的方式，谢谢。

### Environment

- SOFARPC version:
- JVM version (e.g. `java -version`):
- OS version (e.g. `uname -a`):
- Maven version:
- IDE version:

**Comment by likeonechild** [comment]
CONFIG_RPC_REGISTER_VIRTUAL_HOST   这个东西就声明了一下，压根没用啊。。。。。。。

**Comment by guyeu** [comment]
`ServerConfig#setHost`，可以把宿主机的IP设置进去。

**Comment by likeonechild** [comment]
> `ServerConfig#setHost`，可以把宿主机的IP设置进去。

我看了Registry那块儿的源码，比如DsrRegsitry的，会从CFG中取，我打算在启动的时候从Pod中把宿主机的IP取出来，然后放到System的Properties中，然后放到CFG中，但是我发现我们又用了SofaBoot，哈哈，这几天没顾上弄这个了，暂时还没找到SofaBoot是在哪儿把IP上报到注册中心的，您要有时间给我发个SofaBoot注册RPC那一块儿的类名吧，哈哈，多谢

**Comment by guyeu** [comment]
参阅[这里](https://github.com/sofastack/sofa-boot/blob/master/sofa-boot-project/sofa-boot-core/rpc-sofa-boot/src/main/java/com/alipay/sofa/rpc/boot/config/SofaBootRpcProperties.java)

**Comment by likeonechild** [comment]
> 参阅[这里](https://github.com/sofastack/sofa-boot/blob/master/sofa-boot-project/sofa-boot-core/rpc-sofa-boot/src/main/java/com/alipay/sofa/rpc/boot/config/SofaBootRpcProperties.java)

唉，版本不一样，我们现在用的是这个sofarpc-spring-boot-starter  2.2.5的  这东西也搜不到啥资料，没看明白能不能通过类似这个com.alipay.sofa.rpc.virtual.host设置通信IP，试了这几个参数
com.alipay.sofa.rpc.virtual.host 
com.alipay.sofa.rpc.bound.host 
com.alipay.boot.sofarpc.spring.virtual.host 
com.alipay.boot.sofarpc.spring.bound.host 
com.alipay.boot.sofarpc.spring.rpc.virtual.host 
com.alipay.boot.sofarpc.spring.rpc.bound.host 
rpc.virtual.host 
rpc.bound.host 

都不行


手动笑哭

**Comment by OrezzerO** [comment]
https://www.sofastack.tech/projects/sofa-rpc/application-rpc-config/ 这是配置说明, 可以用com.alipay.sofa.rpc.virtual.host来指定,如果还有问题,可以再打开这个 issue
